// Generated by hand for this game: ordinary Three.js + @threenative/physics.
//
// Static collision for the building.
//
// Built by *reading* the cathedral's scene graph rather than by hand-listing its parts, so
// the colliders cannot drift out of step with geometry another file owns. Every mesh
// contributes an axis-aligned box in world space; instanced meshes contribute one box per
// instance.
//
// Boxes rather than trimeshes on purpose. A gothic pier is a cluster of round shafts and a
// trimesh of it would be thousands of triangles the solver has to walk for a wall that a
// player can only ever bump into sideways. Boxes are what the collision actually needs, and
// they let Rapier keep every one of these as a cheap static cuboid.
import type { IPhysicsContext } from "@threenative/physics";
import { CollisionShape3D, RigidBody3D } from "@threenative/physics";
import { Box3, InstancedMesh, Matrix4, Mesh, Object3D, Vector3 } from "three";

/** Anything smaller than this in every axis is trim, not architecture, and gets no collider. */
const MIN_COLLIDER_EXTENT = 0.25;

/**
 * Objects whose names match are skipped.
 *
 * Glass is a plane inside a window opening the player can never reach; flames and chains are
 * decoration hanging in mid-air. Colliding with them would wall the player out of the aisles
 * for no reason a player could see.
 */
const SKIP = /glass|flame|candle|chain|banner|pane|rose|lancet/i;

const _box = new Box3();
const _size = new Vector3();
const _centre = new Vector3();
const _matrix = new Matrix4();
const _world = new Matrix4();

function addBox(
  ctx: { physics: IPhysicsContext },
  bodies: RigidBody3D[],
  centre: Vector3,
  size: Vector3,
): void {
  if (size.x < MIN_COLLIDER_EXTENT && size.y < MIN_COLLIDER_EXTENT && size.z < MIN_COLLIDER_EXTENT) {
    return;
  }
  // The body needs an object to carry its transform. It is never added to the scene: this is
  // a collider, and drawing it would put a grey box over every pier in the building.
  const anchor = new Object3D();
  anchor.position.copy(centre);
  bodies.push(
    new RigidBody3D({
      object: anchor,
      physics: ctx.physics,
      shape: CollisionShape3D.box(
        Math.max(size.x, 0.05),
        Math.max(size.y, 0.05),
        Math.max(size.z, 0.05),
      ),
      type: "fixed",
    }),
  );
}

/**
 * Gives every structural mesh in `root` a static box collider.
 *
 * Returns the bodies so the scene can dispose them; the count is worth logging, because a
 * silent zero here is indistinguishable from working collision until the player walks
 * through a wall.
 */
export function buildStaticColliders(
  ctx: { physics: IPhysicsContext },
  root: Object3D,
): RigidBody3D[] {
  const bodies: RigidBody3D[] = [];
  root.updateMatrixWorld(true);

  root.traverse((object) => {
    if (SKIP.test(object.name)) return;

    if (object instanceof InstancedMesh) {
      const geometry = object.geometry;
      if (geometry.boundingBox === null) geometry.computeBoundingBox();
      const local = geometry.boundingBox;
      if (local === null) return;
      for (let index = 0; index < object.count; index += 1) {
        object.getMatrixAt(index, _matrix);
        // Instance matrices are relative to the InstancedMesh, so compose with its world
        // matrix — skipping this puts every collider at the origin, which reads as "the
        // whole building is one box in the middle of the floor".
        _world.multiplyMatrices(object.matrixWorld, _matrix);
        _box.copy(local).applyMatrix4(_world);
        _box.getSize(_size);
        _box.getCenter(_centre);
        addBox(ctx, bodies, _centre, _size);
      }
      return;
    }

    if (object instanceof Mesh) {
      _box.setFromObject(object, true);
      if (_box.isEmpty()) return;
      _box.getSize(_size);
      _box.getCenter(_centre);
      addBox(ctx, bodies, _centre, _size);
    }
  });

  console.info(`TN_STATIC_COLLIDERS:${JSON.stringify({ bodies: bodies.length })}`);
  return bodies;
}
