// Generated by hand for this game: ordinary Three.js + @threenative/physics.
//
// Static collision for the building, read off the cathedral's own scene graph rather than
// hand-listed, so it cannot drift out of step with geometry another file owns.
//
// **Trimesh, not bounding boxes.** The first version of this file used one axis-aligned box
// per mesh, which produced two bugs that are really the same bug — a box cannot represent a
// hole or a notch:
//
//   * The arcade and clerestory walls are extruded shapes *pierced by arch openings*. Their
//     bounding box is the solid rectangle, so every opening in the building was sealed. That
//     is where the invisible walls came from.
//   * The chancel stairs are three risers welded into a single mesh. Their bounding box is
//     one block 1.08 m tall rather than three steps of 0.36 m, so it was not a staircase at
//     all, it was a wall — and well over the character's 0.6 m autostep limit.
//
// A trimesh follows the real triangles, so openings stay open and each nosing stays a step.
// These are all static bodies, so the cost is a one-off BVH build rather than anything the
// solver pays per frame.
import type { IPhysicsContext } from "@threenative/physics";
import { CollisionShape3D, RigidBody3D } from "@threenative/physics";
import { Box3, InstancedMesh, Matrix4, Mesh, type Object3D } from "three";

/**
 * Nothing whose lowest point is above this can ever be touched.
 *
 * The player's capsule is 1.72 m and it can step up 0.6 m, so anything starting above about
 * four metres is unreachable — the vault, the clerestory, the triforium, the chandeliers and
 * every banner. Colliding them would spend a BVH on geometry no player can reach, and this
 * cull is what keeps a trimesh-per-mesh approach affordable at all.
 */
const REACHABLE_CEILING = 4.5;

/**
 * Objects whose names match are skipped.
 *
 * Glass sits inside window openings the player cannot reach; flames, chains and banners hang
 * in mid-air. Colliding with them would wall the player out of the aisles for no reason
 * anyone could see on screen.
 */
const SKIP = /glass|flame|candle|chain|banner|pane|rose|lancet|chandelier/i;

const _box = new Box3();
const _matrix = new Matrix4();

function collide(
  ctx: { physics: IPhysicsContext },
  bodies: RigidBody3D[],
  mesh: Mesh,
  carrier: Object3D,
): void {
  bodies.push(
    new RigidBody3D({
      object: carrier,
      physics: ctx.physics,
      // `fromMesh` reads the geometry in its own local space; the body's object supplies the
      // transform. That is why the instanced branch below builds a proxy carrier rather than
      // baking instance transforms into vertices.
      shape: CollisionShape3D.fromMesh(mesh, "trimesh"),
      type: "fixed",
    }),
  );
}

/** Whether any part of this object's world bounds is low enough for the player to reach. */
function reachable(object: Object3D): boolean {
  _box.setFromObject(object, true);
  return !_box.isEmpty() && _box.min.y < REACHABLE_CEILING;
}

/**
 * Gives every reachable structural mesh in `root` a static trimesh collider.
 *
 * Returns the bodies so the scene can dispose them. The count is logged because a silent
 * zero here is indistinguishable from working collision right up until a player walks
 * through a wall.
 */
export function buildStaticColliders(
  ctx: { physics: IPhysicsContext },
  root: Object3D,
): RigidBody3D[] {
  const bodies: RigidBody3D[] = [];
  const proxies: Object3D[] = [];
  root.updateMatrixWorld(true);

  root.traverse((object) => {
    if (SKIP.test(object.name)) return;

    if (object instanceof InstancedMesh) {
      if (!reachable(object)) return;
      for (let index = 0; index < object.count; index += 1) {
        object.getMatrixAt(index, _matrix);
        // A carrier that is never added to the scene: it exists only to hold this instance's
        // world transform for the body. Composing with `matrixWorld` matters — instance
        // matrices are relative to the InstancedMesh, and skipping it stacks every collider
        // at the origin.
        const carrier = new Mesh(object.geometry);
        carrier.applyMatrix4(_matrix.premultiply(object.matrixWorld));
        carrier.updateMatrixWorld(true);
        if (!reachable(carrier)) continue;
        proxies.push(carrier);
        collide(ctx, bodies, object, carrier);
      }
      return;
    }

    if (object instanceof Mesh && reachable(object)) {
      collide(ctx, bodies, object, object);
    }
  });

  console.info(
    `TN_STATIC_COLLIDERS:${JSON.stringify({ bodies: bodies.length, proxies: proxies.length })}`,
  );
  return bodies;
}
