// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// A first-person walker for the nave. WASD or the arrows move, the mouse looks.
//
// Deliberately not a physics character: the cathedral floor is one flat plane at y = 0 and
// the only things to collide with are piers, so a capsule controller would spend a Rapier
// body and a step-height problem to solve nothing. Movement is clamped to the building's
// interior instead, which is the whole collision model this scene needs.
import type { PerspectiveCamera } from "three";
import { Euler, Vector3 } from "three";

export interface IWalkerBounds {
  /** Half-width of the volume the walker may stand in, in metres either side of the axis. */
  readonly halfWidth: number;
  /** Half-depth, measured from the origin along Z. */
  readonly halfDepth: number;
}

export interface IFirstPerson {
  /** Call once per fixed step. `move` is the game's `input.vector("move")`. */
  update(move: { x: number; y: number }, dt: number, sprinting: boolean): void;
  /**
   * Jump the walker to a spot on the floor and aim the view.
   *
   * The camera's rotation is written from the walker's own orientation every fixed step,
   * so a vantage that moves the camera directly is snapped back within a frame; anything
   * that wants to place the view must come through here.
   */
  teleport(x: number, z: number, pitch: number, yaw: number): void;
  /** Detach the pointer listeners. */
  dispose(): void;
}

/** Eye height of a standing adult. The whole sense of scale in the building rests on it. */
const EYE_HEIGHT = 1.7;
const WALK_SPEED = 3.4;
const SPRINT_MULTIPLIER = 2.2;
/** Radians of yaw per pixel of mouse travel. */
const LOOK_SENSITIVITY = 0.0022;
/** Just short of straight up and straight down, so the view never flips through vertical. */
const MAX_PITCH = Math.PI / 2 - 0.02;
/** Seconds for the camera to reach most of its target velocity. Kills the on/off snap. */
const ACCELERATION = 0.09;

/**
 * Attaches mouse-look and keyboard movement to a camera.
 *
 * Pointer lock is requested on the first click rather than on load, because a browser
 * refuses the request outside a user gesture and a refused lock leaves the game with a
 * camera nothing can turn.
 */
export function createFirstPerson(
  camera: PerspectiveCamera,
  canvas: HTMLElement,
  bounds: IWalkerBounds,
): IFirstPerson {
  camera.position.y = EYE_HEIGHT;
  camera.rotation.order = "YXZ";

  const orientation = new Euler(camera.rotation.x, camera.rotation.y, 0, "YXZ");
  const velocity = new Vector3();
  const desired = new Vector3();
  const forward = new Vector3();
  const right = new Vector3();

  const onMouseMove = (event: MouseEvent): void => {
    if (document.pointerLockElement !== canvas) return;
    orientation.y -= event.movementX * LOOK_SENSITIVITY;
    orientation.x -= event.movementY * LOOK_SENSITIVITY;
    orientation.x = Math.max(-MAX_PITCH, Math.min(MAX_PITCH, orientation.x));
  };
  const onClick = (): void => {
    if (document.pointerLockElement !== canvas) void canvas.requestPointerLock();
  };

  canvas.addEventListener("click", onClick);
  document.addEventListener("mousemove", onMouseMove);

  return {
    update(move, dt, sprinting) {
      camera.rotation.set(orientation.x, orientation.y, 0, "YXZ");

      // Movement is horizontal regardless of where the camera is pointing. Without the
      // y-flatten, looking up at the vault and walking forward flies the player upward,
      // which is the single most common bug in a hand-rolled first-person controller.
      forward.set(0, 0, -1).applyEuler(orientation);
      forward.y = 0;
      if (forward.lengthSq() > 0) forward.normalize();
      right.set(1, 0, 0).applyEuler(orientation);
      right.y = 0;
      if (right.lengthSq() > 0) right.normalize();

      const speed = WALK_SPEED * (sprinting ? SPRINT_MULTIPLIER : 1);
      desired.set(0, 0, 0).addScaledVector(forward, move.y).addScaledVector(right, move.x);
      // Normalising after the sum, not before: adding two unit axes gives a diagonal of
      // length √2, and skipping this makes diagonal movement 41% faster than straight.
      if (desired.lengthSq() > 1) desired.normalize();
      desired.multiplyScalar(speed);

      // Frame-rate-independent approach to the target velocity, the same exponential form
      // the starter's spring arm uses. A plain lerp is correct at one step rate only.
      const blend = 1 - Math.exp(-dt / ACCELERATION);
      velocity.lerp(desired, blend);

      camera.position.addScaledVector(velocity, dt);
      camera.position.y = EYE_HEIGHT;
      camera.position.x = Math.max(-bounds.halfWidth, Math.min(bounds.halfWidth, camera.position.x));
      camera.position.z = Math.max(-bounds.halfDepth, Math.min(bounds.halfDepth, camera.position.z));
    },

    teleport(x, z, pitch, yaw) {
      camera.position.set(x, EYE_HEIGHT, z);
      orientation.set(pitch, yaw, 0, "YXZ");
      velocity.set(0, 0, 0);
    },

    dispose() {
      canvas.removeEventListener("click", onClick);
      document.removeEventListener("mousemove", onMouseMove);
    },
  };
}
