// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// A first-person walker for the nave. WASD or the arrows move, the mouse looks.
//
// Driven by a kinematic `CharacterBody3D` when one is supplied, so the player is stopped by
// piers and walls and steps up the chancel stairs instead of walking through them. The
// clamped free-camera path is kept as the fallback for a scene with no physics context.
import type { CharacterBody3D } from "@threenative/physics";
import type { PerspectiveCamera } from "three";
import { Euler, Vector3 } from "three";

export interface IWalkerBounds {
  /** Half-width of the volume the walker may stand in, in metres either side of the axis. */
  readonly halfWidth: number;
  /** Half-depth, measured from the origin along Z. */
  readonly halfDepth: number;
}

export interface IFirstPersonOptions {
  /**
   * The kinematic body that does the colliding.
   *
   * When present the walker stops being a clamped free camera and becomes a character: it
   * slides along piers, is stopped by walls and steps up the chancel stairs. `bounds` stays
   * as a backstop, because a character that escapes its collision through a seam should end
   * up inside the building rather than in the void.
   */
  readonly character?: CharacterBody3D;
}

export interface IFirstPerson {
  /** Call once per fixed step. `move` is the game's `input.vector("move")`. */
  update(move: { x: number; y: number }, dt: number, sprinting: boolean): void;
  /**
   * Jump the walker to a spot on the floor and aim the view.
   *
   * The camera's rotation is written from the walker's own orientation every fixed step,
   * so a vantage that moves the camera directly is snapped back within a frame; anything
   * that wants to place the view must come through here.
   */
  teleport(x: number, z: number, pitch: number, yaw: number): void;
  /** Detach the pointer listeners. */
  dispose(): void;
}

/** Eye height of a standing adult. The whole sense of scale in the building rests on it. */
const EYE_HEIGHT = 1.7;
const WALK_SPEED = 3.4;
const SPRINT_MULTIPLIER = 2.2;
/** Radians of yaw per pixel of mouse travel. */
const LOOK_SENSITIVITY = 0.0022;
/** Just short of straight up and straight down, so the view never flips through vertical. */
const MAX_PITCH = Math.PI / 2 - 0.02;
/** Seconds for the camera to reach most of its target velocity. Kills the on/off snap. */
const ACCELERATION = 0.09;
/**
 * The collision capsule. Total height is `2 * (halfHeight + radius)` = 1.72 m, and because
 * every shape here is centred on the body origin, that origin sits at the waist.
 */
export const BODY_HALF_HEIGHT = 0.58;
export const BODY_RADIUS = 0.28;
/** Waist to eye, so the camera rides at `EYE_HEIGHT` when the capsule is standing on the floor. */
const EYE_OVER_BODY = EYE_HEIGHT - (BODY_HALF_HEIGHT + BODY_RADIUS);

/**
 * Attaches mouse-look and keyboard movement to a camera.
 *
 * Pointer lock is requested on the first click rather than on load, because a browser
 * refuses the request outside a user gesture and a refused lock leaves the game with a
 * camera nothing can turn.
 */
export function createFirstPerson(
  camera: PerspectiveCamera,
  canvas: HTMLElement,
  bounds: IWalkerBounds,
  options: IFirstPersonOptions = {},
): IFirstPerson {
  const character = options.character;
  camera.position.y = EYE_HEIGHT;
  camera.rotation.order = "YXZ";

  const orientation = new Euler(camera.rotation.x, camera.rotation.y, 0, "YXZ");
  const velocity = new Vector3();
  const desired = new Vector3();
  const forward = new Vector3();
  const right = new Vector3();

  const onMouseMove = (event: MouseEvent): void => {
    if (document.pointerLockElement !== canvas) return;
    orientation.y -= event.movementX * LOOK_SENSITIVITY;
    orientation.x -= event.movementY * LOOK_SENSITIVITY;
    orientation.x = Math.max(-MAX_PITCH, Math.min(MAX_PITCH, orientation.x));
  };
  const onClick = (): void => {
    if (document.pointerLockElement !== canvas) void canvas.requestPointerLock();
  };

  canvas.addEventListener("click", onClick);
  document.addEventListener("mousemove", onMouseMove);

  return {
    update(move, dt, sprinting) {
      camera.rotation.set(orientation.x, orientation.y, 0, "YXZ");

      // Movement is horizontal regardless of where the camera is pointing. Without the
      // y-flatten, looking up at the vault and walking forward flies the player upward,
      // which is the single most common bug in a hand-rolled first-person controller.
      forward.set(0, 0, -1).applyEuler(orientation);
      forward.y = 0;
      if (forward.lengthSq() > 0) forward.normalize();
      right.set(1, 0, 0).applyEuler(orientation);
      right.y = 0;
      if (right.lengthSq() > 0) right.normalize();

      const speed = WALK_SPEED * (sprinting ? SPRINT_MULTIPLIER : 1);
      desired.set(0, 0, 0).addScaledVector(forward, move.y).addScaledVector(right, move.x);
      // Normalising after the sum, not before: adding two unit axes gives a diagonal of
      // length √2, and skipping this makes diagonal movement 41% faster than straight.
      if (desired.lengthSq() > 1) desired.normalize();
      desired.multiplyScalar(speed);

      // Frame-rate-independent approach to the target velocity, the same exponential form
      // the starter's spring arm uses. A plain lerp is correct at one step rate only.
      const blend = 1 - Math.exp(-dt / ACCELERATION);
      velocity.lerp(desired, blend);

      if (character !== undefined) {
        // Horizontal intent only. `moveAndSlide` owns the vertical axis — it applies gravity,
        // resolves the ground contact and runs the autostep that carries the player up the
        // chancel stairs. Writing `velocity.y` here would fight it every frame.
        character.velocity.x = velocity.x;
        character.velocity.z = velocity.z;
        character.moveAndSlide(dt);
        // The solver writes the transform after the bulk step, so this reads last frame's
        // result. That is the correct thing to render: it is where the character actually
        // was, rather than where it asked to go before anything stopped it.
        camera.position.copy(character.object.position);
        camera.position.y = character.object.position.y + EYE_OVER_BODY;
        return;
      }

      camera.position.addScaledVector(velocity, dt);
      camera.position.y = EYE_HEIGHT;
      camera.position.x = Math.max(-bounds.halfWidth, Math.min(bounds.halfWidth, camera.position.x));
      camera.position.z = Math.max(-bounds.halfDepth, Math.min(bounds.halfDepth, camera.position.z));
    },

    teleport(x, z, pitch, yaw) {
      camera.position.set(x, EYE_HEIGHT, z);
      orientation.set(pitch, yaw, 0, "YXZ");
      velocity.set(0, 0, 0);
      // The capsule is centred on the body origin, so its origin sits at the waist rather
      // than at the feet — place it that far above the floor or the character spawns half
      // sunk into it and the solver spends the first frames pushing it out.
      character?.teleport({ x, y: BODY_HALF_HEIGHT + BODY_RADIUS, z });
    },

    dispose() {
      canvas.removeEventListener("click", onClick);
      document.removeEventListener("mousemove", onMouseMove);
    },
  };
}
