// Generated by hand for this game. Ordinary Three.js — ThreeNative does not read this file.
//
// The keyboard on every desk. It was two stacked boxes, which from a standing camera read as a
// dark mat, and it was full-size — 0.44 m — under a mannequin whose bind-pose hand measures
// 0.238 m from wrist to index tip against a human 0.19 m. Two of those hands swallowed it.
//
// So this is a real key field at a pitch scaled to the hand that types on it: 24.8 mm instead of
// the human 19.05 mm, a factor of 1.30. Ninety-one chamfered caps in three tones, a recessed
// well and a rim, laid out row for row against a full-size board — function row, four staggered
// alpha rows, a spacebar row, and a right-hand cluster behind a one-unit gutter.
//
// The cost is paid once. Every geometry and material below is a module-level singleton built on
// first use, so sixteen desks share three buffers between them and a desk pays three Meshes and
// no vertices. Sculpted against `references/keyboard-top.jpg` (Fujitsu FM Towns FMT-KB202A,
// public domain — see CREDITS.md); the spec that gates this file is the ObjectSculptSpec for
// "office desktop keyboard", tier moderate.
import {
  type BufferGeometry,
  Matrix4,
  Mesh,
  MeshStandardMaterial,
  Vector3,
} from "three";
import { mergeGeometries } from "three/addons/utils/BufferGeometryUtils.js";
import { office } from "./palette.js";
import { roundedBox } from "./shapes.js";

/** Key pitch. A human keyboard is 19.05 mm; this is that times the mannequin's 1.30 hand ratio. */
const UNIT = 0.0248;
/** The dark channel between two caps. Widened from a real 3.5 mm because it is the whole read. */
const GAP = 0.0042;
/** Bezel between the outermost cap and the outside of the case, left and right. */
const BEZEL_X = 0.017;
/** Bezel front and back. */
const BEZEL_Z = 0.011;
/** Units across the key field: 15 for the alpha block, 1 of gutter, 4 for the right cluster. */
const FIELD_UNITS_X = 20;
/** Rows deep, counting the half-unit break under the function row. */
const FIELD_UNITS_Z = 6.5;

const WIDTH = FIELD_UNITS_X * UNIT + BEZEL_X * 2;
const DEPTH = FIELD_UNITS_Z * UNIT + BEZEL_Z * 2;
/** Height of the tray the caps stand on. The rim rises 5 mm above it. */
const PLATE_HEIGHT = 0.017;
const RIM_HEIGHT = 0.005;
const CAP_HEIGHT = 0.009;
/** The function row sits lower, the way it does on a real board. */
const FN_CAP_HEIGHT = 0.0065;

/** Overall footprint, so the desk builder can place it without re-deriving these. */
export const KEYBOARD_SIZE = { width: WIDTH, depth: DEPTH, height: PLATE_HEIGHT + CAP_HEIGHT };

/** The back edge rides higher than the front: four degrees of tilt toward the typist. */
export const KEYBOARD_TILT = 0.07;

/**
 * One cap: how many units wide, and whether it wears the dark modifier tone.
 *
 * Every row's widths sum to 15 units, exactly as a full-size board's do, which is what produces
 * the stagger — each row starts with a different-width modifier, so the columns below the number
 * row never line up.
 */
interface IKey {
  readonly units: number;
  readonly dark: boolean;
}

function pale(count: number): IKey[] {
  return Array.from({ length: count }, () => ({ units: 1, dark: false }));
}

function dark(units: number): IKey {
  return { units, dark: true };
}

/** A row of the alpha block, plus where its band starts in units back-to-front. */
interface IRow {
  readonly startZ: number;
  readonly keys: readonly IKey[];
  readonly capHeight: number;
  /** Units from the field's left edge. 0 for the alpha block, 16 for the right cluster. */
  readonly startX: number;
}

// Esc, then three groups of four function keys with a half unit between them. Modelled as one
// run because a quarter-unit of extra channel would not survive at 1.7 m; the two real gaps are
// spent where they read.
const FUNCTION_ROW: readonly IKey[] = [
  dark(1),
  dark(1.5),
  ...[1, 1, 1, 1].map(() => dark(1)),
  dark(0.5),
  ...[1, 1, 1, 1].map(() => dark(1)),
  dark(0.5),
  ...[1, 1, 1, 1].map(() => dark(1)),
];

const ALPHA_ROWS: readonly (readonly IKey[])[] = [
  [...pale(13), dark(2)], // number row, wide backspace
  [dark(1.5), ...pale(12), dark(1.5)], // tab and backslash
  [dark(1.75), ...pale(11), dark(2.25)], // caps and enter
  [dark(2.25), ...pale(10), dark(2.75)], // both shifts
];

const SPACE_ROW: readonly IKey[] = [
  dark(1.25),
  dark(1.25),
  dark(1.5),
  dark(6.25), // the spacebar: the largest single shape in the well and the fastest read
  dark(1.5),
  dark(1.25),
  dark(2),
];

// Eighteen keys in four columns behind a one-unit gutter. The hole above the left and right
// arrows is deliberate: an inverted-T with a gap over it is a shape only a keyboard has.
const CLUSTER_ROWS: readonly IRow[] = [
  { startX: 16, startZ: 0, keys: [dark(1), dark(1), dark(1), dark(1)], capHeight: FN_CAP_HEIGHT },
  { startX: 16, startZ: 1.5, keys: [dark(1), dark(1), dark(1), dark(1)], capHeight: CAP_HEIGHT },
  { startX: 16, startZ: 2.5, keys: [dark(1), dark(1), dark(1), dark(1)], capHeight: CAP_HEIGHT },
  { startX: 17, startZ: 3.5, keys: [dark(1)], capHeight: CAP_HEIGHT },
  { startX: 16, startZ: 4.5, keys: [dark(1), dark(1), dark(1)], capHeight: CAP_HEIGHT },
  { startX: 16, startZ: 5.5, keys: [dark(3), dark(1)], capHeight: CAP_HEIGHT },
];

const ROWS: readonly IRow[] = [
  { startX: 0, startZ: 0, keys: FUNCTION_ROW, capHeight: FN_CAP_HEIGHT },
  ...ALPHA_ROWS.map((keys, index) => ({
    startX: 0,
    startZ: 1.5 + index,
    keys,
    capHeight: CAP_HEIGHT,
  })),
  { startX: 0, startZ: 5.5, keys: SPACE_ROW, capHeight: CAP_HEIGHT },
  ...CLUSTER_ROWS,
];

const capCache = new Map<string, BufferGeometry>();

/**
 * A keycap: a chamfered box whose top is drawn in from its base, so the four sides catch
 * different light and two adjacent caps of the same colour still separate.
 *
 * A plain rounded box does not do this — under one overhead strip the tops all read at the same
 * value and the field flattens into a speckled plane, which is the failure mode this whole file
 * exists to avoid.
 */
function keycap(width: number, depth: number, height: number): BufferGeometry {
  const key = `${width},${depth},${height}`;
  const cached = capCache.get(key);
  if (cached !== undefined) return cached;

  const geometry = roundedBox(width, height, depth, 0.0025, 2).clone();
  const position = geometry.attributes.position;
  if (position === undefined) throw new Error("A keycap lost its position attribute.");
  const vertex = new Vector3();
  for (let index = 0; index < position.count; index += 1) {
    vertex.fromBufferAttribute(position, index);
    if (vertex.y > 0) {
      // 0 at the waist, 1 at the crown; 14% drawn in at the top is the standard cap taper.
      const rise = vertex.y / (height / 2);
      const draw = 1 - 0.14 * rise;
      position.setXYZ(index, vertex.x * draw, vertex.y, vertex.z * draw);
    }
  }
  geometry.computeVertexNormals();
  capCache.set(key, geometry);
  return geometry;
}

interface IParts {
  readonly shell: BufferGeometry;
  readonly paleCaps: BufferGeometry;
  readonly darkCaps: BufferGeometry;
}

let parts: IParts | undefined;

/** The case: a tray the caps stand in, with a rim round it so the well reads as recessed. */
function buildShell(): BufferGeometry {
  const pieces: BufferGeometry[] = [];
  const place = (geometry: BufferGeometry, x: number, y: number, z: number): void => {
    pieces.push(geometry.clone().applyMatrix4(new Matrix4().makeTranslation(x, y, z)));
  };

  place(roundedBox(WIDTH, PLATE_HEIGHT, DEPTH, 0.004, 3), 0, PLATE_HEIGHT / 2, 0);

  // Four rim bars, sunk a millimetre into the tray so no two faces are coplanar. The crown sits
  // 5 mm above the plate and 4 mm below the caps, which is the profile of a real case.
  const rimY = PLATE_HEIGHT - 0.001 + RIM_HEIGHT / 2;
  const sideBar = roundedBox(BEZEL_X, RIM_HEIGHT + 0.001, DEPTH, 0.002, 2);
  place(sideBar, -(WIDTH - BEZEL_X) / 2, rimY, 0);
  place(sideBar, (WIDTH - BEZEL_X) / 2, rimY, 0);
  const endBar = roundedBox(WIDTH - BEZEL_X * 2, RIM_HEIGHT + 0.001, BEZEL_Z, 0.002, 2);
  place(endBar, 0, rimY, -(DEPTH - BEZEL_Z) / 2);
  place(endBar, 0, rimY, (DEPTH - BEZEL_Z) / 2);

  const merged = mergeGeometries(pieces);
  if (merged === null) throw new Error("The keyboard shell would not merge.");
  return merged;
}

/** Walk the row table once and merge every cap into two buffers, one per tone. */
function buildParts(): IParts {
  const paleParts: BufferGeometry[] = [];
  const darkParts: BufferGeometry[] = [];
  const left = -WIDTH / 2 + BEZEL_X;
  const back = -DEPTH / 2 + BEZEL_Z;

  for (const row of ROWS) {
    let cursor = row.startX;
    for (const key of row.keys) {
      const width = key.units * UNIT - GAP;
      const depth = UNIT - GAP;
      const geometry = keycap(width, depth, row.capHeight)
        .clone()
        .applyMatrix4(
          new Matrix4().makeTranslation(
            left + (cursor + key.units / 2) * UNIT,
            PLATE_HEIGHT + row.capHeight / 2,
            back + (row.startZ + 0.5) * UNIT,
          ),
        );
      (key.dark ? darkParts : paleParts).push(geometry);
      cursor += key.units;
    }
  }

  const paleCaps = mergeGeometries(paleParts);
  const darkCaps = mergeGeometries(darkParts);
  if (paleCaps === null || darkCaps === null) throw new Error("The keycaps would not merge.");
  return { shell: buildShell(), paleCaps, darkCaps };
}

const shellMaterial = new MeshStandardMaterial({
  color: office.keyCase,
  roughness: 0.62,
  metalness: 0,
});
const paleCapMaterial = new MeshStandardMaterial({
  color: office.keyCapLight,
  roughness: 0.78,
  metalness: 0,
});
const darkCapMaterial = new MeshStandardMaterial({
  color: office.keyCapDark,
  roughness: 0.72,
  metalness: 0,
});

/**
 * A keyboard for one desk: the case, with its two cap fields parented to it.
 *
 * The returned Mesh is the handle `IDeskAnchor.keyboard` carries and `src/scenes/Office.ts`
 * repositions every frame under a seated worker's hands — the caps ride along because they are
 * its children, which is the same contract the two-box version had.
 *
 * Its origin is the centre of the footprint at desk-surface level, so a caller sets `position.y`
 * to the desk top and nothing else.
 */
export function keyboard(): Mesh {
  parts ??= buildParts();
  const board = new Mesh(parts.shell, shellMaterial);
  board.castShadow = true;
  board.receiveShadow = true;

  const light = new Mesh(parts.paleCaps, paleCapMaterial);
  light.castShadow = true;
  light.receiveShadow = true;
  board.add(light);

  const heavy = new Mesh(parts.darkCaps, darkCapMaterial);
  heavy.castShadow = true;
  heavy.receiveShadow = true;
  board.add(heavy);

  board.rotation.x = KEYBOARD_TILT;
  return board;
}
