// Generated by hand for this game. Ordinary Three.js — ThreeNative does not read this file.
//
// The whole look of ThreeNative HQ lives here: a warm corporate floor at dusk, after the
// reference frames. Cream carpet under a tan ceiling, a dark wood-slat feature wall, banded
// columns down the middle, cold glass on the long side, and suspended strip lights that are the
// only thing in the room allowed to be bright. Nothing here knows what a session is.
import {
  BoxGeometry,
  CylinderGeometry,
  Group,
  InstancedMesh,
  Matrix4,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  type Object3D,
  PlaneGeometry,
  Vector3,
} from "three";
import { office } from "./palette.js";

export interface IDeskAnchor {
  /** Where the worker's feet go when seated, in world space. */
  readonly seat: Vector3;
  /** Where the worker stands when it gets up — half a step back from the chair. */
  readonly stand: Vector3;
  /** Heading in radians the worker faces while at this desk. */
  readonly facing: number;
  /** The monitor for this desk, so a working session can light its own screen. */
  readonly screen: Mesh;
}

export interface IOffice {
  readonly root: Group;
  /** Every desk in the room, in a stable order — desk 0 is nearest the lift. */
  readonly desks: readonly IDeskAnchor[];
  /** The floor mesh, handed to the navmesh bake. */
  readonly floor: Mesh;
  /** Where a worker enters and leaves the floor. */
  readonly entrance: Vector3;
}

const ROOM_WIDTH = 32;
const ROOM_DEPTH = 17;
const CEILING = 3.2;
const DESK_HEIGHT = 0.74;

function standard(colour: number, roughness = 0.85): MeshStandardMaterial {
  return new MeshStandardMaterial({ color: colour, roughness, metalness: 0 });
}

/** Build the floor a game plays on. `deskCount` sets how many pods the room is furnished with. */
export function createOffice(deskCount: number): IOffice {
  if (!Number.isInteger(deskCount) || deskCount < 1)
    throw new Error(`An office needs at least one desk, got ${String(deskCount)}.`);
  const root = new Group();
  root.name = "office";

  const carpet = standard(office.carpet, 0.95);
  const floor = new Mesh(new PlaneGeometry(ROOM_WIDTH, ROOM_DEPTH), carpet);
  floor.rotation.x = -Math.PI / 2;
  floor.receiveShadow = true;
  root.add(floor);

  const ceiling = new Mesh(new PlaneGeometry(ROOM_WIDTH, ROOM_DEPTH), standard(office.ceiling, 1));
  ceiling.rotation.x = Math.PI / 2;
  ceiling.position.y = CEILING;
  root.add(ceiling);

  root.add(backWall(), slatWall(), glassWall(), columns(), stripLights(), lounge(), shelving());

  const desks: IDeskAnchor[] = [];
  for (let index = 0; index < deskCount; index += 1) {
    const anchor = placeDesk(index);
    root.add(anchor.group);
    desks.push(anchor.desk);
  }

  return { root, desks, floor, entrance: new Vector3(-ROOM_WIDTH / 2 + 1.5, 0, ROOM_DEPTH / 2 - 2) };
}

/** The tan end wall, plain, so the slats and the glass carry the room. */
function backWall(): Object3D {
  const wall = new Mesh(new PlaneGeometry(ROOM_WIDTH, CEILING), standard(office.wallTan));
  wall.position.set(0, CEILING / 2, -ROOM_DEPTH / 2);
  wall.receiveShadow = true;
  return wall;
}

/**
 * The dark vertical slats behind the desks.
 *
 * One `InstancedMesh` rather than 120 meshes: the slats are the single most repeated shape in the
 * room and the cheapest place to spend a draw call well.
 */
function slatWall(): Object3D {
  const group = new Group();
  const backing = new Mesh(new PlaneGeometry(ROOM_WIDTH, CEILING), standard(office.slatDark, 0.95));
  backing.position.set(0, CEILING / 2, -ROOM_DEPTH / 2 + 0.06);
  group.add(backing);

  const count = 118;
  const slats = new InstancedMesh(
    new BoxGeometry(0.07, CEILING - 0.1, 0.09),
    standard(office.slatLight, 0.6),
    count,
  );
  const matrix = new Matrix4();
  for (let index = 0; index < count; index += 1) {
    const x = -ROOM_WIDTH / 2 + 0.3 + (index * (ROOM_WIDTH - 0.6)) / (count - 1);
    matrix.makeTranslation(x, (CEILING - 0.1) / 2, -ROOM_DEPTH / 2 + 0.12);
    slats.setMatrixAt(index, matrix);
  }
  slats.instanceMatrix.needsUpdate = true;
  slats.castShadow = true;
  group.add(slats);
  return group;
}

/** Cold dusk beyond the glass, with mullions. The only cold surface in the room. */
function glassWall(): Object3D {
  const group = new Group();
  const glass = new Mesh(
    new PlaneGeometry(ROOM_WIDTH, CEILING - 0.6),
    // Basic, not standard: this is the world outside, not a surface being lit by the office.
    new MeshBasicMaterial({ color: office.glass }),
  );
  glass.position.set(0, CEILING / 2 + 0.1, ROOM_DEPTH / 2 - 0.02);
  glass.rotation.y = Math.PI;
  group.add(glass);

  const transom = new Mesh(new BoxGeometry(ROOM_WIDTH, 0.1, 0.14), standard(office.deskFrame, 0.5));
  transom.position.set(0, 1.9, ROOM_DEPTH / 2 - 0.08);
  group.add(transom);
  const horizon = new Mesh(
    new PlaneGeometry(ROOM_WIDTH, 0.9),
    new MeshBasicMaterial({ color: 0x7b93b5 }),
  );
  horizon.position.set(0, 1.45, ROOM_DEPTH / 2 - 0.03);
  horizon.rotation.y = Math.PI;
  group.add(horizon);

  const mullions = 14;
  const bars = new InstancedMesh(
    new BoxGeometry(0.08, CEILING, 0.12),
    standard(office.deskFrame, 0.5),
    mullions,
  );
  const matrix = new Matrix4();
  for (let index = 0; index < mullions; index += 1) {
    const x = -ROOM_WIDTH / 2 + (index * ROOM_WIDTH) / (mullions - 1);
    matrix.makeTranslation(x, CEILING / 2, ROOM_DEPTH / 2 - 0.08);
    bars.setMatrixAt(index, matrix);
  }
  bars.instanceMatrix.needsUpdate = true;
  group.add(bars);
  return group;
}

/** Banded columns: the reference's most recognisable shape, and cheap — stacked boxes. */
function columns(): Object3D {
  const group = new Group();
  const bandHeight = 0.22;
  const bands = Math.floor(CEILING / bandHeight);
  for (const x of [-10.2, -2.4, 5.4]) {
    for (let index = 0; index < bands; index += 1) {
      const wide = index % 2 === 0;
      const size = wide ? 0.82 : 0.72;
      const band = new Mesh(
        new BoxGeometry(size, bandHeight, size),
        standard(wide ? office.columnLight : office.columnDark, 0.8),
      );
      band.position.set(x, bandHeight / 2 + index * bandHeight, -2.9);
      band.castShadow = true;
      band.receiveShadow = true;
      group.add(band);
    }
  }
  return group;
}

/** Suspended linear fixtures. Emissive geometry, not lights — the scene owns the lighting rig. */
function stripLights(): Object3D {
  const group = new Group();
  const material = new MeshBasicMaterial({ color: office.strip });
  const housing = standard(office.deskFrame, 0.5);
  for (const z of [-5.4, -1.2, 3, 6.4]) {
    for (const x of [-10, -2, 6, 13]) {
      const strip = new Mesh(new BoxGeometry(5.6, 0.035, 0.1), material);
      strip.position.set(x, CEILING - 0.38, z);
      group.add(strip);
      const shell = new Mesh(new BoxGeometry(5.7, 0.07, 0.2), housing);
      shell.position.set(x, CEILING - 0.33, z);
      group.add(shell);
      for (const end of [-2.8, 2.8]) {
        const wire = new Mesh(
          new CylinderGeometry(0.008, 0.008, 0.32),
          standard(office.deskFrame, 0.4),
        );
        wire.position.set(x + end, CEILING - 0.19, z);
        group.add(wire);
      }
    }
  }
  return group;
}

/** The waiting area by the glass: two sofas and a low table, after the lobby reference. */
function lounge(): Object3D {
  const group = new Group();
  const frame = standard(office.sofa, 0.7);
  const cushion = standard(office.cushion, 0.9);
  for (const [x, z, turn] of [
    [-6.5, 4.6, 0],
    [-1.2, 4.6, 0],
    [-3.9, 6.9, Math.PI],
  ] as const) {
    const sofa = new Group();
    const base = new Mesh(new BoxGeometry(2.4, 0.42, 0.95), frame);
    base.position.y = 0.21;
    base.castShadow = true;
    base.receiveShadow = true;
    sofa.add(base);
    const back = new Mesh(new BoxGeometry(2.4, 0.5, 0.22), frame);
    back.position.set(0, 0.63, -0.37);
    back.castShadow = true;
    sofa.add(back);
    for (const seat of [-0.6, 0.6]) {
      const pad = new Mesh(new BoxGeometry(1.1, 0.16, 0.85), cushion);
      pad.position.set(seat, 0.5, 0.02);
      sofa.add(pad);
    }
    sofa.position.set(x, 0, z);
    sofa.rotation.y = turn;
    group.add(sofa);
  }
  const table = new Mesh(new BoxGeometry(1.5, 0.05, 0.8), standard(office.deskTop, 0.5));
  table.position.set(-3.9, 0.42, 5.7);
  table.castShadow = true;
  group.add(table);
  for (const [dx, dz] of [
    [-0.68, -0.34],
    [0.68, -0.34],
    [-0.68, 0.34],
    [0.68, 0.34],
  ] as const) {
    const leg = new Mesh(new BoxGeometry(0.03, 0.42, 0.03), standard(office.deskFrame, 0.4));
    leg.position.set(-3.9 + dx, 0.21, 5.7 + dz);
    group.add(leg);
  }
  return group;
}

/** The open shelving that divides the floor from the lounge in the first reference frame. */
function shelving(): Object3D {
  const group = new Group();
  const wood = standard(office.shelf, 0.6);
  const cellWidth = 0.9;
  const cellHeight = 0.62;
  const columnsOf = 4;
  const rowsOf = 2;
  const width = cellWidth * columnsOf;
  for (let index = 0; index <= columnsOf; index += 1) {
    const upright = new Mesh(new BoxGeometry(0.05, cellHeight * rowsOf, 0.36), wood);
    upright.position.set(-width / 2 + index * cellWidth, (cellHeight * rowsOf) / 2, 0);
    upright.castShadow = true;
    group.add(upright);
  }
  for (let index = 0; index <= rowsOf; index += 1) {
    const shelf = new Mesh(new BoxGeometry(width + 0.05, 0.05, 0.36), wood);
    shelf.position.set(0, index * cellHeight, 0);
    shelf.castShadow = true;
    group.add(shelf);
  }
  group.position.set(3.4, 0, 4.4);
  group.rotation.y = -Math.PI / 2;
  return group;
}

/** One desk, its divider, its monitor and its chair, plus where a worker sits at it. */
function placeDesk(index: number): { group: Group; desk: IDeskAnchor } {
  const group = new Group();
  const perRow = 8;
  const row = Math.floor(index / perRow);
  const column = index % perRow;
  // Rows face the slat wall; a second bank behind it faces the glass, so the room reads as an
  // open-plan floor rather than a classroom.
  const facingWall = row % 2 === 0;
  const x = -13.6 + column * 3.9;
  const z = -5.4 + row * 4.2;
  group.position.set(x, 0, z);
  group.rotation.y = facingWall ? 0 : Math.PI;

  const top = new Mesh(new BoxGeometry(1.6, 0.05, 0.78), standard(office.deskTop, 0.55));
  top.position.y = DESK_HEIGHT;
  top.castShadow = true;
  top.receiveShadow = true;
  group.add(top);

  for (const side of [-0.72, 0.72]) {
    const leg = new Mesh(new BoxGeometry(0.06, DESK_HEIGHT, 0.68), standard(office.deskFrame, 0.5));
    leg.position.set(side, DESK_HEIGHT / 2, 0);
    group.add(leg);
  }

  const divider = new Mesh(new BoxGeometry(1.6, 0.42, 0.05), standard(office.divider, 0.95));
  divider.position.set(0, DESK_HEIGHT + 0.21, -0.4);
  divider.castShadow = true;
  group.add(divider);

  const screen = new Mesh(
    new BoxGeometry(0.62, 0.36, 0.03),
    new MeshStandardMaterial({ color: office.screenOff, roughness: 0.3, metalness: 0.1 }),
  );
  screen.position.set(0, DESK_HEIGHT + 0.28, -0.24);
  group.add(screen);
  const stand = new Mesh(new BoxGeometry(0.16, 0.12, 0.14), standard(office.deskFrame, 0.4));
  stand.position.set(0, DESK_HEIGHT + 0.06, -0.24);
  group.add(stand);

  group.add(chair());

  const seatLocal = new Vector3(0, 0, 0.52);
  const standLocal = new Vector3(0, 0, 1.15);
  const seat = seatLocal.clone().applyEuler(group.rotation).add(group.position);
  const stand2 = standLocal.clone().applyEuler(group.rotation).add(group.position);
  return {
    group,
    desk: { seat, stand: stand2, facing: group.rotation.y + Math.PI, screen },
  };
}

/** A plain task chair: seat, back, post, base. */
function chair(): Object3D {
  const group = new Group();
  const dark = standard(office.seat, 0.6);
  const seat = new Mesh(new BoxGeometry(0.5, 0.08, 0.5), dark);
  seat.position.set(0, 0.45, 0.52);
  seat.castShadow = true;
  group.add(seat);
  const back = new Mesh(new BoxGeometry(0.48, 0.6, 0.07), dark);
  back.position.set(0, 0.78, 0.76);
  back.castShadow = true;
  group.add(back);
  const post = new Mesh(new CylinderGeometry(0.04, 0.04, 0.4), dark);
  post.position.set(0, 0.22, 0.52);
  group.add(post);
  const base = new Mesh(new CylinderGeometry(0.3, 0.3, 0.04, 12), dark);
  base.position.set(0, 0.03, 0.52);
  group.add(base);
  return group;
}
