import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { RippleField } from '@threenative/core';
const source=await build({stdin:{contents:`export {Whitewater} from './src/render/whitewater.ts'; export {shipMotion} from './src/render/ship-motion.ts'; export {Battle} from './src/sim/battle.ts';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const {Whitewater,shipMotion,Battle}=await import(`data:text/javascript;base64,${Buffer.from(source.outputFiles[0].text).toString('base64')}`);
const wave=new RippleField({resolution:64,size:160,step:1/120});
const height=(x,z,t)=>Math.sin(t)*.3+wave.heightAt(x,z);
const water=new Whitewater({wave,heightAt:height,capacity:64});
water.emit(0,4,0,0,-8,0,.25,0,9,.5,0);
for(let i=1;i<=240;i++){wave.advance(1/120);water.step(1/120,i/120);}
assert.equal(water.stats.waterHits,1,'one swept crossing returns momentum exactly once');
assert.ok(water.stats.returnImpulse>0&&wave.energy()>0,'droplet drives actual wave energy');
assert.equal(water.counts().foam,1,'water parcel becomes floating foam');
assert.ok(Math.abs(water.start[1]-height(water.start[0],water.start[2],2)-.055)<1e-5,'foam rides the same deformed surface');
water.reset();wave.reset();
water.emit(0,-.1,0,0,1,0,.2,2,8,.5,.1);
for(let i=1;i<=120;i++)water.step(1/120,i/120);
assert.equal(water.stats.bubblePops,1,'rising bubble pops');
assert.equal(water.counts().foam,1,'bubble becomes persistent foam');
water.reset();
for(let i=0;i<64;i++)assert.ok(water.emit(i,10,0,0,0,0,.1,0,8)>=0);
assert.equal(water.emit(0,10,0,0,0,0,.1,0,8),-1,'full pool rejects without erasing live parcels');
assert.equal(water.activeCount(),64);
const b=new Battle(),s=b.ships.find(s=>s.kind==='carrier'&&s.team==='jp');
const right={x:Math.cos(s.heading),z:Math.sin(s.heading)};
b.damageShip(s,120,{x:s.x+right.x*s.hullBeam*.5,y:-3,z:s.z+right.z*s.hullBeam*.5},'torpedo','us',{owner:'player'});
const event=b.effects.find(e=>e.waterKind==='torpedo');
assert.ok(event&&event.underwater&&event.waterDepth===3,'actual torpedo damage emits typed submerged water blast');
const flat=()=>0,p=shipMotion(s,b.time+.8,flat);
assert.ok(Math.abs(p.roll)>.01&&Math.hypot(p.x,p.z)>.2,'real hit record rocks and displaces the visible hull');
const opposite={...s,impacts:s.impacts.map(h=>({...h,right:-h.right}))},o=shipMotion(opposite,b.time+.8,flat);
assert.ok(Math.abs(p.roll+o.roll)<1e-9,'opposite hull side reverses roll');
assert.ok(Math.abs(shipMotion(s,b.time+20,flat).roll)<.001,'hit rocking decays');
const destroyer={...s,hullLength:s.hullLength*.5};
assert.ok(Math.abs(shipMotion(destroyer,b.time+.8,flat).roll)>Math.abs(p.roll),'smaller hull responds more');
assert.deepEqual(shipMotion({...s,impacts:[]},b.time,flat),{x:0,y:0,z:0,pitch:0,roll:0});
console.log('PASS: swept splashback, persistent surface foam, rising bubbles, bounded pool, actual torpedo event, opposite-side hull motion and decay.');
