// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// A gothic nave, built to `sculpt/cathedral.spec.json` and gated against
// `reference-cathedral.png`. Every proportion below derives from one bay, so the building
// cannot drift out of scale when a number is edited.
//
// The single silhouette cue that separates gothic from romanesque is the **two-centre
// pointed arch**, and it appears at four scales — arcade, triforium, clerestory, chancel.
// A wall with rectangular holes in it reads as a car park at any lighting quality, so the
// openings are real extruded shapes with real arch heads rather than boxes with gaps.
//
// Two structural decisions drive everything below:
//
//   *Merge, then instance.* A bay is one welded `BufferGeometry` — arch orders, string
//   courses, triforium arcade, clerestory splay and mullions together — drawn once as an
//   `InstancedMesh` across all eighteen wall positions. Piers, vault webs, ribs and bosses
//   are the same trick. The whole shell is roughly thirty draw calls; built as loose meshes
//   the same geometry was over three hundred, and the post chain has no budget for that.
//
//   *Tone lives in vertex colours, not in materials.* Merging kills per-part materials, so
//   every part is tinted into a `color` attribute and drawn by one `vertexColors` material.
//   That is what lets a capital read as a bright band across a dark pier without costing a
//   second draw call for every capital in the building.
//
// What each part is here to do for the lighting chain:
//   godrays   the clerestory mullions cut one window into three separate shafts
//   ssgi      the aisles behind the colonnade receive no direct light whatsoever
//   gtao      pier bases, capital undersides, the arch orders, and the vault severies
//   ssr       the floor is the only low-roughness surface in the building
//   bloom     the glass is authored past the tonemap ceiling on purpose
import {
  BoxGeometry,
  BufferGeometry,
  CatmullRomCurve3,
  Color,
  CylinderGeometry,
  DoubleSide,
  ExtrudeGeometry,
  Float32BufferAttribute,
  Group,
  InstancedMesh,
  LatheGeometry,
  Matrix4,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  Path,
  PlaneGeometry,
  RepeatWrapping,
  RingGeometry,
  Shape,
  SphereGeometry,
  SRGBColorSpace,
  type Texture,
  TorusGeometry,
  TubeGeometry,
  Vector2,
  Vector3,
} from "three";
import { mergeGeometries } from "three/addons/utils/BufferGeometryUtils.js";
import { NAVE } from "./lighting.js";
import { palette } from "./palette.js";

/** Tones the carved stone is tinted with. One material, four values, no extra draw calls. */
const TONE = {
  /** The bulk of the building. */
  stone: palette.stone,
  /** Capitals, string courses, ribs, tracery — anything meant to catch a rim of light. */
  bright: 0x968b7b,
  /**
   * The upper storeys. Above the arcade the nave wall is backlit from every camera on the
   * axis, so nothing up there is separated by *light*; the storeys have to be separated by
   * their own albedo or twenty metres of wall reads as one undifferentiated slab.
   */
  upper: 0xa79b88,
  /** Bases, plinths, wall backing. Reads as the shadow the arcade sits in. */
  base: 0x4a463d,
  /** Triforium backing and aisle roof: the darkness the openings are read against. */
  void: palette.stoneDark,
} as const;

const materials = {
  /**
   * Everything carved. `vertexColors` multiplies the merged tints above, so one material
   * covers plinth to boss; the white base colour is deliberate, since anything else would
   * tint the stone twice.
   */
  carved: new MeshStandardMaterial({
    color: 0xffffff,
    metalness: 0,
    roughness: 0.92,
    vertexColors: true,
  }),
  /**
   * The aisle walls: seen from one side only, so `DoubleSide` costs nothing.
   *
   * A shade above `stoneDark`, because the arcade openings are seen at sixty degrees off
   * their own plane from anywhere on the axis — at the darker value the aisle behind them
   * was pure black and the colonnade read as a wall with decorations on it.
   */
  shadowStone: new MeshStandardMaterial({
    color: 0x494437,
    metalness: 0,
    roughness: 0.95,
    side: DoubleSide,
  }),
  /**
   * The apse. Pale, where the aisles are dark: the east end is what the whole nave points
   * at, and an apse cut from the same value as the aisle walls closes the axis on nothing.
   */
  apseStone: new MeshStandardMaterial({
    color: palette.stone,
    metalness: 0,
    roughness: 0.9,
    side: DoubleSide,
  }),
  /** The one low-roughness surface. Without it screen-space reflections have nothing to return. */
  marble: new MeshStandardMaterial({ color: palette.floor, roughness: 0.16, metalness: 0.1 }),
  marbleBand: new MeshStandardMaterial({ color: palette.floorBand, roughness: 0.2, metalness: 0.1 }),
  /** Near-black. The chancel screen reads as silhouette and nothing else. */
  iron: new MeshStandardMaterial({ color: 0x14120f, roughness: 0.55, metalness: 0.7 }),
};

function glass(colour: number): MeshBasicMaterial {
  // `toneMapped: false` with a colour at full value keeps the pane above the bloom
  // threshold. A window the tonemap can hold reads as a grey hole in a wall.
  return new MeshBasicMaterial({ color: colour, toneMapped: false, side: DoubleSide });
}

// ---- geometry plumbing ---------------------------------------------------------------

const SQRT3 = Math.sqrt(3);
const scratch = new Matrix4();

/**
 * Springing height of the arcade, and therefore the top of every pier capital in the nave.
 *
 * One constant for both, because an arch that springs from anywhere other than the abacus
 * it stands on is the single loudest wrongness available in a building like this — the
 * previous pass had the capital floating two metres above the arch it was carrying.
 */
const ARCADE_SPRING = 8;

/**
 * The clerestory window: the only opening in the building the sun actually comes through,
 * and therefore the only geometry that decides whether the nave has shafts of light in it.
 *
 * A godray is raymarched against the sun's shadow map, so a beam exists only where the air
 * *beside* it is in shadow. The previous window was a single 4.2 m opening on a 7 m bay —
 * 60% of the upper wall was hole, most of the upper nave volume was lit, every view ray
 * accumulated something, and the pass returned even haze instead of separate beams. Pushing
 * godray density up made the haze brighter, not the beams sharper, which is the signature of
 * an aperture problem rather than a post problem.
 *
 * So: two narrow lights per bay with 1.56 m of solid stone between them, 41% open against
 * 59% solid at the aperture plane, plus a transom that cuts each shaft in half again. Four
 * separated beams per bay rather than one lit volume.
 */
const CLERESTORY = {
  /** Half-width of each light at the *outer* face — the hole the shadow map sees. */
  aperture: 0.72,
  /** Sill height. Clear of the triforium string course, and low enough for a 4:1 light. */
  base: 20.2,
  /** Centre of each light across the bay. Two, far enough apart to leave a real mullion. */
  lights: [-1.5, 1.5],
  /** Order depths from the nave face outward. 2.1 m of reveal in three steps. */
  reveal: [0.9, 0.6, 0.6],
  /**
   * How much wider each order gets toward the nave.
   *
   * Each light is splayed on its own rather than grouped under one containing arch. A
   * containing arch pinches fast near its own apex — at this band height it forced the
   * lights down to a 2:1 stump — and per-light splay also gives every aperture its own
   * taper, which is what makes a shaft start narrow at the glass and widen into the nave.
   */
  splay: 0.16,
  springY: 4.5,
  /** Height of the transom above the sill. */
  transomY: 2.5,
} as const;

/** Height of one clerestory light, sill to apex, at the aperture plane. */
const CLERESTORY_LIGHT_HEIGHT = CLERESTORY.springY + CLERESTORY.aperture * Math.sqrt(3);
/** Total reveal depth, nave face to glass. */
const CLERESTORY_DEPTH = CLERESTORY.reveal.reduce((total, step) => total + step, 0);

/**
 * Tint every vertex, and drop the index while doing it.
 *
 * `mergeGeometries` refuses a mix of indexed and non-indexed inputs, and `ExtrudeGeometry`
 * is the only non-indexed primitive in this file — so rather than remember which is which,
 * everything is flattened on the way in. The cost is vertex count in a scene that is draw
 * -call bound, not vertex bound.
 */
function part(geometry: BufferGeometry, tone: number): BufferGeometry {
  const flat = geometry.index === null ? geometry : geometry.toNonIndexed();
  if (flat !== geometry) geometry.dispose();
  const colour = new Color(tone);
  const count = flat.getAttribute("position").count;
  const data = new Float32Array(count * 3);
  for (let vertex = 0; vertex < count; vertex += 1) {
    data[vertex * 3] = colour.r;
    data[vertex * 3 + 1] = colour.g;
    data[vertex * 3 + 2] = colour.b;
  }
  flat.setAttribute("color", new Float32BufferAttribute(data, 3));
  return flat;
}

/** `mergeGeometries` returns `null` on mismatched attributes; this file cannot recover from that. */
function weld(parts: BufferGeometry[], label: string): BufferGeometry {
  const merged = mergeGeometries(parts, false);
  if (merged === null) throw new Error(`cathedral: attribute mismatch welding ${label}`);
  for (const piece of parts) piece.dispose();
  return merged;
}

/**
 * Height of a two-centre pointed arch at horizontal position `t`, normalised so that
 * `p(0) = 1` at the apex and `p(±1) = 0` at the springing.
 *
 * Both arcs have radius `2a` centred on the *opposite* springing point, which puts the
 * apex at `a·√3`. Dividing by √3 is what makes this reusable at any rise: the vault, the
 * ribs and the arch profiles all share one curve, so they cannot drift apart.
 */
function pointedRise(t: number): number {
  const along = Math.min(1, Math.abs(t));
  return Math.sqrt(Math.max(0, 4 - (1 + along) ** 2)) / SQRT3;
}

/** A two-centre pointed opening of half-width `a`, centred on `cx`, springing at `springY`. */
function pointedArchHole(a: number, springY: number, cx = 0): Path {
  const hole = new Path();
  hole.moveTo(cx - a, 0);
  hole.lineTo(cx - a, springY);
  hole.absarc(cx + a, springY, 2 * a, Math.PI, (Math.PI * 2) / 3, true);
  hole.absarc(cx - a, springY, 2 * a, Math.PI / 3, 0, true);
  hole.lineTo(cx + a, 0);
  hole.closePath();
  return hole;
}

interface IOpening {
  readonly halfWidth: number;
  readonly springY: number;
  readonly centre?: number;
}

/**
 * A wall panel pierced by one or more pointed openings.
 *
 * The panel is built in its own local frame with `z` running from the nave face *away*
 * from the nave, which is what lets receding arch orders be stacked by depth: order zero
 * sits at the face with the widest opening, and each order behind it is narrower, so the
 * arch head reads as three concentric mouldings instead of one cut in a card.
 */
function piercedPanel(
  width: number,
  height: number,
  thickness: number,
  openings: readonly IOpening[],
): BufferGeometry {
  const panel = new Shape();
  panel.moveTo(-width / 2, 0);
  panel.lineTo(width / 2, 0);
  panel.lineTo(width / 2, height);
  panel.lineTo(-width / 2, height);
  panel.closePath();
  for (const opening of openings) {
    panel.holes.push(pointedArchHole(opening.halfWidth, opening.springY, opening.centre ?? 0));
  }
  return new ExtrudeGeometry(panel, { bevelEnabled: false, depth: thickness });
}

/**
 * One bay of the outer aisle wall: a pointed window opening with a respond either side.
 *
 * Same local frame as `bayWall` — `z` runs away from the nave — so both colonnades and both
 * aisle walls come from one geometry placed by `rotation.y = side · π/2`.
 *
 * This is the second plane of depth in the picture. A flat wall behind the colonnade gives
 * the arcade openings nothing to be openings *onto*, and the whole aisle then reads as a
 * painted backdrop however dark it is.
 */
function aisleBay(bayPitch: number, wallHeight: number): BufferGeometry {
  const parts: BufferGeometry[] = [
    part(
      piercedPanel(bayPitch, wallHeight, 0.5, [
        { halfWidth: bayPitch * 0.32, springY: wallHeight * 0.38 },
      ]),
      // A mid value, not `void`. Against a black aisle the arcade openings had nothing to be
      // darker or lighter *than*, and the whole colonnade flattened into one slab.
      0x484133,
    ),
  ];
  for (const edge of [-1, 1]) {
    // A respond on each bay joint, standing proud toward the nave. Half of every pair is
    // coincident with its neighbour's, which costs nothing and keeps one geometry per bay.
    parts.push(
      part(
        new CylinderGeometry(0.38, 0.38, wallHeight, 8).translate(
          (edge * bayPitch) / 2,
          wallHeight / 2,
          -0.34,
        ),
        TONE.base,
      ),
    );
    parts.push(
      part(
        new BoxGeometry(1.1, 0.3, 1.1).translate(
          (edge * bayPitch) / 2,
          wallHeight * 0.38,
          -0.34,
        ),
        TONE.base,
      ),
    );
  }
  return weld(parts, "aisle bay");
}

/** A rib, as a tube swept along the curve the vault surface actually creases on. */
function ribTube(points: readonly Vector3[], radius: number): BufferGeometry {
  return new TubeGeometry(new CatmullRomCurve3([...points]), points.length * 2, radius, 6, false);
}

// ---- the compound pier ----------------------------------------------------------------

/**
 * One compound pier, welded into a single geometry with the nave lying toward local +X.
 *
 * A stack of a cylinder and two boxes reads as scaffolding. What makes a pier read as
 * stone is that its section is *lobed*: eight engaged shafts around an octagonal core give
 * eight bright lines and eight dark ones when a shaft of light crosses it, and that
 * vertical rhythm survives at any distance, which a single broad highlight does not.
 *
 * The three tall shafts on the nave face are the other half of it. They run unbroken from
 * the floor past the arcade capital to the vault springing, and they are the reason the
 * eye reads floor and vault as one structure rather than as a room with a lid.
 */
function compoundPier(radius: number, capitalY: number, vaultShaftTop: number): BufferGeometry {
  const parts: BufferGeometry[] = [];
  const socleTop = 1.5;
  const bellHeight = 1.25;
  const coreTop = capitalY - bellHeight;

  // Stepped plinth. Three receding steps, not one box: the step edges are where ambient
  // occlusion reads strongest, and they are what gives the pier a foot rather than a cut.
  parts.push(part(new BoxGeometry(radius * 2.9, 0.5, radius * 2.9).translate(0, 0.25, 0), TONE.base));
  parts.push(part(new BoxGeometry(radius * 2.5, 0.45, radius * 2.5).translate(0, 0.72, 0), TONE.base));
  // The socle flares outward going *down*, so the octagon meets the square below it on a
  // slope. A straight drum here leaves a hard ring that reads as a join, not a moulding.
  parts.push(
    part(new CylinderGeometry(radius * 1.34, radius * 1.5, 0.55, 8).translate(0, 1.22, 0), TONE.base),
  );

  parts.push(
    part(
      new CylinderGeometry(radius, radius, coreTop - socleTop, 8).translate(
        0,
        (coreTop + socleTop) / 2,
        0,
      ),
      TONE.stone,
    ),
  );

  const shafts = 12;
  const shaftRadius = radius * 0.26;
  const shaftOrbit = radius + shaftRadius * 0.8;
  for (let index = 0; index < shafts; index += 1) {
    // Twelve thin ones, all the way round, rather than five fat ones over the front 240°.
    // Fewer and fatter reads as a bundle of pipes; the count is what makes a compound pier
    // look carved out of one block, and the back half matters because it is seen from the aisle.
    const angle = (index / shafts) * Math.PI * 2;
    const shaftX = Math.cos(angle) * shaftOrbit;
    const shaftZ = Math.sin(angle) * shaftOrbit;
    parts.push(
      part(
        new CylinderGeometry(shaftRadius, shaftRadius, coreTop - 1.35, 10).translate(
          shaftX,
          (coreTop + 1.35) / 2,
          shaftZ,
        ),
        TONE.stone,
      ),
    );
    // Necking ring under the capital and a torus base above the socle: two thin bright
    // horizontals that stop each shaft reading as an extruded pipe.
    parts.push(
      part(
        new TorusGeometry(shaftRadius * 1.16, shaftRadius * 0.34, 6, 10)
          .rotateX(Math.PI / 2)
          .translate(shaftX, coreTop - 0.24, shaftZ),
        TONE.bright,
      ),
    );
    parts.push(
      part(
        new TorusGeometry(shaftRadius * 1.3, shaftRadius * 0.4, 6, 10)
          .rotateX(Math.PI / 2)
          .translate(shaftX, socleTop + 0.1, shaftZ),
        TONE.base,
      ),
    );
  }

  // The capital, as a lathed profile rather than a cube. The silhouette that matters is the
  // *flare*: a bell that widens as it rises, capped by a flat abacus. That outline is what
  // the eye reads as a foliage band from twenty metres, long before any leaf is resolvable.
  // Kept deliberately tight. The first pass flared to 1.5x the core radius and read as a
  // mushroom cap from the nave floor; a real capital projects barely past the shafts it
  // gathers, and the *band* is the read, not the overhang.
  const bell = [
    new Vector2(radius * 1.16, 0),
    new Vector2(radius * 1.26, 0.09),
    new Vector2(radius * 1.14, 0.2),
    new Vector2(radius * 1.18, 0.3),
    new Vector2(radius * 1.26, 0.6),
    new Vector2(radius * 1.32, 0.86),
    new Vector2(radius * 1.36, 0.96),
    new Vector2(0, 0.96),
  ];
  parts.push(part(new LatheGeometry(bell, 16).translate(0, coreTop, 0), TONE.bright));
  // A *square* abacus over the round bell. This is the detail that stops a lathed capital
  // reading as a lampshade: the corners of the slab break the circle from every angle, and
  // gothic capitals are square-abacus almost without exception for exactly that reason.
  parts.push(
    part(
      new BoxGeometry(radius * 2.86, 0.24, radius * 2.86).translate(0, coreTop + 1.08, 0),
      TONE.bright,
    ),
  );
  parts.push(
    part(
      new BoxGeometry(radius * 2.6, 0.16, radius * 2.6).translate(0, coreTop + 0.92, 0),
      TONE.bright,
    ),
  );

  // Crockets around the bell. Eight squashed blobs is not carving, but it breaks the
  // lathe's perfect circle, and a broken outline is the whole read of a foliage capital.
  for (let leaf = 0; leaf < 12; leaf += 1) {
    const angle = (leaf / 12) * Math.PI * 2 + Math.PI / 12;
    parts.push(
      part(
        new SphereGeometry(radius * 0.13, 6, 4)
          .scale(1.5, 0.7, 1.5)
          .translate(
            Math.cos(angle) * radius * 1.14,
            coreTop + 0.62,
            Math.sin(angle) * radius * 1.14,
          ),
        TONE.bright,
      ),
    );
  }

  // The vault shafts: a triple cluster standing proud of the pier on the nave side, running
  // floor to vault. They pass *outside* the abacus rather than through it, which is why the
  // abacus radius above and this offset are locked to each other.
  const shaftFace = radius * 1.43 + 0.5;
  // Five shafts at eye level, shedding members at each string course until one reaches the
  // vault. That taper is not decoration — it is the only reason the clerestory is visible.
  //
  // Carried full height, the five spanned 4 m of z, 27 m tall, on a 7 m bay pitch, standing
  // about two thirds of the way from a nave camera to the far clerestory. Projected onto the
  // window plane that is a 5.9 m screen across a 7 m bay: a raycast of all 49 clerestory
  // sample points inside the play camera's frustum found 36 of them stopped by *these
  // cylinders*, and the upper elevation rendered as an unbroken black field. Dropping the
  // outer pair at the arcade and the middle pair at the triforium leaves a 1 m screen above
  // 19 m, and it is also what a real pier does — a vault shaft sheds members as it rises.
  for (const [offsetZ, tallRadius, tone, top] of [
    [0, 0.5, TONE.upper, vaultShaftTop],
    [-1.0, 0.34, TONE.bright, NAVE.triforiumTop],
    [1.0, 0.34, TONE.bright, NAVE.triforiumTop],
    [-1.75, 0.24, TONE.upper, NAVE.arcadeHeight],
    [1.75, 0.24, TONE.upper, NAVE.arcadeHeight],
  ] as const) {
    const inset = tallRadius < 0.3 ? 0.28 : 0;
    parts.push(
      part(
        new CylinderGeometry(tallRadius, tallRadius, top, 10).translate(
          shaftFace - inset,
          top / 2,
          offsetZ,
        ),
        tone,
      ),
    );
    // A stop where a shaft dies into the wall. Without one it ends in mid-air, which is the
    // one way this taper can read as a modelling mistake rather than as architecture.
    if (top === vaultShaftTop) continue;
    parts.push(
      part(
        new BoxGeometry(tallRadius * 3.4, 0.34, tallRadius * 3.4).translate(
          shaftFace - inset,
          top - 0.17,
          offsetZ,
        ),
        TONE.bright,
      ),
    );
  }
  // A corbel at the top of the cluster, so the ribs land on something instead of on air.
  for (const [corbelWidth, corbelDepth, corbelY] of [
    [1.3, 1.5, vaultShaftTop - 0.72],
    [1.7, 1.9, vaultShaftTop - 0.24],
  ] as const) {
    parts.push(
      part(
        new BoxGeometry(corbelWidth, 0.48, corbelDepth).translate(
          shaftFace - 0.14,
          corbelY,
          0,
        ),
        TONE.bright,
      ),
    );
  }

  return weld(parts, "pier");
}

// ---- one bay of arcade wall ------------------------------------------------------------

/**
 * A full-height slice of one arcade wall: arcade with three orders, string course,
 * triforium arcade, string course, splayed clerestory.
 *
 * Local frame: `x` along the bay and centred on it, `y` from the floor, and `z` running
 * from the nave face (0) *into* the wall. That last convention is the whole point — it is
 * what lets the arch orders be ordered by depth, and it makes the two colonnades mirror
 * each other with a single `rotation.y = side · π/2`.
 */
function bayWall(): BufferGeometry {
  const { arcadeHeight, bayPitch, clerestoryTop, triforiumTop } = NAVE;
  const parts: BufferGeometry[] = [];

  // -- arcade, in three receding orders --------------------------------------------------
  // Each order behind the last is narrower and lower, because a two-centre head of
  // half-width `a` apexes at `a·√3`; that is what produces concentric mouldings for free.
  // Four bands, the first of them standing *proud* of the wall. A hood mould is the only
  // one of these that casts onto the wall behind it rather than into the opening, and that
  // cast line is what gives the arcade its contact shadow at grazing sun.
  const orders = [
    { depth: 0.34, halfWidth: bayPitch * 0.4, tone: TONE.bright, z: -0.34 },
    { depth: 0.46, halfWidth: bayPitch * 0.38, tone: TONE.stone, z: 0 },
    { depth: 0.34, halfWidth: bayPitch * 0.345, tone: TONE.bright, z: 0.46 },
    { depth: 0.42, halfWidth: bayPitch * 0.315, tone: TONE.stone, z: 0.8 },
  ] as const;
  for (const order of orders) {
    parts.push(
      part(
        piercedPanel(bayPitch, arcadeHeight, order.depth, [
          { halfWidth: order.halfWidth, springY: ARCADE_SPRING },
        ]).translate(0, 0, order.z),
        order.tone,
      ),
    );
  }

  // -- string courses --------------------------------------------------------------------
  // A cathedral's storeys are legible because two horizontals cut across every pier in the
  // building at the same height. Without them the three storeys blend into one tall wall.
  for (const [courseY, courseTone] of [
    [arcadeHeight, TONE.upper],
    [triforiumTop, TONE.upper],
  ] as const) {
    parts.push(
      part(
        new BoxGeometry(bayPitch, 0.42, 0.8).translate(0, courseY + 0.21, 0.05),
        courseTone,
      ),
    );
    parts.push(
      part(
        new BoxGeometry(bayPitch, 0.22, 0.5).translate(0, courseY + 0.53, 0.1),
        TONE.stone,
      ),
    );
  }

  // -- triforium: an arcade, not a slot ---------------------------------------------------
  // Four small pointed lights per bay. One opening per bay read as a letterbox; four read
  // as a storey, and the difference is entirely in the count of vertical mullions between
  // them catching light along their edges.
  const triforiumHeight = triforiumTop - arcadeHeight;
  const lights = 4;
  const lightSpan = bayPitch * 0.86;
  const lightPitch = lightSpan / lights;
  const triforiumOpenings: IOpening[] = [];
  for (let light = 0; light < lights; light += 1) {
    triforiumOpenings.push({
      centre: -lightSpan / 2 + lightPitch * (light + 0.5),
      halfWidth: lightPitch * 0.38,
      springY: triforiumHeight * 0.42,
    });
  }
  parts.push(
    part(
      piercedPanel(bayPitch, triforiumHeight, 0.55, triforiumOpenings).translate(
        0,
        arcadeHeight + 0.63,
        0,
      ),
      TONE.upper,
    ),
  );
  // Detached colonnettes in front of each mullion, and a solid backing behind the whole
  // storey. The triforium in a real nave is a *dark* arcade; the backing is what makes the
  // openings read as depth instead of as holes onto the aisle roof.
  for (let mullion = 0; mullion <= lights; mullion += 1) {
    parts.push(
      part(
        new CylinderGeometry(0.2, 0.2, triforiumHeight * 0.5, 8).translate(
          -lightSpan / 2 + lightPitch * mullion,
          arcadeHeight + 0.63 + triforiumHeight * 0.25,
          -0.3,
        ),
        TONE.upper,
      ),
    );
  }
  parts.push(
    part(
      new BoxGeometry(bayPitch, triforiumHeight, 0.3).translate(
        0,
        arcadeHeight + triforiumHeight / 2,
        1.25,
      ),
      TONE.void,
    ),
  );
  // The gallery sill: a shelf the colonnettes stand on, projecting further than the string
  // course below it. Without it the triforium is a row of holes floating on a flat wall.
  parts.push(
    part(
      new BoxGeometry(bayPitch, 0.3, 1.3).translate(0, arcadeHeight + 0.78, -0.45),
      TONE.upper,
    ),
  );

  // -- clerestory: a traceried window, not a hole ------------------------------------------
  // Three orders, each light splayed individually, plus a transom and nook-shafts. Every
  // number comes from `CLERESTORY` so the glass below is placed against the same aperture.
  const clerestoryHeight = clerestoryTop - CLERESTORY.base;
  let revealZ = 0;
  CLERESTORY.reveal.forEach((depth, order) => {
    // Order 0 sits on the nave face and is the widest; each order behind it steps in by one
    // splay. The last one is the aperture, and it is the one the sun is measured against.
    const halfWidth = CLERESTORY.aperture + CLERESTORY.splay * (CLERESTORY.reveal.length - 1 - order);
    parts.push(
      part(
        piercedPanel(
          bayPitch,
          clerestoryHeight,
          depth,
          CLERESTORY.lights.map((centre) => ({
            centre,
            halfWidth,
            springY: CLERESTORY.springY,
          })),
        ).translate(0, CLERESTORY.base, revealZ),
        TONE.upper,
      ),
    );
    revealZ += depth;
  });

  // The transom. It crosses both lights in the two outer orders, so the shadow map sees it
  // and each of the two shafts arrives in the nave as two — the horizontal break that reads
  // in the reference and that no amount of godray density can manufacture.
  parts.push(
    part(
      new BoxGeometry(
        (Math.abs(CLERESTORY.lights[1] ?? 1.5) + CLERESTORY.aperture) * 2 + 0.4,
        0.32,
        CLERESTORY_DEPTH - CLERESTORY.reveal[0],
      ).translate(0, CLERESTORY.base + CLERESTORY.transomY, CLERESTORY.reveal[0] ?? 0.9),
      TONE.bright,
    ),
  );

  // Nook-shafts in the jambs of each light. The splay is a stepped hole until something
  // stands in the step; these are what make it read as carved from the nave floor.
  const jambHalf = CLERESTORY.aperture + CLERESTORY.splay * (CLERESTORY.reveal.length - 1);
  for (const centre of CLERESTORY.lights) {
    for (const jamb of [-1, 1]) {
      parts.push(
        part(
          new CylinderGeometry(0.14, 0.14, CLERESTORY.springY + 0.4, 8).translate(
            centre + jamb * jambHalf,
            CLERESTORY.base + 0.3 + (CLERESTORY.springY + 0.4) / 2,
            0.34,
          ),
          TONE.bright,
        ),
      );
    }
  }

  return weld(parts, "bay wall");
}

// ---- the vault --------------------------------------------------------------------------

/**
 * One quadripartite severy: the real curved surface, not a ceiling plane with arcs hung
 * under it.
 *
 * A groin vault is the union of two barrels, so its height is `max` of the two pointed
 * profiles — `max`, not `min`, because the vault comes down to the springing only at the
 * four *corners* and stands at crown height along the middle of every edge. Taking the
 * larger of the two profiles puts the creases exactly on `|u| = |v|`, which is where the
 * diagonal ribs go; the ribs are then on the surface by construction rather than by eye.
 */
function vaultWeb(halfWidth: number, halfPitch: number, spring: number, rise: number): BufferGeometry {
  const columns = 24;
  const rows = 16;
  const positions: number[] = [];
  const uvs: number[] = [];
  const indices: number[] = [];
  for (let row = 0; row <= rows; row += 1) {
    const v = (row / rows) * 2 - 1;
    for (let column = 0; column <= columns; column += 1) {
      const u = (column / columns) * 2 - 1;
      positions.push(
        u * halfWidth,
        spring + rise * Math.max(pointedRise(u), pointedRise(v)),
        v * halfPitch,
      );
      uvs.push(column / columns, row / rows);
    }
  }
  const stride = columns + 1;
  for (let row = 0; row < rows; row += 1) {
    for (let column = 0; column < columns; column += 1) {
      const a = row * stride + column;
      const b = a + 1;
      const c = a + stride;
      // Wound so the face normal comes out downward. The vault is only ever seen from
      // below, so a single-sided surface facing the wrong way is an invisible ceiling.
      indices.push(a, b, c, b, c + 1, c);
    }
  }
  const web = new BufferGeometry();
  web.setAttribute("position", new Float32BufferAttribute(positions, 3));
  web.setAttribute("uv", new Float32BufferAttribute(uvs, 2));
  web.setIndex(indices);
  web.computeVertexNormals();
  return web;
}

/**
 * Where a rib meets the springing, pulled off the ideal surface and onto the vault-shaft
 * corbel it visually lands on.
 *
 * The web springs from the wall face; the shafts stand two metres proud of it. Left alone
 * the ribs would die into a blank wall a shaft-width away from the corbel that is plainly
 * carrying them. The pull only acts over the last quarter of the curve, so the rib is still
 * exactly on the web everywhere the crease is visible.
 */
function ribFoot(point: Vector3, along: number, inset: number, drop: number): Vector3 {
  const pull = Math.max(0, (Math.abs(along) - 0.72) / 0.28);
  if (pull === 0) return point;
  point.x -= Math.sign(point.x) * inset * pull;
  point.y -= drop * pull;
  return point;
}

// ---- the building ------------------------------------------------------------------------

/**
 * The nave. Floor at y = 0, running east toward -Z where the rose window closes the axis.
 *
 * `floorTexture` is the patterned marble. It is a parameter rather than a load inside this
 * function because the texture has to be resolved before the first frame — a floor that
 * pops in three frames later is a floor the screen-space reflection pass has already
 * gathered without.
 */
export function createCathedral(floorTexture?: Texture): Group {
  const { width, height, depth, bayPitch, arcadeHeight, pierRadius } = NAVE;
  const { triforiumTop, clerestoryTop, aisleWidth } = NAVE;
  /**
   * How far the aisle runs behind each colonnade, for the wall and its windows.
   *
   * Shorter than `NAVE.aisleWidth`, which still sets the paved extent. An arcade opening
   * is a 1.2 m-deep slot, and from a camera on the axis every sightline through it is
   * within thirty degrees of the wall plane: at six metres the far wall subtended less
   * than a metre of that slot and the aisle rendered as solid black. Bringing the wall in
   * is what makes lit tracery visible behind the colonnade at all.
   */
  const aisleDepth = 4.6;
  const nave = new Group();
  nave.name = "cathedral";
  const bays = Math.floor(depth / bayPitch);
  const halfDepth = (bays * bayPitch) / 2;
  const halfWidth = width / 2;
  /** Two bays of apse behind the chancel arch. The east end recedes; it is not one wall. */
  const chancelZ = -halfDepth + bayPitch * 2;

  // ---- floor -------------------------------------------------------------------------
  // Polished, and patterned. A mirror floor with no pattern gives the reflection nothing to
  // be a reflection *of*, and the eye reads it as fog.
  const floorWidth = width + aisleWidth * 2;
  const floorDepth = bays * bayPitch;
  if (floorTexture !== undefined) {
    floorTexture.wrapS = RepeatWrapping;
    floorTexture.wrapT = RepeatWrapping;
    // One tile every 4.5 m, which puts roughly two of the pattern's rosettes across a bay.
    // Tiling finer turns the inlay into noise the reflection cannot resolve; coarser and
    // the scale of the building reads wrong against a human-sized figure.
    floorTexture.repeat.set(floorWidth / 4.5, floorDepth / 4.5);
    floorTexture.colorSpace = SRGBColorSpace;
    floorTexture.anisotropy = 8;
    materials.marble.map = floorTexture;
    // The base colour multiplies the map. Anything but white tints the marble twice.
    materials.marble.color.setHex(0xffffff);
    materials.marble.needsUpdate = true;
  }
  const floor = new Mesh(new PlaneGeometry(floorWidth, floorDepth), materials.marble);
  floor.rotation.x = -Math.PI / 2;
  floor.receiveShadow = true;
  nave.add(floor);

  // ---- the two arcade walls ----------------------------------------------------------
  // One geometry, eighteen instances. `rotation.y = side · π/2` maps the panel's local +Z
  // (into the wall) onto the outward direction on either side, which is what makes one
  // asymmetric bay serve both colonnades.
  const wall = new InstancedMesh(bayWall(), materials.carved, bays * 2);
  wall.castShadow = true;
  wall.receiveShadow = true;
  let wallInstance = 0;
  for (const side of [-1, 1]) {
    for (let bay = 0; bay < bays; bay += 1) {
      const z = -halfDepth + bay * bayPitch + bayPitch / 2;
      scratch.makeRotationY((side * Math.PI) / 2).setPosition(side * halfWidth, 0, z);
      wall.setMatrixAt(wallInstance, scratch);
      wallInstance += 1;
    }
  }
  wall.instanceMatrix.needsUpdate = true;
  nave.add(wall);

  // ---- glass ---------------------------------------------------------------------------
  // Two clerestory materials rather than one with instance colours: `toneMapped: false` is
  // the whole trick here and a per-instance tint is one more thing that can quietly stop
  // being honoured under a node material.
  //
  // One pane per *light*, and it stays a `PlaneGeometry`: the textures lane maps a whole
  // stained-glass panel onto anything that already carries 0..1 UVs and reprojects one
  // panel across anything that does not. Welding the two lights of a bay into one geometry
  // would smear a single panel across both of them.
  const paneGeometry = new PlaneGeometry(CLERESTORY.aperture * 2, CLERESTORY_LIGHT_HEIGHT);
  const paneY = CLERESTORY.base + CLERESTORY_LIGHT_HEIGHT * 0.5;
  // Just inside the aperture, so the reveal in front of it still shades the glass.
  const paneX = halfWidth + CLERESTORY_DEPTH - 0.02;
  for (const [tint, parity] of [
    [palette.glassWarm, 0],
    [palette.glassCool, 1],
  ] as const) {
    const count = Math.ceil(bays / 2) * 2 * CLERESTORY.lights.length;
    const panes = new InstancedMesh(paneGeometry, glass(tint), count);
    let paneInstance = 0;
    for (const side of [-1, 1]) {
      for (let bay = 0; bay < bays; bay += 1) {
        if (bay % 2 !== parity) continue;
        const z = -halfDepth + bay * bayPitch + bayPitch / 2;
        for (const light of CLERESTORY.lights) {
          // The lights sit symmetrically about the bay centre, so the same pair of world
          // offsets is correct whichever way the panel was turned.
          scratch
            .makeRotationY((side * Math.PI) / 2)
            .setPosition(side * paneX, paneY, z + light);
          panes.setMatrixAt(paneInstance, scratch);
          paneInstance += 1;
        }
      }
    }
    panes.count = paneInstance;
    panes.instanceMatrix.needsUpdate = true;
    nave.add(panes);
  }

  // Aisle windows. Dimmer than the clerestory on purpose: the aisles must stay the dark
  // half of the picture, but a colonnade with nothing behind it reads as a wall, and the
  // reference plainly shows lit tracery through the arcade openings.
  const aisleGlass = new InstancedMesh(
    new PlaneGeometry(bayPitch * 0.64, 9.2),
    glass(0xd8a2ae),
    bays * 2,
  );
  let aisleInstance = 0;
  for (const side of [-1, 1]) {
    for (let bay = 0; bay < bays; bay += 1) {
      const z = -halfDepth + bay * bayPitch + bayPitch / 2;
      scratch
        .makeRotationY((side * Math.PI) / 2)
        // Behind the aisle wall's own opening, not in front of it: the pointed head of that
        // opening is what makes the light beyond the colonnade read as a window.
        .setPosition(side * (halfWidth + aisleDepth + 0.54), 5.0, z);
      aisleGlass.setMatrixAt(aisleInstance, scratch);
      aisleInstance += 1;
    }
  }
  aisleGlass.instanceMatrix.needsUpdate = true;
  nave.add(aisleGlass);

  // ---- piers ---------------------------------------------------------------------------
  // On the bay joints, sitting on the wall line so the back of the pier is engaged in the
  // wall and only the shaft cluster stands in the nave — which is what a compound pier is.
  const pierR = pierRadius * 1.05;
  const vaultShaftTop = clerestoryTop - 0.7;
  const pierGeometry = compoundPier(pierR, ARCADE_SPRING, vaultShaftTop);
  const piers = new InstancedMesh(pierGeometry, materials.carved, (bays + 1) * 2);
  piers.castShadow = true;
  piers.receiveShadow = true;
  let pierInstance = 0;
  for (const side of [-1, 1]) {
    for (let bay = 0; bay <= bays; bay += 1) {
      // Local +X faces the nave, so the far colonnade is the same geometry turned round —
      // never a negative scale, which would invert every normal in the merged pier.
      scratch
        .makeRotationY(side > 0 ? Math.PI : 0)
        .setPosition(side * (halfWidth + 0.3), 0, -halfDepth + bay * bayPitch);
      piers.setMatrixAt(pierInstance, scratch);
      pierInstance += 1;
    }
  }
  piers.instanceMatrix.needsUpdate = true;
  nave.add(piers);

  // ---- aisles ----------------------------------------------------------------------------
  const aisleWalls = new InstancedMesh(
    aisleBay(bayPitch, arcadeHeight),
    materials.carved,
    bays * 2,
  );
  aisleWalls.receiveShadow = true;
  let aisleWallInstance = 0;
  for (const side of [-1, 1]) {
    for (let bay = 0; bay < bays; bay += 1) {
      const z = -halfDepth + bay * bayPitch + bayPitch / 2;
      scratch
        .makeRotationY((side * Math.PI) / 2)
        .setPosition(side * (halfWidth + aisleDepth), 0, z);
      aisleWalls.setMatrixAt(aisleWallInstance, scratch);
      aisleWallInstance += 1;
    }
  }
  aisleWalls.instanceMatrix.needsUpdate = true;
  nave.add(aisleWalls);

  for (const side of [-1, 1]) {
    const aisleVault = new Mesh(
      new PlaneGeometry(bays * bayPitch, aisleDepth),
      materials.shadowStone,
    );
    aisleVault.rotation.set(Math.PI / 2, 0, Math.PI / 2);
    aisleVault.position.set(side * (halfWidth + aisleDepth / 2), arcadeHeight - 0.4, 0);
    nave.add(aisleVault);
  }

  // ---- vault -------------------------------------------------------------------------
  const rise = height - clerestoryTop;
  const halfPitch = bayPitch / 2;
  const webs = new InstancedMesh(
    // A shade below the walls. The web takes bounce off the whole nave and nothing direct,
    // so at the wall's own tint it blew out to paper-white and flattened the ribs off it.
    part(vaultWeb(halfWidth, halfPitch, clerestoryTop, rise), 0x5c5449),
    materials.carved,
    bays,
  );
  // The vault casts nothing: the sun enters below its springing through the clerestory, so
  // every shadow-map texel it would occupy is spent on nothing the camera can see.
  webs.castShadow = false;
  webs.receiveShadow = true;

  // ribs, per bay: two diagonals across the severy and two wall arcs against the clerestory
  const shaftInset = halfWidth - (pierR * 1.52 + 0.44 + 0.3);
  const ribParts: BufferGeometry[] = [];
  const samples = 13;
  for (const lean of [1, -1]) {
    const points: Vector3[] = [];
    for (let sample = 0; sample < samples; sample += 1) {
      const along = (sample / (samples - 1)) * 2 - 1;
      points.push(
        ribFoot(
          new Vector3(
            along * halfWidth,
            clerestoryTop + rise * pointedRise(along),
            along * lean * halfPitch,
          ),
          along,
          shaftInset,
          0.7,
        ),
      );
    }
    ribParts.push(part(ribTube(points, 0.36), TONE.bright));
  }
  for (const side of [-1, 1]) {
    // The formeret: the arch of the vault against the clerestory wall. It is what turns the
    // top of each window into a lunette instead of a rectangle cut off by a ceiling.
    const points: Vector3[] = [];
    for (let sample = 0; sample < samples; sample += 1) {
      const along = (sample / (samples - 1)) * 2 - 1;
      points.push(
        new Vector3(
          side * (halfWidth - 0.32),
          clerestoryTop + rise * pointedRise(along),
          along * halfPitch,
        ),
      );
    }
    ribParts.push(part(ribTube(points, 0.24), TONE.bright));
  }
  const bayRibs = new InstancedMesh(weld(ribParts, "bay ribs"), materials.carved, bays);
  bayRibs.castShadow = false;

  // The transverse rib sits on the bay *joint*, shared by the two severies either side, so
  // it is instanced once per joint rather than once per bay.
  const transversePoints: Vector3[] = [];
  for (let sample = 0; sample < samples; sample += 1) {
    const along = (sample / (samples - 1)) * 2 - 1;
    transversePoints.push(
      ribFoot(
        new Vector3(along * halfWidth, clerestoryTop + rise * pointedRise(along), 0),
        along,
        shaftInset,
        0.7,
      ),
    );
  }
  const transverse = new InstancedMesh(
    part(ribTube(transversePoints, 0.38), TONE.bright),
    materials.carved,
    bays + 1,
  );
  transverse.castShadow = false;

  const bosses = new InstancedMesh(
    part(
      new SphereGeometry(0.62, 10, 8).scale(1, 0.7, 1).translate(0, height - 0.3, 0),
      TONE.bright,
    ),
    materials.carved,
    bays,
  );
  bosses.castShadow = false;

  for (let bay = 0; bay < bays; bay += 1) {
    const z = -halfDepth + bay * bayPitch + bayPitch / 2;
    scratch.makeRotationY(0).setPosition(0, 0, z);
    webs.setMatrixAt(bay, scratch);
    bayRibs.setMatrixAt(bay, scratch);
    bosses.setMatrixAt(bay, scratch);
  }
  for (let joint = 0; joint <= bays; joint += 1) {
    scratch.makeRotationY(0).setPosition(0, 0, -halfDepth + joint * bayPitch);
    transverse.setMatrixAt(joint, scratch);
  }
  webs.instanceMatrix.needsUpdate = true;
  bayRibs.instanceMatrix.needsUpdate = true;
  transverse.instanceMatrix.needsUpdate = true;
  bosses.instanceMatrix.needsUpdate = true;
  nave.add(webs, bayRibs, transverse, bosses);

  // ---- east end ------------------------------------------------------------------------
  // The chancel arch. One enormous pointed opening two bays short of the east wall, so the
  // apse is seen *through* something. A single flat wall closing the axis is the difference
  // between a nave and a corridor, however good the tracery on it is.
  const chancelParts: BufferGeometry[] = [];
  // Ordered by depth from the *east*: this panel is extruded away from the camera, so the
  // widest opening belongs on the highest local z, which is the face the nave sees.
  const chancelOrders = [
    { depth: 0.7, halfWidth: 5.6, tone: TONE.stone, z: 0 },
    { depth: 0.55, halfWidth: 6.1, tone: TONE.bright, z: 0.7 },
    { depth: 0.75, halfWidth: 6.6, tone: TONE.bright, z: 1.25 },
  ] as const;
  for (const order of chancelOrders) {
    chancelParts.push(
      part(
        piercedPanel(width, 26, order.depth, [{ halfWidth: order.halfWidth, springY: 12 }]).translate(
          0,
          0,
          order.z,
        ),
        order.tone,
      ),
    );
  }
  const chancelArch = new Mesh(weld(chancelParts, "chancel arch"), materials.carved);
  // Extruded along +Z from the shape plane; pushed back so the nave face lands on the joint.
  chancelArch.position.set(0, 0, chancelZ - 2);
  chancelArch.castShadow = true;
  chancelArch.receiveShadow = true;
  nave.add(chancelArch);

  // The apse itself: a back wall and two canted returns, so the east end has a plan and not
  // just an elevation. The canted walls are what stop the rose reading as a poster.
  const apseBack = new Mesh(new PlaneGeometry(13.6, height), materials.apseStone);
  apseBack.position.set(0, height / 2, -halfDepth);
  apseBack.receiveShadow = true;
  nave.add(apseBack);
  for (const side of [-1, 1]) {
    const from = new Vector3(side * halfWidth, 0, chancelZ);
    const to = new Vector3(side * 6.8, 0, -halfDepth);
    const span = from.distanceTo(to);
    const cant = new Mesh(new PlaneGeometry(span, height), materials.apseStone);
    cant.position.set((from.x + to.x) / 2, height / 2, (from.z + to.z) / 2);
    cant.rotation.y = Math.atan2(to.x - from.x, to.z - from.z) + Math.PI / 2;
    cant.receiveShadow = true;
    nave.add(cant);
  }

  // ---- the rose ------------------------------------------------------------------------
  // Brightest object in the frame and the thing that closes the axis. Sized and sited so a
  // camera on the nave floor sees the whole wheel through the chancel arch; a rose whose
  // top is clipped by the arch in front of it is a rose nobody can read.
  const roseRadius = 5;
  const roseY = 17.5;
  const roseZ = -halfDepth + 0.12;
  // A disc. The square pane behind the tracery showed its corners as four bright pink
  // quadrants outside the wheel — the loudest single wrongness in the previous capture.
  const rose = new Mesh(new RingGeometry(0, roseRadius, 48), glass(palette.glassRose));
  rose.position.set(0, roseY, roseZ);
  nave.add(rose);

  const traceryParts: BufferGeometry[] = [];
  /** A radial bar between two rings: built at the origin, pushed out, then swung round. */
  const spokeBetween = (from: number, to: number, angle: number, width: number) =>
    part(
      new BoxGeometry(width, (to - from) * roseRadius, 0.26)
        .translate(0, ((from + to) / 2) * roseRadius, 0)
        .rotateZ(angle),
      TONE.bright,
    );
  /** A cusped light: a small circle of tracery, which is what a rose is actually made of. */
  const cusp = (radiusRatio: number, sizeRatio: number, angle: number, tube: number) =>
    part(
      new TorusGeometry(roseRadius * sizeRatio, tube, 6, 14).translate(
        Math.cos(angle) * roseRadius * radiusRatio,
        Math.sin(angle) * roseRadius * radiusRatio,
        0,
      ),
      TONE.bright,
    );

  // Four rings, and radial bars only *between* them — never across the whole wheel.
  //
  // Sixteen full-diameter spokes is a dartboard: every bar runs through the centre, the eye
  // reads one flat star, and it fights the map behind it, which draws deep blue lights in
  // concentric bands. Short bars that stop at a ring, with a cusped circle in each cell,
  // give the wheel the two things a real rose has — a hub, and rings that each carry their
  // own count of lights.
  for (const ratio of [0.15, 0.36, 0.62, 0.88]) {
    traceryParts.push(
      part(new RingGeometry(roseRadius * ratio - 0.1, roseRadius * ratio + 0.1, 44), TONE.bright),
    );
  }
  for (let spoke = 0; spoke < 8; spoke += 1) {
    const angle = (spoke / 8) * Math.PI * 2;
    traceryParts.push(spokeBetween(0.15, 0.36, angle, 0.17));
  }
  for (let spoke = 0; spoke < 16; spoke += 1) {
    const angle = (spoke / 16) * Math.PI * 2 + Math.PI / 16;
    traceryParts.push(spokeBetween(0.62, 0.88, angle, 0.15));
  }
  // The inner ring of eight lights, and the outer ring of sixteen. Doubling the count as
  // the radius grows is what keeps every cell about the same size, and it is the reason a
  // rose reads as a pattern rather than as a pie chart.
  for (let petal = 0; petal < 8; petal += 1) {
    const angle = (petal / 8) * Math.PI * 2 + Math.PI / 8;
    traceryParts.push(cusp(0.49, 0.115, angle, 0.085));
  }
  for (let petal = 0; petal < 16; petal += 1) {
    const angle = (petal / 16) * Math.PI * 2;
    traceryParts.push(cusp(0.75, 0.085, angle, 0.07));
  }
  traceryParts.push(part(new RingGeometry(roseRadius, roseRadius + 1.1, 48), TONE.bright));
  const tracery = new Mesh(weld(traceryParts, "rose tracery"), materials.carved);
  tracery.position.set(0, roseY, roseZ + 0.22);
  nave.add(tracery);

  // No separate eye disc. The rose map already draws one, and `surfaces.ts` deliberately
  // leaves any disc under three metres untextured — so a mesh here is a flat warm lid over
  // the middle of the wheel rather than a centre for it, which is exactly how it read.

  // The rose's own architecture: a gable over it and a shaft either side. A wheel pasted on
  // a blank plane reads as a decal; the gable is what tells the eye that the east wall has
  // a front, and its two slopes are the only diagonals in an otherwise all-vertical wall.
  const surroundParts: BufferGeometry[] = [];
  const gableFoot = new Vector2(6.5, 21.3);
  const gableApex = 27;
  const gableRun = Math.hypot(gableFoot.x, gableApex - gableFoot.y);
  for (const slope of [-1, 1]) {
    surroundParts.push(
      part(
        new BoxGeometry(gableRun + 0.4, 0.55, 0.45)
          .rotateZ(slope * -Math.atan2(gableApex - gableFoot.y, gableFoot.x))
          .translate((slope * gableFoot.x) / 2, (gableFoot.y + gableApex) / 2, 0),
        TONE.bright,
      ),
    );
  }
  for (const flank of [-1, 1]) {
    surroundParts.push(
      part(
        new CylinderGeometry(0.42, 0.42, 21.6, 10).translate(flank * 6.5, 10.8, 0),
        TONE.stone,
      ),
    );
  }
  const roseSurround = new Mesh(weld(surroundParts, "rose surround"), materials.carved);
  roseSurround.position.set(0, 0, -halfDepth + 0.55);
  roseSurround.castShadow = true;
  nave.add(roseSurround);

  // ---- the east lancets ------------------------------------------------------------------
  // Three pointed lights under the rose, the centre one taller — which is what stops three
  // equal windows reading as a fence and makes the group point at the wheel above it.
  const lancetParts: BufferGeometry[] = [];
  const lancetGlass: BufferGeometry[] = [];
  for (const light of [-1, 0, 1]) {
    const lancetHalf = 0.7;
    const lancetHeight = light === 0 ? 6.1 : 4.4;
    const shape = new Shape();
    shape.moveTo(-lancetHalf, 0);
    shape.lineTo(-lancetHalf, lancetHeight);
    shape.absarc(lancetHalf, lancetHeight, 2 * lancetHalf, Math.PI, (Math.PI * 2) / 3, true);
    shape.absarc(-lancetHalf, lancetHeight, 2 * lancetHalf, Math.PI / 3, 0, true);
    shape.lineTo(lancetHalf, 0);
    shape.closePath();
    lancetGlass.push(
      new ExtrudeGeometry(shape, { bevelEnabled: false, depth: 0.1 }).translate(light * 2.0, 5.0, 0),
    );
    // A mullion up the middle of each light, and a jamb either side. Glass with no bar
    // across it blooms into one soft lozenge and loses the pointed head entirely.
    lancetParts.push(
      part(
        new BoxGeometry(0.16, lancetHeight + lancetHalf * SQRT3, 0.3).translate(
          light * 2.0,
          5.0 + (lancetHeight + lancetHalf * SQRT3) / 2,
          0.24,
        ),
        TONE.bright,
      ),
    );
    for (const jamb of [-1, 1]) {
      lancetParts.push(
        part(
          new BoxGeometry(0.24, lancetHeight + 0.6, 0.5).translate(
            light * 2.0 + jamb * (lancetHalf + 0.16),
            5.0 + (lancetHeight + 0.6) / 2,
            0.2,
          ),
          // Jambs in plain stone, not the bright tint. Six bright bars beside three bright
          // panes fused into one striped slab and the lancets stopped reading as windows.
          TONE.stone,
        ),
      );
    }
  }
  // Half value. At full `glassCool` the three lights fused into one blue slab under the
  // rose and took the wheel's job; the rose has to stay the brightest thing on the axis.
  const lancets = new Mesh(weld(lancetGlass, "east lancets"), glass(0x5f7ec4));
  lancets.position.set(0, 0, -halfDepth + 0.1);
  nave.add(lancets);
  const lancetFrames = new Mesh(weld(lancetParts, "lancet frames"), materials.carved);
  lancetFrames.position.set(0, 0, -halfDepth + 0.1);
  nave.add(lancetFrames);

  // The canopy: one containing arch over all three lights, so the group sits in a recess
  // rather than being pasted flat on the apse wall. The two-centre head narrows fast near
  // its apex, which is why the side lights are shorter than the centre one — they have to
  // fit under the curve, and that stepping is also what makes the group point at the rose.
  //
  // It stops just above its own apex on purpose. Carried up to the vault it becomes a slab
  // standing in front of the rose, and the rose is the one object on this axis that may
  // never be occluded.
  const canopy = new Mesh(
    part(
      piercedPanel(11, 13.9, 0.45, [{ halfWidth: 4.4, springY: 6 }]),
      TONE.stone,
    ),
    materials.carved,
  );
  canopy.position.set(0, 0, -halfDepth + 0.2);
  canopy.castShadow = true;
  canopy.receiveShadow = true;
  nave.add(canopy);

  // A gable on the canopy, for the same reason the rose has one: a pierced panel ends in a
  // straight horizontal edge, and against a lit apse wall that edge reads as the top of a
  // rectangle stuck on the wall rather than as the head of a window.
  const canopyParts: BufferGeometry[] = [];
  const canopyFoot = new Vector2(5.4, 13.6);
  const canopyApex = 16.4;
  const canopyRun = Math.hypot(canopyFoot.x, canopyApex - canopyFoot.y);
  for (const slope of [-1, 1]) {
    canopyParts.push(
      part(
        new BoxGeometry(canopyRun + 0.35, 0.5, 0.5)
          .rotateZ(slope * -Math.atan2(canopyApex - canopyFoot.y, canopyFoot.x))
          .translate((slope * canopyFoot.x) / 2, (canopyFoot.y + canopyApex) / 2, 0),
        TONE.bright,
      ),
    );
  }
  const canopyGable = new Mesh(weld(canopyParts, "canopy gable"), materials.carved);
  canopyGable.position.set(0, 0, -halfDepth + 0.62);
  canopyGable.castShadow = true;
  nave.add(canopyGable);

  // ---- chancel floor, altar, screen ---------------------------------------------------------
  // Three steps, not one box. The step nosings are the horizontal that breaks the floor's
  // reflection near the east end, and one 45 cm slab gives exactly one such line.
  const stepParts: BufferGeometry[] = [];
  for (let step = 0; step < 3; step += 1) {
    stepParts.push(
      new BoxGeometry(width * 0.82 - step * 0.7, 0.36, 1.0).translate(
        0,
        0.18 + step * 0.36,
        chancelZ + 2.6 - step * 1.0,
      ),
    );
  }
  stepParts.push(
    new BoxGeometry(11.6, 1.08, bayPitch * 2 + 1).translate(0, 0.54, chancelZ - bayPitch + 0.5),
  );
  const chancelFloor = new Mesh(weld(stepParts, "steps"), materials.marbleBand);
  chancelFloor.castShadow = true;
  chancelFloor.receiveShadow = true;
  nave.add(chancelFloor);

  const altar = new Mesh(part(new BoxGeometry(4.2, 1.35, 1.9), TONE.bright), materials.carved);
  altar.position.set(0, 1.08 + 0.68, chancelZ - 6.5);
  altar.castShadow = true;
  altar.receiveShadow = true;
  nave.add(altar);

  // The chancel screen: near-black vertical bars, read as silhouette against the lit apse.
  const screen = new InstancedMesh(new BoxGeometry(0.13, 3.4, 0.13), materials.iron, 27);
  for (let bar = 0; bar < 27; bar += 1) {
    // On the raised chancel platform, inside the arch — a screen standing on the nave floor
    // reads as railings in a corridor rather than as the boundary of the sanctuary.
    scratch.makeRotationY(0).setPosition((bar - 13) * 0.5, 1.08 + 1.7, chancelZ - 0.8);
    screen.setMatrixAt(bar, scratch);
  }
  screen.instanceMatrix.needsUpdate = true;
  screen.castShadow = true;
  nave.add(screen);

  // The west wall, behind the camera. Off screen, and it still matters: it is the surface
  // bouncing light back down the nave that screen-space GI can never sample — the gap
  // PRD-268's probe volume exists to close.
  const westWall = new Mesh(
    new PlaneGeometry(width + aisleWidth * 2, height),
    materials.shadowStone,
  );
  westWall.position.set(0, height / 2, halfDepth);
  nave.add(westWall);

  return nave;
}
