// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// A gothic nave, built to `sculpt/cathedral.spec.json` and gated against
// `reference-cathedral.png`. Every proportion below derives from one bay, so the building
// cannot drift out of scale when a number is edited.
//
// The single silhouette cue that separates gothic from romanesque is the **two-centre
// pointed arch**, and it appears at three scales — arcade, triforium, clerestory. A wall
// with rectangular holes in it reads as a car park at any lighting quality, so the
// openings are real extruded shapes with real arch heads rather than boxes with gaps.
//
// What each part is here to do for the lighting chain:
//   godrays   the clerestory mullions cut one window into several separate shafts
//   ssgi      the aisles behind the colonnade receive no direct light whatsoever
//   gtao      pier bases, capital undersides, and the arch orders
//   ssr       the floor is the only low-roughness surface in the building
//   bloom     the glass is authored past the tonemap ceiling on purpose
import {
  BoxGeometry,
  BufferGeometry,
  CylinderGeometry,
  DoubleSide,
  ExtrudeGeometry,
  Group,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  Path,
  PlaneGeometry,
  RepeatWrapping,
  RingGeometry,
  Shape,
  SRGBColorSpace,
  type Texture,
  TorusGeometry,
} from "three";
import { NAVE } from "./lighting.js";
import { palette } from "./palette.js";

const materials = {
  /** The building. Rough, near-white, no metalness — it carries every bounce in the scene. */
  limestone: new MeshStandardMaterial({ color: palette.stone, roughness: 0.93, metalness: 0 }),
  /** The vault and the aisle walls, a shade down so the arcade reads in front of them. */
  shadowStone: new MeshStandardMaterial({ color: palette.stoneDark, roughness: 0.95, metalness: 0 }),
  /** The one low-roughness surface. Without it screen-space reflections have nothing to return. */
  marble: new MeshStandardMaterial({ color: palette.floor, roughness: 0.16, metalness: 0.1 }),
  marbleBand: new MeshStandardMaterial({ color: palette.floorBand, roughness: 0.2, metalness: 0.1 }),
  /** Near-black. The chancel screen reads as silhouette and nothing else. */
  iron: new MeshStandardMaterial({ color: 0x14120f, roughness: 0.55, metalness: 0.7 }),
};

function glass(colour: number): MeshBasicMaterial {
  // `toneMapped: false` with a colour at full value keeps the pane above the bloom
  // threshold. A window the tonemap can hold reads as a grey hole in a wall.
  return new MeshBasicMaterial({ color: colour, toneMapped: false, side: DoubleSide });
}

/**
 * A two-centre (equilateral) pointed arch opening, as a hole in a wall panel.
 *
 * Springing at `springY`, half-width `a`, apex at `springY + a·√3`. Both arcs have radius
 * `2a` and are centred on the *opposite* springing point — that is what a two-centre arch
 * is, and swapping in a semicircle here is the difference between this building and a
 * roman aqueduct.
 */
function pointedArchHole(a: number, springY: number): Path {
  const hole = new Path();
  hole.moveTo(-a, 0);
  hole.lineTo(-a, springY);
  hole.absarc(a, springY, 2 * a, Math.PI, (Math.PI * 2) / 3, true);
  hole.absarc(-a, springY, 2 * a, Math.PI / 3, 0, true);
  hole.lineTo(a, 0);
  hole.closePath();
  return hole;
}

/** A wall panel of `width × height`, pierced by one pointed opening, extruded `thickness` deep. */
function piercedPanel(
  width: number,
  height: number,
  thickness: number,
  opening: { halfWidth: number; springY: number },
): BufferGeometry {
  const panel = new Shape();
  panel.moveTo(-width / 2, 0);
  panel.lineTo(width / 2, 0);
  panel.lineTo(width / 2, height);
  panel.lineTo(-width / 2, height);
  panel.closePath();
  panel.holes.push(pointedArchHole(opening.halfWidth, opening.springY));
  const geometry = new ExtrudeGeometry(panel, { depth: thickness, bevelEnabled: false });
  // Extrude builds along +Z from the shape plane; centre it so the panel's own position is
  // its middle and the two rows of the arcade stay symmetric about the nave axis.
  geometry.translate(0, 0, -thickness / 2);
  return geometry;
}

/**
 * One clustered pier: an octagonal core with engaged shafts around it.
 *
 * A plain cylinder catches one broad highlight and reads as a pipe. The cluster is what
 * gives a pier its vertical rhythm of bright and dark lines when a shaft of light crosses
 * it, which is most of why the reference reads as stone.
 */
function clusteredPier(radius: number, height: number): Group {
  const pier = new Group();

  const core = new Mesh(new CylinderGeometry(radius, radius, height, 8), materials.limestone);
  core.position.y = height / 2;
  core.castShadow = true;
  core.receiveShadow = true;
  pier.add(core);

  const shaftRadius = radius * 0.3;
  for (let index = 0; index < 5; index += 1) {
    // Five, spread over the front 240° only: the back of a pier faces the dark aisle and
    // a shaft there costs geometry and shows nothing.
    const angle = -Math.PI * 0.66 + (index / 4) * Math.PI * 1.32;
    const shaft = new Mesh(
      new CylinderGeometry(shaftRadius, shaftRadius, height, 10),
      materials.limestone,
    );
    shaft.position.set(
      Math.sin(angle) * (radius + shaftRadius * 0.55),
      height / 2,
      Math.cos(angle) * (radius + shaftRadius * 0.55),
    );
    shaft.castShadow = true;
    shaft.receiveShadow = true;
    pier.add(shaft);
  }

  const plinth = new Mesh(
    new BoxGeometry(radius * 3, 0.9, radius * 3),
    materials.shadowStone,
  );
  plinth.position.y = 0.45;
  plinth.castShadow = true;
  plinth.receiveShadow = true;
  pier.add(plinth);

  // The capital: a bright horizontal line across a dark pier, and the thing the arch and
  // the vault ribs both spring from.
  const capital = new Mesh(new BoxGeometry(radius * 3.1, 1.1, radius * 3.1), materials.limestone);
  capital.position.y = height - 0.55;
  capital.castShadow = true;
  capital.receiveShadow = true;
  pier.add(capital);

  return pier;
}

/**
 * The nave. Floor at y = 0, running east toward -Z where the rose window closes the axis.
 *
 * `floorTexture` is the patterned marble. It is a parameter rather than a load inside this
 * function because the texture has to be resolved before the first frame — a floor that
 * pops in three frames later is a floor the screen-space reflection pass has already
 * gathered without.
 */
export function createCathedral(floorTexture?: Texture): Group {
  const { width, height, depth, bayPitch, arcadeHeight, pierRadius } = NAVE;
  const { triforiumTop, clerestoryTop, aisleWidth } = NAVE;
  const nave = new Group();
  nave.name = "cathedral";
  const bays = Math.floor(depth / bayPitch);
  const halfDepth = (bays * bayPitch) / 2;

  // ---- floor -------------------------------------------------------------------------
  // Polished, and banded across the axis. The bands are not decoration: a mirror floor
  // with no pattern gives the reflection nothing to be a reflection *of*, and the eye
  // reads it as fog.
  const floorWidth = width + aisleWidth * 2;
  const floorDepth = bays * bayPitch;
  if (floorTexture !== undefined) {
    floorTexture.wrapS = RepeatWrapping;
    floorTexture.wrapT = RepeatWrapping;
    // One tile every 4.5 m, which puts roughly two of the pattern's rosettes across a bay.
    // Tiling finer turns the inlay into noise the reflection cannot resolve; coarser and
    // the scale of the building reads wrong against a human-sized figure.
    floorTexture.repeat.set(floorWidth / 4.5, floorDepth / 4.5);
    floorTexture.colorSpace = SRGBColorSpace;
    floorTexture.anisotropy = 8;
    materials.marble.map = floorTexture;
    // The base colour multiplies the map. Anything but white tints the marble twice.
    materials.marble.color.setHex(0xffffff);
    materials.marble.needsUpdate = true;
  }
  const floor = new Mesh(new PlaneGeometry(floorWidth, floorDepth), materials.marble);
  floor.rotation.x = -Math.PI / 2;
  floor.receiveShadow = true;
  nave.add(floor);

  // The chancel steps break the reflection line near the east end; the bands that used to
  // run down the whole nave are gone, because the marble map now carries that rhythm.

  // ---- the two arcade walls ----------------------------------------------------------
  // Built as pierced panels rather than piers-with-gaps, so each opening has a real arch
  // head and the shadow map sees one clean silhouette per bay.
  const arcadeOpening = { halfWidth: bayPitch * 0.36, springY: arcadeHeight * 0.52 };
  const arcadePanel = piercedPanel(bayPitch, arcadeHeight, 1.0, arcadeOpening);

  const triforiumHeight = triforiumTop - arcadeHeight;
  const triforiumPanel = piercedPanel(bayPitch, triforiumHeight, 0.8, {
    halfWidth: bayPitch * 0.17,
    springY: triforiumHeight * 0.45,
  });

  const clerestoryHeight = clerestoryTop - triforiumTop;
  const clerestoryOpening = { halfWidth: bayPitch * 0.26, springY: clerestoryHeight * 0.42 };
  const clerestoryPanel = piercedPanel(bayPitch, clerestoryHeight, 0.7, clerestoryOpening);

  for (const side of [-1, 1]) {
    const x = (side * width) / 2;
    for (let bay = 0; bay < bays; bay += 1) {
      const z = -halfDepth + bay * bayPitch + bayPitch / 2;

      const arcade = new Mesh(arcadePanel, materials.limestone);
      arcade.rotation.y = Math.PI / 2;
      arcade.position.set(x, 0, z);
      arcade.castShadow = true;
      arcade.receiveShadow = true;
      nave.add(arcade);

      const triforium = new Mesh(triforiumPanel, materials.shadowStone);
      triforium.rotation.y = Math.PI / 2;
      triforium.position.set(x, arcadeHeight, z);
      triforium.castShadow = true;
      triforium.receiveShadow = true;
      nave.add(triforium);

      const clerestory = new Mesh(clerestoryPanel, materials.limestone);
      clerestory.rotation.y = Math.PI / 2;
      clerestory.position.set(x, triforiumTop, z);
      clerestory.castShadow = true;
      clerestory.receiveShadow = true;
      nave.add(clerestory);

      // The mullion. One vertical bar in the middle of each clerestory light is what
      // turns one shaft into two, and two shafts read as light where one reads as haze.
      const mullion = new Mesh(
        new BoxGeometry(0.9, clerestoryOpening.springY + clerestoryOpening.halfWidth * 1.7, 0.28),
        materials.limestone,
      );
      mullion.rotation.y = Math.PI / 2;
      mullion.position.set(
        x,
        triforiumTop + (clerestoryOpening.springY + clerestoryOpening.halfWidth * 1.7) / 2,
        z,
      );
      mullion.castShadow = true;
      nave.add(mullion);

      const pane = new Mesh(
        new PlaneGeometry(
          clerestoryOpening.halfWidth * 2,
          clerestoryOpening.springY + clerestoryOpening.halfWidth * 1.7,
        ),
        glass(bay % 2 === 0 ? palette.glassWarm : palette.glassCool),
      );
      pane.rotation.y = Math.PI / 2;
      pane.position.set(
        x + side * 0.02,
        triforiumTop + (clerestoryOpening.springY + clerestoryOpening.halfWidth * 1.7) / 2,
        z,
      );
      nave.add(pane);
    }

    // The outer aisle wall, behind the colonnade. It is the surface that stays dark, and
    // the reason the arcade openings read as openings.
    const aisleWall = new Mesh(
      new PlaneGeometry(bays * bayPitch, arcadeHeight + 2),
      materials.shadowStone,
    );
    aisleWall.rotation.y = side * -Math.PI / 2;
    aisleWall.position.set(x + side * aisleWidth, (arcadeHeight + 2) / 2, 0);
    aisleWall.receiveShadow = true;
    nave.add(aisleWall);

    const aisleVault = new Mesh(
      new PlaneGeometry(bays * bayPitch, aisleWidth),
      materials.shadowStone,
    );
    aisleVault.rotation.set(Math.PI / 2, 0, Math.PI / 2);
    aisleVault.position.set(x + (side * aisleWidth) / 2, arcadeHeight + 2, 0);
    nave.add(aisleVault);
  }

  // ---- piers -------------------------------------------------------------------------
  // On the bay joints, standing proud of the arcade wall into the nave.
  for (const side of [-1, 1]) {
    for (let bay = 0; bay <= bays; bay += 1) {
      const pier = clusteredPier(pierRadius, arcadeHeight + 1.2);
      pier.position.set((side * width) / 2 - side * pierRadius * 0.7, 0, -halfDepth + bay * bayPitch);
      nave.add(pier);

      // The vault shaft: a thin colonnette running from the capital to the springing of
      // the vault, which is what visually ties the floor to the ceiling in a gothic nave.
      const colonnette = new Mesh(
        new CylinderGeometry(pierRadius * 0.26, pierRadius * 0.26, clerestoryTop - arcadeHeight, 10),
        materials.limestone,
      );
      colonnette.position.set(
        (side * width) / 2 - side * pierRadius * 0.5,
        (clerestoryTop + arcadeHeight) / 2,
        -halfDepth + bay * bayPitch,
      );
      colonnette.castShadow = true;
      nave.add(colonnette);
    }
  }

  // ---- vault -------------------------------------------------------------------------
  const vault = new Mesh(new PlaneGeometry(width, bays * bayPitch), materials.shadowStone);
  vault.rotation.x = Math.PI / 2;
  vault.position.y = height;
  nave.add(vault);

  for (let bay = 0; bay < bays; bay += 1) {
    const z = -halfDepth + bay * bayPitch + bayPitch / 2;
    // Diagonal ribs: the X across each bay. They receive no direct light at all — every
    // pixel of them is indirect, which makes them the clearest read of whether the GI
    // stage is doing anything.
    for (const lean of [-1, 1]) {
      const rib = new Mesh(
        new TorusGeometry(width * 0.62, 0.28, 8, 24, Math.PI),
        materials.limestone,
      );
      rib.position.set(0, clerestoryTop, z);
      rib.rotation.set(0, (lean * Math.PI) / 4, 0);
      rib.scale.y = (height - clerestoryTop) / (width * 0.62);
      nave.add(rib);
    }

    const transverse = new Mesh(
      new TorusGeometry(width / 2, 0.32, 8, 24, Math.PI),
      materials.limestone,
    );
    transverse.position.set(0, clerestoryTop, -halfDepth + bay * bayPitch);
    transverse.rotation.y = Math.PI / 2;
    transverse.scale.y = (height - clerestoryTop) / (width / 2);
    nave.add(transverse);

    const boss = new Mesh(new CylinderGeometry(0.55, 0.55, 0.5, 10), materials.limestone);
    boss.position.set(0, height - 0.3, z);
    nave.add(boss);
  }

  // ---- east end ----------------------------------------------------------------------
  const eastWall = new Mesh(new PlaneGeometry(width, height), materials.limestone);
  eastWall.position.set(0, height / 2, -halfDepth);
  eastWall.receiveShadow = true;
  nave.add(eastWall);

  // The rose. Brightest object in the frame and the thing that closes the axis, so it sits
  // dead centre and everything else in the east end defers to it.
  const roseRadius = width * 0.28;
  const roseY = triforiumTop + roseRadius * 0.9;
  const rose = new Mesh(new PlaneGeometry(roseRadius * 2, roseRadius * 2), glass(palette.glassRose));
  rose.position.set(0, roseY, -halfDepth + 0.12);
  nave.add(rose);

  // Radial tracery. Without spokes the rose is a glowing disc; with them it is a window.
  for (let spoke = 0; spoke < 8; spoke += 1) {
    const bar = new Mesh(
      new BoxGeometry(0.34, roseRadius * 2, 0.3),
      materials.limestone,
    );
    bar.position.set(0, roseY, -halfDepth + 0.3);
    bar.rotation.z = (spoke / 8) * Math.PI;
    nave.add(bar);
  }
  for (const ratio of [0.34, 0.72]) {
    const ring = new Mesh(
      new RingGeometry(roseRadius * ratio - 0.16, roseRadius * ratio + 0.16, 40),
      materials.limestone,
    );
    ring.position.set(0, roseY, -halfDepth + 0.34);
    nave.add(ring);
  }
  // The eye at the centre, warm against the cool field. Every real rose has one and it is
  // what gives the wheel a centre to be a wheel around.
  const roseEye = new Mesh(
    new RingGeometry(0, roseRadius * 0.16, 20),
    glass(palette.glassWarm),
  );
  roseEye.position.set(0, roseY, -halfDepth + 0.4);
  nave.add(roseEye);

  const roseFrame = new Mesh(
    new RingGeometry(roseRadius, roseRadius + 0.9, 48),
    materials.limestone,
  );
  roseFrame.position.set(0, roseY, -halfDepth + 0.34);
  nave.add(roseFrame);

  // The triple lancet below the rose, and the altar in front of it.
  // Three lancets under the rose, each with a real arch head. A rectangle here reads as a
  // poster taped to the wall, which is exactly what the first blockout looked like.
  for (let light = -1; light <= 1; light += 1) {
    const lancetHalf = 0.95;
    const lancetShape = new Shape();
    lancetShape.moveTo(-lancetHalf, 0);
    lancetShape.lineTo(-lancetHalf, 6);
    lancetShape.absarc(lancetHalf, 6, 2 * lancetHalf, Math.PI, (Math.PI * 2) / 3, true);
    lancetShape.absarc(-lancetHalf, 6, 2 * lancetHalf, Math.PI / 3, 0, true);
    lancetShape.lineTo(lancetHalf, 0);
    lancetShape.closePath();
    const lancet = new Mesh(
      new ExtrudeGeometry(lancetShape, { depth: 0.1, bevelEnabled: false }),
      glass(light === 0 ? palette.glassWarm : palette.glassRose),
    );
    // The centre light is taller, which is what stops three equal windows reading as a
    // fence and makes the group point at the rose above it.
    lancet.scale.y = light === 0 ? 1.18 : 1;
    lancet.position.set(light * 2.5, arcadeHeight * 0.42, -halfDepth + 0.12);
    nave.add(lancet);

    const mullionBar = new Mesh(new BoxGeometry(0.22, 7.4, 0.22), materials.limestone);
    mullionBar.position.set(light * 2.5, arcadeHeight * 0.42 + 3.4, -halfDepth + 0.3);
    nave.add(mullionBar);
  }

  const steps = new Mesh(new BoxGeometry(width * 0.7, 0.45, 4), materials.marbleBand);
  steps.position.set(0, 0.22, -halfDepth + 7);
  steps.castShadow = true;
  steps.receiveShadow = true;
  nave.add(steps);

  const altar = new Mesh(new BoxGeometry(4, 1.3, 1.8), materials.limestone);
  altar.position.set(0, 1.1, -halfDepth + 5);
  altar.castShadow = true;
  altar.receiveShadow = true;
  nave.add(altar);

  // The chancel screen: near-black vertical bars, read as silhouette against the lit apse.
  for (let bar = -8; bar <= 8; bar += 1) {
    const rail = new Mesh(new BoxGeometry(0.14, 3.2, 0.14), materials.iron);
    rail.position.set(bar * 0.62, 1.6, -halfDepth + 9);
    rail.castShadow = true;
    nave.add(rail);
  }

  // The west wall, behind the camera. Off screen, and it still matters: it is the surface
  // bouncing light back down the nave that screen-space GI can never sample — the gap
  // PRD-268's probe volume exists to close.
  const westWall = new Mesh(new PlaneGeometry(width + aisleWidth * 2, height), materials.shadowStone);
  westWall.position.set(0, height / 2, halfDepth);
  westWall.material.side = DoubleSide;
  nave.add(westWall);

  return nave;
}
