// Generated by nobody: this is ordinary Three.js and ThreeNative does not read it.
//
// A hanging cloth that moves.
//
// The banners were already the right shape — `furnishings.ts` builds each one as a 17 x 23
// grid with a hand-authored bow, fold and swallowtail, and the comment above that code is
// right that the bow is what kills the cardboard read. What they were not was *alive*: four
// dead cloths in a building where every candle flickers.
//
// So this simulates the grid the authored code already produced, rather than replacing it
// with a sim's own idea of a drape. The distinction is the whole design:
//
//   The rest lengths are measured from the authored surface. A bowed, gathered, tailed
//   cloth has edges longer than the flat distance between its corners, so the authored
//   silhouette is *encoded in the constraint set*. Solve those constraints and the cloth
//   relaxes back toward the shape somebody chose, not toward a flat sheet. A sim seeded
//   with flat rest lengths hangs like a towel — which is exactly the read the authored
//   displacements existed to defeat.
//
// Verlet, not springs-and-forces: position-based integration is unconditionally stable at
// the step sizes a game loop actually delivers, and an explicit spring solver at this
// stiffness is not. It is also plain arithmetic over a Float32Array, which means it runs on
// native as-is — no browser global, no compute pass, no WebGPU-only node graph.
//
// Determinism is a requirement here, not a nicety. Two captures of the same build at the
// same frame time have to differ by the stage under test and nothing else, so the wind is a
// closed-form function of elapsed time — three sines with irrational-ish ratios so the
// pattern does not visibly repeat — and there is no `Math.random` anywhere in the file.

import { type BufferAttribute, type BufferGeometry, Vector3 } from "three";

export interface IClothOptions {
  /** Columns of vertices. Must match the geometry the caller built. */
  readonly across: number;
  /** Rows of vertices. Must match the geometry the caller built. */
  readonly down: number;
  /**
   * How hard the draft pushes, in metres per second squared.
   *
   * A cathedral is not a hillside, but the first guess was too timid to see: at 0.6 the
   * measured hem travel was 5 mm, which at nave distance is nothing. 2.2 puts it around
   * three centimetres — cloth that is visibly alive without becoming a flag, which would be
   * a different building.
   */
  readonly wind?: number;
  /** Downward acceleration. The authored drape already hangs, so this only adds weight. */
  readonly gravity?: number;
  /** Velocity retained per second. Lower is heavier cloth; damask is not silk. */
  readonly damping?: number;
  /** Constraint relaxation passes. Three is enough for a grid this size. */
  readonly iterations?: number;
  /**
   * Pull back toward the authored position, per second.
   *
   * Distance constraints alone do not pin a *shape*: a grid can fold to a completely
   * different surface while satisfying every edge length. This is the term that guarantees
   * the cloth still looks like the one the render lane authored an hour of taste into, and
   * it is why the banner does not slowly wander into a shape nobody chose.
   */
  readonly memory?: number;
  /** Shifts this cloth's wind phase so four banners do not breathe in unison. */
  readonly phase?: number;
}

interface IConstraint {
  readonly a: number;
  readonly b: number;
  readonly rest: number;
}

const scratch = new Vector3();

/**
 * One simulated banner, driven in place on the geometry the caller already built.
 *
 * The geometry's own `position` attribute is the live state — there is no second copy of
 * the cloth to keep in step with it, and `step` writes the attribute and marks it dirty.
 * The caller keeps the `Mesh`; this class never touches materials, colour or visibility.
 */
export class ClothSheet {
  readonly #geometry: BufferGeometry;
  readonly #position: BufferAttribute;
  readonly #across: number;
  readonly #down: number;
  /** Where each vertex was authored. Also the target of the memory term. */
  readonly #rest: Float32Array;
  /** Verlet's second state vector: where each vertex was one step ago. */
  readonly #previous: Float32Array;
  readonly #constraints: readonly IConstraint[];
  readonly #wind: number;
  readonly #gravity: number;
  readonly #damping: number;
  readonly #iterations: number;
  readonly #memory: number;
  readonly #phase: number;
  #elapsed = 0;
  #excursion = 0;

  constructor(geometry: BufferGeometry, options: IClothOptions) {
    const position = geometry.getAttribute("position") as BufferAttribute | undefined;
    // Fail closed. A cloth whose grid does not match its geometry produces a plausible
    // animation over the wrong vertices, which is far harder to spot than a throw.
    if (position === undefined) throw new Error("ClothSheet: geometry has no position attribute");
    const expected = (options.across + 1) * (options.down + 1);
    if (position.count !== expected) {
      throw new Error(
        `ClothSheet: geometry has ${position.count} vertices, but across=${options.across} down=${options.down} needs ${expected}`,
      );
    }

    this.#geometry = geometry;
    this.#position = position;
    this.#across = options.across;
    this.#down = options.down;
    this.#wind = options.wind ?? 2.2;
    this.#gravity = options.gravity ?? 1.4;
    this.#damping = options.damping ?? 0.86;
    this.#iterations = options.iterations ?? 3;
    this.#memory = options.memory ?? 1.5;
    this.#phase = options.phase ?? 0;

    this.#rest = new Float32Array(position.array as Float32Array);
    this.#previous = new Float32Array(position.array as Float32Array);
    this.#constraints = this.#buildConstraints();
  }

  /** Vertices across x rows down, for a caller that wants to report the cost. */
  get particles(): number {
    return (this.#across + 1) * (this.#down + 1);
  }

  get constraintCount(): number {
    return this.#constraints.length;
  }

  /**
   * How far the hem has travelled from where it was authored, in metres.
   *
   * The observable that makes this provable. A screenshot cannot tell a simulated banner in
   * still air from a static one, and "the sim is wired up" is exactly the claim that is
   * worth nothing unasserted — a `stepCloth` nobody calls produces four dead cloths and no
   * error. A playtest reads this and fails when the number stops changing.
   */
  get excursion(): number {
    return this.#excursion;
  }

  /**
   * Advance one fixed step.
   *
   * `dt` is clamped rather than trusted: a tab that was backgrounded delivers a step of
   * several seconds, and Verlet integrating that in one go throws the cloth off the pole
   * and never recovers it.
   */
  step(dt: number): void {
    const step = Math.min(Math.max(dt, 1 / 240), 1 / 30);
    this.#elapsed += step;

    const positions = this.#position.array as Float32Array;
    const previous = this.#previous;
    const rest = this.#rest;
    const columns = this.#across + 1;
    // Retain-per-second raised to the step, so the feel does not change with frame rate.
    const retain = this.#damping ** step;
    const gravity = -this.#gravity * step * step;
    const memory = Math.min(1, this.#memory * step);

    for (let row = 0; row <= this.#down; row += 1) {
      // The top row is the pole. It never moves, and the ramp below it is what makes the
      // cloth pivot from the rings rather than swinging as a rigid slab.
      const pinned = row === 0;
      // 0 at the pole, 1 at the hem. The draft has more purchase on cloth that is free.
      const reach = row / this.#down;
      for (let column = 0; column < columns; column += 1) {
        const index = (row * columns + column) * 3;
        if (pinned) {
          positions[index] = rest[index] as number;
          positions[index + 1] = rest[index + 1] as number;
          positions[index + 2] = rest[index + 2] as number;
          previous[index] = positions[index] as number;
          previous[index + 1] = positions[index + 1] as number;
          previous[index + 2] = positions[index + 2] as number;
          continue;
        }

        const gust = this.#draft(reach, column / this.#across) * step * step;
        for (let axis = 0; axis < 3; axis += 1) {
          const at = index + axis;
          const current = positions[at] as number;
          const velocity = (current - (previous[at] as number)) * retain;
          // Verlet: next = current + damped velocity + acceleration. The memory term is
          // applied as a position correction rather than a force, which keeps it stable at
          // any stiffness — a spring stiff enough to hold this shape would not be.
          const accel = axis === 1 ? gravity : axis === 2 ? gust : gust * 0.35;
          let next = current + velocity + accel;
          next += ((rest[at] as number) - next) * memory;
          previous[at] = current;
          positions[at] = next;
        }
      }
    }

    for (let pass = 0; pass < this.#iterations; pass += 1) this.#relax();

    this.#excursion = this.#measureHem();
    this.#position.needsUpdate = true;
    // The lighting is the entire reason this file exists: a moving cloth whose normals are
    // stale is a flat cloth that changes silhouette, which looks worse than not moving.
    this.#geometry.computeVertexNormals();
  }

  /** Largest distance from rest along the bottom row, which is where the travel is. */
  #measureHem(): number {
    const positions = this.#position.array as Float32Array;
    const rest = this.#rest;
    const columns = this.#across + 1;
    let worst = 0;
    for (let column = 0; column < columns; column += 1) {
      const index = (this.#down * columns + column) * 3;
      const dx = (positions[index] as number) - (rest[index] as number);
      const dy = (positions[index + 1] as number) - (rest[index + 1] as number);
      const dz = (positions[index + 2] as number) - (rest[index + 2] as number);
      worst = Math.max(worst, dx * dx + dy * dy + dz * dz);
    }
    return Math.sqrt(worst);
  }

  /**
   * The draft, as a closed form in elapsed time.
   *
   * Three sines rather than one. A single sine is a metronome and the eye finds it in about
   * two seconds; three at ratios that do not divide each other never visibly repeat while
   * staying perfectly reproducible from the clock alone.
   */
  #draft(reach: number, across: number): number {
    const t = this.#elapsed;
    const p = this.#phase;
    const swell =
      Math.sin(t * 0.41 + p) * 0.6 +
      Math.sin(t * 0.97 + p * 1.7) * 0.28 +
      Math.sin(t * 2.13 + across * 2.4 + p) * 0.12;
    // Squared reach, not linear: cloth held at the top barely moves a hand's width down,
    // and the hem does nearly all the travelling.
    return swell * this.#wind * reach * reach;
  }

  /**
   * One relaxation pass over the constraint set.
   *
   * Both ends of every edge move by half the error, except at the pole where the pinned end
   * takes none of it — a constraint that drags the top row down is a banner that slides off
   * its own rings over a few hundred frames.
   */
  #relax(): void {
    const positions = this.#position.array as Float32Array;
    const columns = this.#across + 1;
    for (const constraint of this.#constraints) {
      const a = constraint.a * 3;
      const b = constraint.b * 3;
      scratch.set(
        (positions[b] as number) - (positions[a] as number),
        (positions[b + 1] as number) - (positions[a + 1] as number),
        (positions[b + 2] as number) - (positions[a + 2] as number),
      );
      const length = scratch.length();
      if (length < 1e-6) continue;
      const correction = (length - constraint.rest) / length / 2;
      const aPinned = constraint.a < columns;
      const bPinned = constraint.b < columns;
      if (aPinned && bPinned) continue;
      const aShare = aPinned ? 0 : bPinned ? 2 : 1;
      const bShare = bPinned ? 0 : aPinned ? 2 : 1;
      for (let axis = 0; axis < 3; axis += 1) {
        const delta = scratch.getComponent(axis) * correction;
        positions[a + axis] = (positions[a + axis] as number) + delta * aShare;
        positions[b + axis] = (positions[b + axis] as number) - delta * bShare;
      }
    }
  }

  /**
   * Structural, shear and bend edges, with every rest length measured off the authored
   * surface rather than assumed uniform.
   *
   * Bend edges — the skip-one pairs — are what stop the sheet creasing into a fan of sharp
   * folds under the draft. Without them a grid this coarse buckles, and a buckled banner
   * reads as a crumpled poster.
   */
  #buildConstraints(): readonly IConstraint[] {
    const constraints: IConstraint[] = [];
    const columns = this.#across + 1;
    const add = (a: number, b: number): void => {
      constraints.push({ a, b, rest: this.#restDistance(a, b) });
    };
    for (let row = 0; row <= this.#down; row += 1) {
      for (let column = 0; column < columns; column += 1) {
        const here = row * columns + column;
        const right = column + 1 < columns;
        const below = row + 1 <= this.#down;
        if (right) add(here, here + 1);
        if (below) add(here, here + columns);
        if (right && below) {
          add(here, here + columns + 1);
          add(here + 1, here + columns);
        }
        if (column + 2 < columns) add(here, here + 2);
        if (row + 2 <= this.#down) add(here, here + columns * 2);
      }
    }
    return constraints;
  }

  #restDistance(a: number, b: number): number {
    const rest = this.#rest;
    const dx = (rest[b * 3] as number) - (rest[a * 3] as number);
    const dy = (rest[b * 3 + 1] as number) - (rest[a * 3 + 1] as number);
    const dz = (rest[b * 3 + 2] as number) - (rest[a * 3 + 2] as number);
    return Math.sqrt(dx * dx + dy * dy + dz * dz);
  }
}
