// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// Everything inside the building that is not the building: chandeliers, candle stands,
// pews, statues, banners, the chancel fittings. Owned by the interior-details lane.
//
// Contract with `cathedral.ts`: this file adds objects *inside* the nave volume described
// by `NAVE` and never edits the shell. Anything emissive placed here is a light source the
// screen-space GI pass will gather from, so keep the count of genuinely bright objects
// low and deliberate.
//
// The lighting budget is the design constraint, not a detail of it. Every flame in the
// reference is a candle, and there are roughly two hundred of them; two hundred
// `PointLight`s is two hundred forward-shading iterations per fragment and a scene that
// no longer runs. Instead each flame is an *emissive material above the tonemap ceiling*:
// bloom spreads it and the SSGI pass gathers it off the beauty buffer, so the flames pay
// for themselves as light without ever entering the light loop. Exactly two real point
// lights survive, and each says below why it could not be an emissive quad.
//
// The second constraint is draw calls. Every repeated part — chain link, candle, wax,
// flame, railing bar, spoke, finial — goes into one shared `InstancedMesh` per
// material+geometry pair rather than one per object, so the entire furnishing set costs
// roughly twenty draws no matter how many candles are lit. The batches are declared once
// at the bottom of `createFurnishings` and every builder below writes into them.
import {
  AdditiveBlending,
  BoxGeometry,
  BufferAttribute,
  BufferGeometry,
  Color,
  ConeGeometry,
  CubeTexture,
  CylinderGeometry,
  DataTexture,
  DoubleSide,
  Group,
  InstancedMesh,
  LatheGeometry,
  LinearFilter,
  LinearMipmapLinearFilter,
  type Material,
  Matrix4,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  Object3D,
  PlaneGeometry,
  PointLight,
  Quaternion,
  SphereGeometry,
  SRGBColorSpace,
  TorusGeometry,
  Vector2,
  Vector3,
} from "three";
import { softCircleDataTexture } from "@threenative/core";
import { ClothSheet } from "./cloth.js";
import { NAVE } from "./lighting.js";

// ---------------------------------------------------------------------------------------
// the room the metal reflects
// ---------------------------------------------------------------------------------------
//
// Metal in a PBR renderer has no diffuse term at all: a `metalness: 1` surface is nothing
// but a mirror tinted by its albedo, so with nothing to reflect it renders black, and the
// usual escape — dialling metalness down to a middling 0.3 and adding emissive — is the
// definition of plastic. That is what the first eight captures had on the chandeliers: a
// flat mid-brown ring with no bright edge anywhere on it.
//
// `scene.environment` would be the right home for this, but this function is handed no
// scene — it returns a `Group`. `NodeMaterial.setupEnvironment` reads `material.envMap`
// per material on the WebGPU path, which reaches the same shading with the same cube and
// touches nothing outside this file.
//
// The cube is generated rather than loaded: no DOM, no canvas, no asset, so it works on
// the native target too. It is not a picture of this building — it is the three things a
// chandelier in this building actually reflects, and nothing else:
//
//   a bright warm band at clerestory height on the -X side   the sun-side windows
//   a dimmer band opposite                                   the shaded windows
//   a warm floor below and a near-black vault above          the room
//
// The bands are what make the rim read. A smooth gradient models the form but gives no
// glint; a *band* is a light source with an edge, and an edge is what a low-roughness
// surface turns into a highlight that slides along the ring as it curves.
function metalEnvironment(): CubeTexture {
  const size = 64;
  const faces: DataTexture[] = [];
  for (let face = 0; face < 6; face += 1) {
    const data = new Uint8Array(size * size * 4);
    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size; x += 1) {
        const u = (2 * (x + 0.5)) / size - 1;
        const v = (2 * (y + 0.5)) / size - 1;
        // Standard cube face orientation: +X, -X, +Y, -Y, +Z, -Z.
        const axis: [number, number, number] =
          face === 0
            ? [1, -v, -u]
            : face === 1
              ? [-1, -v, u]
              : face === 2
                ? [u, 1, v]
                : face === 3
                  ? [u, -1, -v]
                  : face === 4
                    ? [u, -v, 1]
                    : [-u, -v, -1];
        const length = Math.hypot(axis[0], axis[1], axis[2]);
        const dx = axis[0] / length;
        const up = axis[1] / length;

        // Vault above, lit pavement below, meeting at the horizon.
        const t = Math.abs(up) ** 0.6;
        const near: [number, number, number] = up > 0 ? [0.05, 0.047, 0.045] : [0.2, 0.15, 0.105];
        let r = 0.105 * (1 - t) + near[0] * t;
        let g = 0.09 * (1 - t) + near[1] * t;
        let b = 0.075 * (1 - t) + near[2] * t;

        // The two window bands. `height` is a narrow lobe around clerestory level and
        // `side` picks the sunlit colonnade; their product is a patch, not a stripe
        // wrapped all the way round, which is what a real window is.
        const height = Math.exp(-(((up - 0.4) / 0.2) ** 2));
        const sunSide = Math.max(0, -dx) ** 1.5;
        const shadeSide = Math.max(0, dx) ** 2;
        const glare = height * (sunSide * 1.5 + shadeSide * 0.28);
        r = Math.min(1, r + glare);
        g = Math.min(1, g + glare * 0.72);
        b = Math.min(1, b + glare * 0.44);

        const index = (y * size + x) * 4;
        data[index] = Math.round(r * 255);
        data[index + 1] = Math.round(g * 255);
        data[index + 2] = Math.round(b * 255);
        data[index + 3] = 255;
      }
    }
    const facing = new DataTexture(data, size, size);
    facing.needsUpdate = true;
    faces.push(facing);
  }
  const cube = new CubeTexture(faces);
  cube.colorSpace = SRGBColorSpace;
  // Without mips a rough metal samples the sharpest level of the cube and the dull iron
  // gets the same crisp window edge as the polished bronze, which flattens the difference
  // between the two materials back out again.
  cube.generateMipmaps = true;
  cube.minFilter = LinearMipmapLinearFilter;
  cube.magFilter = LinearFilter;
  cube.needsUpdate = true;
  return cube;
}

const metalEnv = metalEnvironment();

// ---------------------------------------------------------------------------------------
// materials
// ---------------------------------------------------------------------------------------
//
// Metalness is binary. Every metal below is 1 with a dark albedo — a metal's albedo *is*
// its reflection tint, so a light brown at metalness 1 gives a washed-out non-colour — and
// every non-metal is 0. Nothing metal carries an emissive term: emissive on a mirror is
// a constant added on top of the reflection and it is exactly what kills the highlight.
const materials = {
  /** The screens and the candle stands. Old wrought iron: near-black, and dull. */
  iron: new MeshStandardMaterial({
    color: 0x1a1712,
    // 0.62, not 0.55. With MSAA off, the 6 mm top edge of a candelabrum crossbar at three
    // metres turned its specular into a dotted line — one lit texel every few pixels. The
    // extra roughness spreads that highlight over enough of the edge to stay continuous,
    // and duller iron next to polished bronze is the right reading anyway.
    roughness: 0.62,
    metalness: 1,
    envMap: metalEnv,
    envMapIntensity: 0.95,
  }),
  /**
   * The chandelier corona and the candle cups. Polished bronze — low roughness, so the rim
   * of a wheel carries a moving highlight where it turns toward the windows and goes dark
   * where it turns away. That highlight is most of what makes it read as metal at all;
   * the warmth comes from the flames standing on it, not from the albedo.
   *
   * Not lower than 0.3: the scene runs without MSAA and a mirror-smooth 2 cm rod at this
   * distance is a specular aliasing generator.
   */
  bronze: new MeshStandardMaterial({
    color: 0x6b4a24,
    roughness: 0.32,
    metalness: 1,
    envMap: metalEnv,
    envMapIntensity: 1.15,
  }),
  /** Heraldic gold on the banners and the altar. The one bright metal in the building. */
  gold: new MeshStandardMaterial({
    color: 0x9a7326,
    roughness: 0.3,
    metalness: 1,
    envMap: metalEnv,
    envMapIntensity: 1.2,
  }),
  /** Candle wax. Warm-lit from its own flame, so it carries a little emissive of its own. */
  wax: new MeshStandardMaterial({
    color: 0xd9cdb2,
    roughness: 0.75,
    metalness: 0,
    emissive: 0x3a2610,
  }),
  /** Statues, plinths, memorial panels, the reredos. One shade off the building's stone. */
  carvedStone: new MeshStandardMaterial({ color: 0x6d6558, roughness: 0.9, metalness: 0 }),
  /** The altar linen: the only near-white cloth in the building, and it reads as the focus. */
  linen: new MeshStandardMaterial({ color: 0xbdb49c, roughness: 0.85, metalness: 0 }),
  /**
   * Banner cloth. Deep and unsaturated — the glass owns the colour in this room.
   *
   * The `emissive` floor this used to carry is gone. It was propping up a flat slab whose
   * single normal faced away from every light in the building; the cloth now bows, so its
   * normals sweep through the light and it holds its own shape. Propping a surface that
   * can light itself only flattens it again.
   *
   * `DoubleSide` stays, and the bow is why: at the grazing angles this is seen from, the
   * far half of the curve turns its back to the camera.
   */
  banner: new MeshStandardMaterial({
    // 0x232d54 is a contract, not a preference. `surfaces.ts` finds the banner cloth by
    // matching this exact hex — it has no other handle on it — and then drives the heraldic
    // map's gain from `luminance(color) / BANNER_CLOTH_LUMINANCE`. Re-tint the cloth here
    // and the banners silently stop being dressed at all, which is what four captures of a
    // flat undressed slab were. Change the tint by changing both files together.
    color: 0x232d54,
    roughness: 0.88,
    metalness: 0,
    // Restored deliberately after being removed. `surfaces.ts` documents depending on it:
    // emissive is added after lighting and its `colorNode` does not reach it, so it is what
    // keeps a navy cloth on an *unlit* pier from rounding to black. Two of the four banners
    // hang on faces the sun never touches.
    emissive: 0x0a0f22,
    side: DoubleSide,
  }),
  /** The sanctuary runner. Muted, so it warms the steps without competing with the rose. */
  carpet: new MeshStandardMaterial({ color: 0x51201d, roughness: 0.9, metalness: 0 }),
  /**
   * A flame.
   *
   * `toneMapped: false` and a colour authored far *past* 1.0. The bloom stage thresholds
   * at 0.2 but its strength is only 0.18, so the halo a flame throws is proportional to how
   * far over the threshold it sits, not to how big the mesh is. The first capture used 2.6
   * and the candles rendered as white sticks with no light on them at all.
   */
  flame: new MeshBasicMaterial({ color: new Color().setRGB(5.5, 2.7, 0.95), toneMapped: false }),
  /**
   * The halo around a flame.
   *
   * Additive, depth-writing off, and much larger than the flame itself. Bloom alone cannot
   * do this job here: `bloomStrength` is 0.18 because the stained glass is already past the
   * tonemap ceiling and a stronger bloom lifts the whole frame. The halo is a local,
   * per-candle version of the same effect that costs one draw call for every candle in the
   * building and nothing in the post chain.
   *
   * It was an eight-segment sphere until a close capture of the chancel ring showed what
   * the comment above it had been predicting all along: an additive solid with a constant
   * colour has a hard silhouette, so twelve of them read as twelve octagonal discs with
   * candles inside. A glow has no edge. `softCircleDataTexture` is the framework's answer
   * to exactly this — a radial alpha falloff written as pixel data rather than painted on a
   * canvas, because a canvas-drawn image samples black under `WebGPURenderer`. Paired with
   * the camera-facing quad the animator writes, the disc becomes a glow.
   */
  halo: new MeshBasicMaterial({
    color: new Color().setRGB(0.42, 0.185, 0.058),
    map: softCircleDataTexture(64, 0.32),
    blending: AdditiveBlending,
    depthWrite: false,
    toneMapped: false,
    transparent: true,
  }),
};

// ---------------------------------------------------------------------------------------
// instancing
// ---------------------------------------------------------------------------------------

/** Accumulates transforms for one geometry+material pair, then becomes one draw call. */
interface IBatch {
  readonly add: (matrix: Matrix4) => void;
}

interface IBuiltBatch extends IBatch {
  readonly build: (parent: Group, name: string, castShadow: boolean) => InstancedMesh | undefined;
}

function batch(geometry: BufferGeometry, material: Material): IBuiltBatch {
  const matrices: Matrix4[] = [];
  return {
    add: (matrix: Matrix4): void => {
      matrices.push(matrix.clone());
    },
    build: (parent: Group, name: string, castShadow: boolean): InstancedMesh | undefined => {
      if (matrices.length === 0) return undefined;
      const mesh = new InstancedMesh(geometry, material, matrices.length);
      mesh.name = name;
      for (let index = 0; index < matrices.length; index += 1) {
        mesh.setMatrixAt(index, matrices[index] as Matrix4);
      }
      mesh.instanceMatrix.needsUpdate = true;
      // Candles and chain links are sub-texel in a 4096 map spanning 92 metres; asking the
      // shadow pass to rasterise them buys nothing and costs a second full instanced draw.
      mesh.castShadow = castShadow;
      mesh.receiveShadow = castShadow;
      mesh.computeBoundingSphere();
      parent.add(mesh);
      return mesh;
    },
  };
}

const dummy = new Object3D();
/** The camera orientation every halo quad copies. Read once a frame, not once a flame. */
const haloFacing = new Quaternion();
const UP = new Vector3(0, 1, 0);
const rodDirection = new Vector3();
const rodMidpoint = new Vector3();
const rodRotation = new Quaternion();

/** Place one instance by position, scale and Euler rotation. */
function place(
  target: IBatch,
  position: [number, number, number],
  scale: [number, number, number],
  rotation: [number, number, number] = [0, 0, 0],
): void {
  dummy.position.set(position[0], position[1], position[2]);
  dummy.rotation.set(rotation[0], rotation[1], rotation[2]);
  dummy.scale.set(scale[0], scale[1], scale[2]);
  dummy.updateMatrix();
  target.add(dummy.matrix);
}

/**
 * Place a unit cylinder as a rod spanning two points.
 *
 * Chains, tie rods and railing bars are all "from A to B" rather than "at P with rotation
 * R"; deriving the quaternion here keeps every caller from hand-computing an Euler angle
 * that is wrong the moment a position moves by a metre.
 */
function rod(
  target: IBatch,
  from: [number, number, number],
  to: [number, number, number],
  radius: number,
): void {
  rodDirection.set(to[0] - from[0], to[1] - from[1], to[2] - from[2]);
  const length = rodDirection.length();
  if (length < 1e-5) return;
  rodDirection.divideScalar(length);
  rodRotation.setFromUnitVectors(UP, rodDirection);
  rodMidpoint.set((from[0] + to[0]) / 2, (from[1] + to[1]) / 2, (from[2] + to[2]) / 2);
  dummy.position.copy(rodMidpoint);
  dummy.quaternion.copy(rodRotation);
  dummy.scale.set(radius, length, radius);
  dummy.updateMatrix();
  dummy.rotation.set(0, 0, 0);
  target.add(dummy.matrix);
}

// ---------------------------------------------------------------------------------------
// layout, derived from the bay so nothing drifts when the nave is resized
// ---------------------------------------------------------------------------------------
const BAYS = Math.floor(NAVE.depth / NAVE.bayPitch);
const HALF_DEPTH = (BAYS * NAVE.bayPitch) / 2;
/** Centre of the pier standing proud of the arcade, matching `createCathedral`. */
const PIER_X = NAVE.width / 2 - NAVE.pierRadius * 0.7;
/** Face of the outer aisle wall. */
const AISLE_WALL_X = NAVE.width / 2 + NAVE.aisleWidth;
/** The chancel screen line `createCathedral` already builds bars on. */
/**
 * The east end, mirrored from `createCathedral`.
 *
 * These five numbers are the shell's, not this file's: the chancel arch springs two bays
 * short of the east wall, the sanctuary floor is a raised platform, and the screen stands
 * on it. They are duplicated here rather than imported because `cathedral.ts` exports one
 * function and nothing else — which makes them the one thing in this file that can go
 * silently stale. When the altar moves over there, these move here, and the symptom is an
 * altar set floating a metre below a platform it should be standing on.
 */
const CHANCEL_Z = -HALF_DEPTH + NAVE.bayPitch * 2;
/** Top of the raised sanctuary platform: everything in the chancel stands on this. */
const CHANCEL_Y = 1.08;
const SCREEN_Z = CHANCEL_Z - 0.8;
const ALTAR_Z = CHANCEL_Z - 6.5;
/** Half-width of the platform. Outside this the chancel fittings stand on the nave floor. */
const CHANCEL_HALF_WIDTH = 5.8;
/**
 * Where a banner hangs, and it is *not* `PIER_X`.
 *
 * Centring a two-metre cloth on the pier axis buries its outer half in the arcade wall,
 * whose nave face is around 7.5. Every banner rendered as a one-metre sliver with the gold
 * device floating over a lit pier beside it — which is most of why they read as a flat
 * pale slab. 6.4 puts the whole width in open air: the outer edge clears the wall, the
 * inner edge sits just proud of the vault shafts the pier stands into the nave.
 */
const BANNER_X = NAVE.width / 2 - 1.6;

/**
 * A stand this file deliberately does not build.
 *
 * The same idiom as the statue bays: `createFurnishings` leaves the slot empty and `Play`
 * — which is where the loaded glTF actually lives — stands the imported model in it. The
 * coordinates are here rather than there so that the stands that *are* procedural and the
 * stands that are not stay laid out in one file; a spacing decision split across two files
 * drifts on the first move.
 */
export interface IAuthoredStand {
  /** Which model goes here. `Play` maps these names to the loaded glTF. */
  readonly model: "candela" | "vigil";
  readonly x: number;
  readonly z: number;
  /** Overall height of the finished piece in metres, candles included. */
  readonly height: number;
  /** Rotation about Y. A branched bar seen end-on collapses to a single candle. */
  readonly yaw: number;
  /** Flame size multiplier, passed through to `IFlamePlacement.size`. */
  readonly flame: number;
}

/**
 * Where the imported stands go, and why each one is where it is.
 *
 * These are placed against the *camera*, not against the architecture. The view sits at
 * x 2.6 with a 63° lens, which leaves the near frustum about ten metres wide at the first
 * pier row: a stand out at the pier line is entirely off the left edge. The two nave pieces
 * stand in from the colonnade so their flames land in the near corners of the frame, three
 * and eight metres from the lens — a candle is a known size, so a lit cluster this close is
 * what tells the eye the piers behind it are fifteen metres tall.
 */
export const AUTHORED_STANDS: readonly IAuthoredStand[] = [
  // The foreground stand, on the polished marble that fills the bottom third of the frame.
  // `standLight` below sits at this x and z; move one and move the other.
  { model: "vigil", x: -1.3, z: 17.6, height: 3.75, yaw: 0.55, flame: 0.62 },
  // The right of the nave, held in toward the axis: the nearest pier on that side fills the
  // right quarter of the frame and anything behind it at x > 6 disappears whole.
  { model: "vigil", x: 6.4, z: 14.5, height: 3.3, yaw: -0.5, flame: 0.7 },
  // Flanking the chancel steps, on the nave floor rather than the raised platform. The ring
  // stand goes here and not in the nave: twelve candles on a hoop read as a *hearse* seen
  // square on, and square on is the only way the axis ever sees the chancel.
  { model: "candela", x: -4.1, z: CHANCEL_Z + 4.4, height: 2.95, yaw: 0.15, flame: 1 },
  { model: "candela", x: 4.1, z: CHANCEL_Z + 4.4, height: 2.95, yaw: -0.15, flame: 1 },
];

// ---------------------------------------------------------------------------------------
// the pieces
// ---------------------------------------------------------------------------------------

/**
 * A wick the caller found for itself, in world coordinates.
 *
 * The authored glTF stands model their candles as carved wax with no fire on them. `Play`
 * measures where each taper ends with `wicks.ts` and passes the points to
 * `createFurnishings`, which lights them into the same two instanced draws as every
 * procedural candle in the building. Nothing here knows which stand a wick came from, and
 * that is the point: one flame system, one animator, one bloom budget.
 */
export interface IFlamePlacement {
  readonly x: number;
  readonly y: number;
  readonly z: number;
  /** Multiplies the default flame and halo size. */
  readonly size?: number;
}

/** One flame's animation state, recorded by `candle` and replayed by `animateFires`. */
interface IFire {
  readonly x: number;
  readonly y: number;
  readonly z: number;
  readonly sx: number;
  readonly sy: number;
  readonly sz: number;
  readonly hx: number;
  readonly hy: number;
  readonly hz: number;
  readonly phase: number;
  readonly speed: number;
}

/** Reset by `createFurnishings`; a scene rebuild must not inherit the last build's flames. */
let fires: IFire[] = [];

/** The simulated banners. Reset alongside `fires` for the same reason. */
let cloths: ClothSheet[] = [];

interface IKit {
  readonly bronzeRod: IBatch;
  readonly bronzeTaper: IBatch;
  readonly chainLink: IBatch;
  readonly flame: IBatch;
  readonly gold: IBatch;
  readonly halo: IBatch;
  readonly ironBox: IBatch;
  readonly ironRod: IBatch;
  readonly ironSpike: IBatch;
  readonly knop: IBatch;
  readonly ring: IBatch;
  readonly stoneBox: IBatch;
  readonly stoneHead: IBatch;
  readonly stoneSpike: IBatch;
  readonly robe: IBatch;
  readonly wax: IBatch;
}

/**
 * One lit candle: wax plus flame, with the flame sitting *on* the wick rather than
 * floating above it. Height varies per call because a rack of candles all burnt to the
 * same length reads as a comb, which is the single most artificial thing a candle rack
 * can do.
 */
function candle(kit: IKit, x: number, baseY: number, z: number, height: number, radius: number) {
  place(kit.wax, [x, baseY + height / 2, z], [radius, height, radius]);
  // On the wick, not above it. At 0.09 the flame floated a visible gap clear of the wax.
  lightWick(kit, x, baseY + height + 0.05, z);
}

/**
 * Put fire on a wick that already exists.
 *
 * Split out of `candle` because the authored glTF stands carry their own carved wax and
 * need only this half: `wicks.ts` measures where their tapers end and `Play` hands the
 * points here, so an authored candle and a procedural one are the same two instances in
 * the same two draw calls, flickering off the same animator. A second flame system for
 * the imported models would have been a second pair of draws and a second thing to keep
 * in step with the bloom threshold.
 *
 * `size` scales the whole fire, and it is not cosmetic: the authored stands are placed
 * against the *lens* rather than against the architecture, so the ones three metres from
 * the camera need a smaller flame than the nave-scale default or they read as torches.
 */
function lightWick(kit: IKit, x: number, tip: number, z: number, size = 1): void {
  // Deliberately larger than a real flame. A 15 mm flame 20 m down the nave is a third of a
  // pixel; at that size the tonemap averages it away with its neighbours and the candle
  // reads as an unlit white stick, which is exactly what the first capture showed.
  place(kit.flame, [x, tip, z], [0.05 * size, 0.11 * size, 0.05 * size]);
  // Kept barely wider than the flame. The halo is a sphere with a hard edge, not a soft
  // sprite, so it has two failure modes and both have been in a capture: too large and two
  // of them merge into one lozenge with no candles inside it, and too large *near the
  // lens* and the edge itself becomes visible as a disc. It stays just big enough to soften
  // the flame and no bigger; the rest of the glow is bloom's job.
  place(kit.halo, [x, tip, z], [0.24 * size, 0.28 * size, 0.24 * size]);
  // Deterministic per-flame fire state for the animator below. The golden-angle phase
  // spread keeps neighbours out of step, and the speeds cluster around 1.3-2 Hz — candle
  // flicker, not strobe. Seeded from the placement index so two captures of the same
  // build at the same frame time differ by the stage under test and nothing else.
  fires.push({
    x,
    y: tip,
    z,
    sx: 0.05 * size,
    sy: 0.11 * size,
    sz: 0.05 * size,
    hx: 0.3 * size,
    hy: 0.34 * size,
    hz: 0.3 * size,
    phase: (fires.length * 2.399963) % (Math.PI * 2),
    speed: 8 + ((fires.length * 7) % 5) * 1.1,
  });
}

/**
 * A hanging wheel chandelier: rim, spokes, corona tie-rods, a ring of candles, and a chain
 * running all the way to the vault springing.
 *
 * The chain is not decoration. In the reference the chandeliers read as *hanging* — the
 * eye follows a line up into darkness — and a wheel with no visible suspension reads as a
 * ring of candles parked in mid-air.
 */
function chandelier(
  kit: IKit,
  x: number,
  z: number,
  ringY: number,
  radius: number,
  arms: number,
): void {
  const hubTop = ringY + radius * 1.15;
  const chainTop = NAVE.clerestoryTop - 1;

  // Links every 0.34 m, each rotated 90° from the last. Two coplanar links read as a
  // dashed line; alternating them is what makes a chain read as a chain at 12 m.
  for (let y = hubTop + 0.35; y < chainTop; y += 0.34) {
    const upright = Math.round((y - hubTop) / 0.34) % 2 === 0;
    place(kit.chainLink, [x, y, z], [0.11, 0.11, 0.11], [0, upright ? 0 : Math.PI / 2, 0]);
  }

  // The rim, and a lighter inner ring. One ring alone reads as a hoop; the pair reads as a
  // wheel, which is the shape the reference's chandeliers are built on.
  place(kit.ring, [x, ringY, z], [radius, radius, radius], [-Math.PI / 2, 0, 0]);
  place(kit.ring, [x, ringY + 0.02, z], [radius * 0.5, radius * 0.5, radius * 0.5], [
    -Math.PI / 2,
    0,
    0,
  ]);
  rod(kit.bronzeRod, [x, ringY - 0.1, z], [x, hubTop + 0.35, z], 0.045);
  place(kit.knop, [x, ringY - 0.28, z], [0.14, 0.22, 0.14]);

  const spokes = 8;
  for (let index = 0; index < spokes; index += 1) {
    const angle = (index / spokes) * Math.PI * 2;
    const rim: [number, number, number] = [
      x + Math.cos(angle) * radius,
      ringY,
      z + Math.sin(angle) * radius,
    ];
    rod(kit.bronzeTaper, [x, ringY, z], rim, 0.036);
    // Tie rods from the hub down to the rim: the diagonal is what gives a corona its
    // cone-shaped silhouette instead of a flat disc seen edge-on from below.
    rod(kit.bronzeTaper, [x, hubTop, z], rim, 0.03);
  }

  for (let index = 0; index < arms; index += 1) {
    const angle = (index / arms) * Math.PI * 2 + 0.2;
    const cx = x + Math.cos(angle) * radius;
    const cz = z + Math.sin(angle) * radius;
    // Pan, then cup. A candle standing straight on the rim reads as a peg pushed into a
    // hoop; the pan is the disc that catches the wax and it is the part that says the ring
    // was made to hold candles.
    place(kit.bronzeRod, [cx, ringY + 0.03, cz], [0.155, 0.022, 0.155]);
    place(kit.bronzeRod, [cx, ringY + 0.09, cz], [0.085, 0.1, 0.085]);
    candle(kit, cx, ringY + 0.14, cz, 0.3 + ((index * 7) % 5) * 0.02, 0.05);
  }
}

/**
 * A branched floor candelabrum: foot, knopped shaft, crossbar, a row of tapers.
 *
 * `yaw` exists because a bar seen end-on collapses to a single candle. These stand beside
 * the piers where the view direction is oblique, so each is turned a little off the nave
 * axis to keep the row spread across the frame.
 */
function candelabrum(
  kit: IKit,
  x: number,
  z: number,
  height: number,
  count: number,
  yaw: number,
  baseY = 0,
): void {
  const top = baseY + height;
  // A stepped foot, not a ball. A squashed sphere on the floor reads as a boulder at the
  // base of the stand, which is what the fourth capture put under every one of them.
  place(kit.ironRod, [x, baseY + 0.04, z], [0.44, 0.08, 0.44]);
  place(kit.ironRod, [x, baseY + 0.14, z], [0.3, 0.12, 0.3]);
  place(kit.ironRod, [x, baseY + 0.24, z], [0.17, 0.1, 0.17]);
  rod(kit.ironRod, [x, baseY + 0.12, z], [x, top, z], 0.05);
  // Small. These are the only polished bronze on an otherwise dull iron stand, so at
  // 0.12 they stopped reading as knops on a shaft and started reading as brass balls
  // threaded onto a pole.
  place(kit.knop, [x, baseY + height * 0.42, z], [0.082, 0.1, 0.082]);
  place(kit.knop, [x, baseY + height * 0.74, z], [0.07, 0.086, 0.07]);

  const spacing = 0.27;
  const span = (count - 1) * spacing;
  const dx = Math.cos(yaw);
  const dz = Math.sin(yaw);
  rod(
    kit.ironRod,
    [x - (dx * span) / 2, top, z - (dz * span) / 2],
    [x + (dx * span) / 2, top, z + (dz * span) / 2],
    0.035,
  );
  for (let index = 0; index < count; index += 1) {
    const offset = -span / 2 + index * spacing;
    const cx = x + dx * offset;
    const cz = z + dz * offset;
    place(kit.bronzeRod, [cx, top + 0.02, cz], [0.135, 0.02, 0.135]);
    place(kit.bronzeRod, [cx, top + 0.07, cz], [0.075, 0.09, 0.075]);
    // The middle taper is the tallest and they fall away to the ends. A flat row of equal
    // candles reads as a barcode; the arc is what makes the group read as a candelabrum.
    const fall = Math.abs(index - (count - 1) / 2) / Math.max(1, (count - 1) / 2);
    // Plus a deterministic burn-down per position. Thin, because at three metres from the
    // lens a 43 mm taper is a white post: the near stand is the one place in the frame
    // where a candle is read as an object rather than as a point of light.
    const burn = ((index * 5) % 4) * 0.05;
    candle(kit, cx, top + 0.1, cz, 0.78 - fall * 0.24 - burn, 0.033);
  }
}

/**
 * A votive rack in an aisle: a low iron tray carrying rows of stubs burnt to different
 * lengths.
 *
 * This is the only warm thing in the aisles, and the aisles are the part of the frame the
 * GI pass is being judged on — a rack seen through an arcade opening puts a warm pool on a
 * surface that receives no direct sun at all.
 */
function votiveRack(kit: IKit, x: number, z: number, facing: number): void {
  const trayY = 0.78;
  const width = 1.5;
  const depth = 0.62;
  for (const sx of [-1, 1]) {
    for (const sz of [-1, 1]) {
      rod(
        kit.ironRod,
        [x + sx * (width / 2 - 0.1), 0, z + sz * (depth / 2 - 0.08)],
        [x + sx * (width / 2 - 0.1), trayY, z + sz * (depth / 2 - 0.08)],
        0.03,
      );
    }
  }
  place(kit.ironBox, [x, trayY, z], [width, 0.06, depth], [0, facing, 0]);
  place(kit.ironBox, [x, trayY + 0.11, z - depth / 2], [width, 0.16, 0.05], [0, facing, 0]);

  const rows = 3;
  const columns = 7;
  for (let row = 0; row < rows; row += 1) {
    for (let column = 0; column < columns; column += 1) {
      const cx = x + (column / (columns - 1) - 0.5) * (width - 0.2);
      const cz = z + (row / (rows - 1) - 0.5) * (depth - 0.18);
      // Burnt to unequal stubs. The variation is deterministic so two captures of the same
      // build differ by the stage under test and nothing else.
      const burn = ((row * 7 + column * 3) % 5) / 5;
      candle(kit, cx, trayY + 0.03, cz, 0.09 + burn * 0.17, 0.036);
    }
  }
}

/**
 * A run of iron railing between two points: balusters, two rails, a crest and finials.
 *
 * The reference's ironwork is read entirely as a black lattice against a lit apse, so the
 * bar pitch matters more than any other number here — too coarse and it reads as a fence,
 * too fine and it fills in solid and reads as a wall.
 */
function railing(
  kit: IKit,
  from: [number, number],
  to: [number, number],
  height: number,
  options: { readonly pitch?: number; readonly finials?: boolean; readonly baseY?: number } = {},
): void {
  const pitch = options.pitch ?? 0.42;
  const baseY = options.baseY ?? 0;
  const dx = to[0] - from[0];
  const dz = to[1] - from[1];
  const length = Math.hypot(dx, dz);
  if (length < 1e-4) return;
  const count = Math.max(2, Math.round(length / pitch));
  const yaw = Math.atan2(dx, dz);

  for (let index = 0; index <= count; index += 1) {
    const t = index / count;
    const bx = from[0] + dx * t;
    const bz = from[1] + dz * t;
    rod(kit.ironRod, [bx, baseY, bz], [bx, baseY + height, bz], 0.038);
    // A boss on every other bar, on the middle rail. Screen ironwork in the reference is
    // never a plain grid; one repeated ornament at the mid-rail is the cheapest thing that
    // reads as wrought rather than welded, and it costs no extra draw call.
    if (index % 2 === 0) {
      place(kit.knop, [bx, baseY + height * 0.62, bz], [0.09, 0.09, 0.09]);
    }
    if (options.finials === true && index % 3 === 0) {
      place(kit.ironSpike, [bx, baseY + height + 0.24, bz], [0.075, 0.34, 0.075]);
    }
  }
  for (const railY of [baseY + 0.14, baseY + height * 0.62, baseY + height - 0.06]) {
    place(kit.ironBox, [from[0] + dx / 2, railY, from[1] + dz / 2], [0.06, 0.09, length], [
      0,
      yaw,
      0,
    ]);
  }
}

/**
/**
 * The cloth of a banner, as a hanging surface rather than a flat outline.
 *
 * An `ExtrudeGeometry` of the outline is a slab: one normal over the whole face, a dead
 * straight edge against the pier, and a hem that sits in a plane. Nothing about that says
 * fabric, and no texture fixes it, because the tell is the silhouette. Three displacements
 * turn it into cloth, in descending order of what they buy:
 *
 *   bow    cloth hung on a pole stands away from the wall in the middle and returns to it
 *          at both edges. This alone kills the cardboard read: it gives the face a range
 *          of normals, so the light across it varies instead of being one flat value.
 *   folds  a low-frequency ripple that grows toward the hem and vanishes at the pole,
 *          which is what makes the bottom edge wave in plan rather than sit in a line.
 *   gather the cloth is narrower at the top, where the rings hold it bunched.
 *
 * `phase` shifts the fold pattern per banner. Four identical banners on four piers read as
 * wallpaper however good one of them is.
 */
const CLOTH = {
  halfWidth: 1.0,
  height: 4.85,
  /** Extra drop at the centre of the hem — the point that makes it a banner, not a towel. */
  tail: 0.55,
  bow: 0.26,
  fold: 0.11,
  /** Deliberately not a whole number: an integer count mirrors the two halves exactly. */
  folds: 3.5,
} as const;

/** Depth of the cloth surface at `u` across (0..1) and `v` down (0..1). */
function clothDepth(u: number, v: number, phase: number): number {
  // Ramped in over the top fifth: the rings hold the cloth flat where they grip it, and a
  // bow that starts at full amplitude under the pole reads as a bulge, not a hang.
  const grip = Math.min(1, v / 0.2);
  const bow = Math.sin(Math.PI * u) * CLOTH.bow * grip;
  const folds = Math.sin(u * Math.PI * CLOTH.folds + phase) * CLOTH.fold * v ** 1.6;
  return bow + folds;
}

/** The banner grid. Shared with `ClothSheet`, which throws if the two ever disagree. */
const CLOTH_ACROSS = 16;
const CLOTH_DOWN = 22;

function clothGeometry(phase: number): BufferGeometry {
  const across = CLOTH_ACROSS;
  const down = CLOTH_DOWN;
  const positions = new Float32Array((across + 1) * (down + 1) * 3);
  const indices: number[] = [];
  for (let row = 0; row <= down; row += 1) {
    const v = row / down;
    // Gathered at the pole, full width by a fifth of the way down.
    const halfWidth = CLOTH.halfWidth * (0.86 + 0.14 * Math.min(1, v * 5));
    for (let column = 0; column <= across; column += 1) {
      const u = column / across;
      const point = 1 - Math.abs(u * 2 - 1);
      const index = (row * (across + 1) + column) * 3;
      positions[index] = (u * 2 - 1) * halfWidth;
      // `v ** 3` keeps the tail local to the hem instead of skewing every row above it.
      positions[index + 1] = -(v * CLOTH.height + CLOTH.tail * point * v ** 3);
      positions[index + 2] = clothDepth(u, v, phase);
    }
  }
  for (let row = 0; row < down; row += 1) {
    for (let column = 0; column < across; column += 1) {
      const a = row * (across + 1) + column;
      const b = a + 1;
      const c = a + across + 1;
      const d = c + 1;
      indices.push(a, c, b, b, c, d);
    }
  }
  const geometry = new BufferGeometry();
  geometry.setAttribute("position", new BufferAttribute(positions, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();
  return geometry;
}

/**
 * A heraldic banner hanging from the west face of a pier.
 *
 * West face, not the nave face, and that is a lighting decision rather than a liturgical
 * one. The sun in this building travels +X and -Z, so it lights whatever faces -X or +Z;
 * a banner hung flat against the *side* of a pier faces +X and receives no direct light on
 * any part of it. Hung on the west face it faces the camera and the sun at once, which is
 * also how the reference's banners are seen — broadside, not edge-on.
 */
function banner(kit: IKit, parent: Group, x: number, z: number, topY: number, phase: number): void {
  const geometry = clothGeometry(phase);
  const cloth = new Mesh(geometry, materials.banner);
  cloth.position.set(x, topY, z);
  cloth.castShadow = true;
  parent.add(cloth);
  // The authored surface above is the sim's rest state, not a starting guess it will
  // wander away from: `ClothSheet` measures every rest length off these vertices, so the
  // bow, the gather and the swallowtail are encoded in the constraint set. With the draft
  // at zero the banner is pixel-identical to the static one this replaced.
  cloths.push(new ClothSheet(geometry, { across: CLOTH_ACROSS, down: CLOTH_DOWN, phase }));

  // The pole and its two suspension rings. Cloth that starts at a bare edge looks pasted
  // to the pier; the pole gives it something to hang from.
  rod(kit.bronzeRod, [x - 1.25, topY + 0.12, z + 0.1], [x + 1.25, topY + 0.12, z + 0.1], 0.05);
  for (const side of [-0.85, 0.85]) {
    place(kit.chainLink, [x + side, topY + 0.26, z + 0.1], [0.14, 0.14, 0.14]);
  }

  // No gold device here any more. `surfaces.ts` now dresses this cloth with a heraldic map
  // that carries the cross patty and the braid that follows the swallowtail hem; the five
  // gold boxes and the segmented bands that used to stand in for it drew straight over the
  // map's own device. `TN_SURFACES_BANNERS` in the console reports how many cloths were
  // dressed — if that count is 0, the tint contract above has been broken and the boxes
  // would be the only device there is.
}

/** A robed figure on a plinth, standing in an aisle bay. */
function statue(kit: IKit, x: number, z: number, facing: number): void {
  place(kit.stoneBox, [x, 0.75, z], [0.9, 1.5, 0.9]);
  place(kit.stoneBox, [x, 1.56, z], [1.05, 0.12, 1.05]);
  place(kit.robe, [x, 1.62, z], [1, 1, 1], [0, facing, 0]);
  place(kit.stoneHead, [x, 3.62, z], [0.15, 0.19, 0.15]);
}

/** A wall memorial: gabled stone panel with a gold inscription plate. */
function memorial(kit: IKit, x: number, z: number, facing: number): void {
  place(kit.stoneBox, [x, 3.4, z], [0.22, 1.9, 1.25], [0, facing, 0]);
  place(kit.stoneSpike, [x, 4.55, z], [0.7, 0.8, 0.7], [0, facing, 0]);
  place(kit.stoneBox, [x + Math.sign(x) * -0.13, 3.5, z], [0.05, 1.1, 0.8], [0, facing, 0]);
  place(kit.gold, [x + Math.sign(x) * -0.17, 3.5, z], [0.04, 0.9, 0.62], [0, facing, 0]);
}

// ---------------------------------------------------------------------------------------

/** Everything that furnishes the nave. Origin and axes match `createCathedral`. */
export function createFurnishings(authoredWicks: readonly IFlamePlacement[] = []): Group {
  const furnishings = new Group();
  furnishings.name = "furnishings";
  fires = [];
  cloths = [];

  // Unit geometries. Every one of these is instanced, so the segment counts below are paid
  // exactly once no matter how many hundreds of copies end up in the frame.
  const unitRod = new CylinderGeometry(1, 1, 1, 8);
  const batches = {
    bronzeRod: batch(unitRod, materials.bronze),
    // A cone frustum, not a cylinder: `rod` puts the wide end at `from`, so a spoke drawn
    // hub-outward thickens toward the hub. Uniform rods at this scale read as bent wire.
    bronzeTaper: batch(new CylinderGeometry(0.42, 1, 1, 6), materials.bronze),
    chainLink: batch(new TorusGeometry(1, 0.26, 4, 8), materials.bronze),
    flame: batch(
      // A teardrop, not a sphere: the pointed top and the narrow waist are the read that
      // says flame. Unit height, as the sphere it replaces was, so every scale below is
      // unchanged; the lathe profile is slimmer than the sphere's equator, which is the
      // point — spherical flames read as glowing beads.
      new LatheGeometry(
        [
          new Vector2(0.001, -1),
          new Vector2(0.42, -0.66),
          new Vector2(0.68, -0.1),
          new Vector2(0.56, 0.4),
          new Vector2(0.24, 0.78),
          new Vector2(0.001, 1),
        ],
        12,
      ),
      materials.flame,
    ),
    gold: batch(new BoxGeometry(1, 1, 1), materials.gold),
    // A quad, not a sphere: `animateFires` turns every one of these to face the camera
    // each frame, which is the half of the soft-halo change that lives outside the
    // material. It costs nothing extra — the animator was already rewriting this matrix.
    halo: batch(new PlaneGeometry(1, 1), materials.halo),
    ironBox: batch(new BoxGeometry(1, 1, 1), materials.iron),
    ironRod: batch(unitRod, materials.iron),
    ironSpike: batch(new ConeGeometry(1, 1, 6), materials.iron),
    knop: batch(new SphereGeometry(1, 8, 6), materials.bronze),
    ring: batch(new TorusGeometry(1, 0.05, 6, 28), materials.bronze),
    stoneBox: batch(new BoxGeometry(1, 1, 1), materials.carvedStone),
    stoneHead: batch(new SphereGeometry(1, 8, 6), materials.carvedStone),
    stoneSpike: batch(new ConeGeometry(1, 1, 4), materials.carvedStone),
    // A lathed robe: one profile, many figures. Modelling a body would cost geometry the
    // frame never resolves — at 20 m in an unlit aisle a statue is a tapering silhouette.
    robe: batch(
      new LatheGeometry(
        [
          new Vector2(0.42, 0),
          new Vector2(0.4, 0.25),
          new Vector2(0.34, 0.8),
          new Vector2(0.29, 1.25),
          new Vector2(0.27, 1.6),
          new Vector2(0.22, 1.82),
          new Vector2(0.13, 1.95),
          new Vector2(0.06, 2.0),
        ],
        10,
      ),
      materials.carvedStone,
    ),
    wax: batch(unitRod, materials.wax),
  };
  const kit: IKit = batches;

  // ---- chandeliers -------------------------------------------------------------------
  // Two staggered rows rather than one down the axis. A centred row stacks in perspective
  // and hangs directly over the rose window, which is the one thing in the frame that must
  // stay unobstructed; flanking them opens the axis and puts a lit wheel in each half of
  // the picture, which is how the reference is composed.
  chandelier(kit, 6.2, 11.0, 9.9, 1.55, 12);
  chandelier(kit, -4.9, 2.5, 10.4, 1.75, 14);
  chandelier(kit, 5.0, -8.0, 10.8, 1.6, 12);
  // Stops short of the chancel arch at z -19.5; a wheel hung inside the arch loses its
  // chain against the arch order and reads as a ring stuck to the masonry.
  chandelier(kit, -4.7, -13.5, 11.0, 1.5, 12);

  // ---- candle stands -----------------------------------------------------------------
  // Against the piers, where the reference puts them: a lit object in the near field is
  // what gives the nave its scale, because the eye reads a candle as a known size.
  // The foreground pair, and they are placed against the *camera*, not against the
  // architecture. The view sits at x 2.6 — a metre and a half off the axis — with a 63°
  // lens, which leaves the near frustum only about ten metres wide at the first pier row:
  // a stand out at the pier line four metres away is entirely off the left edge, which is
  // where the previous near stand went when the framing moved. These two stand in from the
  // colonnade so their flames land in the lower-left of the frame, three and eight metres
  // from the lens. That is the whole job: a candle is a known size, so a lit cluster this
  // close is what tells the eye the piers behind it are fifteen metres tall, and the pool
  // it throws is the only warm thing on the near pavement.
  // The two stands nearest the lens are NOT built here. `AUTHORED_STANDS` above reserves
  // them for the imported glTF pieces, because the near field is the one place in the frame
  // where a lathe-and-cylinder stand is read as a lathe-and-cylinder stand: at three metres
  // the eye resolves the crossbar, and a modelled one carries chasing and a cast foot that
  // no amount of primitives buys. Everything further down the nave stays procedural — past
  // eight metres the two are indistinguishable and the procedural one costs no draw call.
  candelabrum(kit, -4.4, 13.4, 2.6, 7, 0.4);
  candelabrum(kit, -6.3, 8.2, 2.35, 7, 0.3);
  candelabrum(kit, -6.2, -0.6, 2.3, 7, 0.3);
  // The right of the nave, held in toward the axis. The nearest pier on that side fills the
  // right quarter of the frame from top to bottom, and anything placed behind it at
  // x > 6 disappears whole — including, in the third capture, an entire seven-branch stand.
  candelabrum(kit, 5.4, 6.0, 2.5, 7, -0.45);
  candelabrum(kit, 5.9, -6.4, 2.25, 7, -0.3);

  // ---- aisle votives -----------------------------------------------------------------
  // Placed so the sight line from the camera through an arcade opening actually lands on
  // them; a rack behind a pier is a rack nobody ever sees.
  // One of these is on the nave side of the arcade rather than in the aisle behind it.
  // A rack correctly placed in an aisle bay is invisible from the nave floor here — the
  // colonnade is deep enough that almost no sightline clears it — and the warm pool it
  // throws on the pavement is the whole reason it exists.
  votiveRack(kit, -5.4, 10.5, Math.PI / 2);
  votiveRack(kit, -9.8, -1.0, Math.PI / 2);
  votiveRack(kit, 9.8, 10.0, -Math.PI / 2);

  // ---- the chancel enclosure ---------------------------------------------------------
  // `createCathedral` builds twenty-seven bars across x ±6.5, standing on the raised
  // platform and topping out at 4.78. This continues that line out past the edge of the
  // platform — where the floor drops back to 0 and the bars have to be a whole metre
  // taller to reach the same crest — and adds the finialled top the reference silhouettes
  // against the lit apse.
  const screenTop = CHANCEL_Y + 3.4;
  for (const side of [-1, 1]) {
    railing(kit, [side * 6.7, SCREEN_Z], [side * (AISLE_WALL_X - 1.2), SCREEN_Z], screenTop, {
      finials: true,
      pitch: 0.34,
    });
    // Gate posts on the platform, taller than the screen, marking the opening on the axis.
    rod(kit.ironRod, [side * 2.0, CHANCEL_Y, SCREEN_Z], [side * 2.0, screenTop + 0.5, SCREEN_Z], 0.1);
    place(kit.ironSpike, [side * 2.0, screenTop + 0.85, SCREEN_Z], [0.16, 0.6, 0.16]);
  }
  // The crest, spanning the shell's bars and this file's, so the whole screen reads as one
  // horizontal rather than as three pieces of fence that happen to line up.
  place(kit.ironBox, [0, screenTop + 0.06, SCREEN_Z], [2 * (AISLE_WALL_X - 1.2), 0.11, 0.11]);
  // The choir enclosure, running east from the screen along the edge of the platform. It
  // is the only thing in the frame that draws a receding line at eye level, and a lattice
  // in perspective is worth more to the read of depth than the same lattice seen flat on.
  for (const side of [-1, 1]) {
    railing(
      kit,
      [side * (CHANCEL_HALF_WIDTH - 0.35), SCREEN_Z - 0.6],
      [side * (CHANCEL_HALF_WIDTH - 0.35), SCREEN_Z - 6.0],
      2.6,
      { pitch: 0.38, baseY: CHANCEL_Y },
    );
  }
  // A low communion rail on the nave floor, west of the chancel steps.
  railing(kit, [-3.4, CHANCEL_Z + 3.6], [3.4, CHANCEL_Z + 3.6], 0.95, { pitch: 0.36 });

  // ---- the altar group ---------------------------------------------------------------
  //
  // Replaced by an authored glTF sanctuary, placed by `Play` at the same ALTAR_Z. The
  // procedural set below — mensa fittings, candlesticks, cross, reredos and tabernacle
  // canopy — is kept rather than deleted because it is the fallback if that asset is ever
  // removed, and because its measurements document what the authored one has to match.
  const AUTHORED_SANCTUARY = true;
  if (!AUTHORED_SANCTUARY) {
    // Everything here stands on the sanctuary platform, so every y is measured from
    // `CHANCEL_Y`. The shell's altar block is 1.35 tall centred at 1.76, which puts its top
    // at 2.435 — the height every fitting below sits on.
    const mensaY = 2.435;

    const runner = new Mesh(new BoxGeometry(4.6, 0.03, 7.5), materials.carpet);
    runner.position.set(0, CHANCEL_Y + 0.015, ALTAR_Z + 3.4);
    runner.receiveShadow = true;
    furnishings.add(runner);

    // The mensa and its frontal. The linen is the brightest non-emissive surface in the
    // building and it sits dead on the axis, which is what pulls the eye to the east end.
    place(kit.stoneBox, [0, mensaY + 0.07, ALTAR_Z], [4.7, 0.14, 2.15]);
    const frontal = new Mesh(new BoxGeometry(4.2, 1.3, 0.04), materials.linen);
    frontal.position.set(0, 1.76, ALTAR_Z + 0.97);
    furnishings.add(frontal);
    place(kit.gold, [0, 2.36, ALTAR_Z + 0.98], [4.2, 0.08, 0.03]);
    place(kit.gold, [0, 1.8, ALTAR_Z + 0.99], [0.1, 0.7, 0.03]);
    place(kit.gold, [0, 1.96, ALTAR_Z + 0.99], [0.44, 0.1, 0.03]);

    // Six candlesticks and a cross: the standard altar set, and six small flames at the far
    // end of a 55 m axis is exactly the cue that says something is happening down there.
    const setZ = ALTAR_Z - 0.4;
    for (let index = 0; index < 6; index += 1) {
      const cx = -1.65 + index * 0.66;
      rod(kit.bronzeRod, [cx, mensaY + 0.14, setZ], [cx, mensaY + 0.72, setZ], 0.035);
      place(kit.knop, [cx, mensaY + 0.42, setZ], [0.075, 0.06, 0.075]);
      place(kit.bronzeRod, [cx, mensaY + 0.75, setZ], [0.07, 0.07, 0.07]);
      candle(kit, cx, mensaY + 0.79, setZ, 0.42, 0.04);
    }
    place(kit.gold, [0, mensaY + 1.35, setZ - 0.25], [0.08, 1.25, 0.08]);
    place(kit.gold, [0, mensaY + 1.67, setZ - 0.25], [0.62, 0.08, 0.08]);

    // The reredos behind the altar: five gabled panels, the centre one tallest.
    for (let index = -2; index <= 2; index += 1) {
      const panelHeight = 3.4 - Math.abs(index) * 0.45;
      const panelZ = ALTAR_Z - 1.7;
      place(kit.stoneBox, [index * 1.22, CHANCEL_Y + panelHeight / 2, panelZ], [1.14, panelHeight, 0.3]);
      place(
        kit.stoneSpike,
        [index * 1.22, CHANCEL_Y + panelHeight + 0.42, panelZ],
        [0.86, 0.85, 0.42],
        [0, Math.PI / 4, 0],
      );
      if (index !== 0) continue;
      place(kit.gold, [index * 1.22, CHANCEL_Y + panelHeight * 0.62, panelZ + 0.17], [0.6, 0.9, 0.04]);
    }

    // The tabernacle canopy: a slender spire over the altar, rising past the top of the
    // screen. Everything else in the sanctuary sits below the screen's crest and is read
    // through a lattice of iron bars; the spire is the one part of the group that clears
    // them, and it is the reason the east end reads as a *place* rather than as a bright
    // window with some candles in front of it.
    const canopyFoot = CHANCEL_Y + 0.1;
    const canopyTop = CHANCEL_Y + 5.6;
    for (const cx of [-0.62, 0.62]) {
      for (const cz of [-0.62, 0.62]) {
        rod(kit.stoneBox, [cx, canopyFoot, ALTAR_Z + cz], [cx, canopyTop, ALTAR_Z + cz], 0.09);
      }
    }
    place(kit.stoneBox, [0, canopyTop, ALTAR_Z], [1.7, 0.22, 1.7]);
    for (const [gx, gz, yaw] of [
      [0, 0.85, 0],
      [0, -0.85, 0],
      [0.85, 0, Math.PI / 2],
      [-0.85, 0, Math.PI / 2],
    ] as ReadonlyArray<readonly [number, number, number]>) {
      place(kit.stoneSpike, [gx, canopyTop + 0.5, ALTAR_Z + gz], [0.75, 0.9, 0.2], [0, yaw, 0]);
    }
    place(kit.stoneSpike, [0, canopyTop + 1.3, ALTAR_Z], [0.82, 1.9, 0.82], [0, Math.PI / 4, 0]);
    // Crockets. Four knops up the spire are what stop a cone reading as a traffic bollard.
    for (let step = 0; step < 4; step += 1) {
      const t = 0.18 + step * 0.2;
      place(kit.knop, [0, canopyTop + 0.35 + t * 1.9, ALTAR_Z], [0.1, 0.1, 0.1]);
    }
    place(kit.gold, [0, canopyTop + 2.5, ALTAR_Z], [0.09, 0.62, 0.09]);
    place(kit.gold, [0, canopyTop + 2.6, ALTAR_Z], [0.34, 0.09, 0.09]);

  }

  // Two sanctuary lamps on long chains, one either side of the altar. They hang where a
  // chandelier cannot — inside the chancel arch, below the apse vault — and they are the
  // only warm light *behind* the screen, which is what stops the sanctuary reading as a
  // flat lit backdrop with a silhouette in front of it.
  for (const side of [-1, 1]) {
    const lampX = side * 2.7;
    const lampZ = ALTAR_Z + 1.9;
    const bowlY = CHANCEL_Y + 3.3;
    for (let y = bowlY + 0.5; y < 15; y += 0.34) {
      const upright = Math.round((y - bowlY) / 0.34) % 2 === 0;
      place(kit.chainLink, [lampX, y, lampZ], [0.1, 0.1, 0.1], [0, upright ? 0 : Math.PI / 2, 0]);
    }
    for (const hang of [-0.22, 0.22]) {
      rod(
        kit.bronzeRod,
        [lampX + hang, bowlY + 0.52, lampZ],
        [lampX, bowlY + 0.14, lampZ],
        0.016,
      );
    }
    place(kit.knop, [lampX, bowlY, lampZ], [0.24, 0.15, 0.24]);
    candle(kit, lampX, bowlY + 0.06, lampZ, 0.1, 0.05);
  }

  // ---- banners -----------------------------------------------------------------------
  // Hung from alternating piers so the two colonnades do not mirror each other exactly —
  // a perfectly symmetric pair of banners reads as wallpaper.

  // One geometry each rather than one shared: the fold phase is baked into the vertices, so
  // sharing would hang four identically creased cloths on four piers. Four banners is four
  // draws either way.
  for (const [x, z, phase] of [
    [-BANNER_X, -3.5, 0.7],
    [-BANNER_X, 10.5, 2.3],
    [BANNER_X, 3.5, 4.1],
    [BANNER_X, -10.5, 5.6],
  ] as ReadonlyArray<readonly [number, number, number]>) {
    // 11.6, not the 13.0 these hung at. The near pier is ten metres from a lens whose
    // frustum tops out around y 10 there, so at 13.0 the only banner properly broadside to
    // the camera showed its bottom metre and nothing else — no device, no hem, no shape.
    banner(kit, furnishings, x, z + NAVE.pierRadius + 0.25, 11.6, phase);
  }

  // ---- aisle statuary and memorials --------------------------------------------------
  // Everything here lives in light the sun never reaches. If the GI stage is off these are
  // black cut-outs; if it is on they are modelled by bounce off the arcade — which makes
  // them the cheapest read on whether the stage did anything.
  for (const side of [-1, 1]) {
    for (const bay of [3, 5, 7]) {
      // Bay centres, on the nave side of the arcade rather than out in the aisle. The
      // colonnade in this building is dense enough that a sightline from the nave floor
      // into an aisle bay is almost never clear: statues placed properly in the aisle were
      // invisible in three consecutive captures. Standing them against the arcade puts
      // them where the reference's are read from — in front of an opening, not behind one.
      const z = -HALF_DEPTH + bay * NAVE.bayPitch + NAVE.bayPitch / 2;
      // Bays 5 and 7 on the +X side are left empty on purpose: `Play` stands authored glTF
      // figures there instead, so authored statues and these procedural ones can be
      // compared standing in the same light in the same aisle.
      if (side > 0 && (bay === 5 || bay === 7)) continue;
      statue(kit, side * 6.95, z, side > 0 ? -Math.PI / 2 : Math.PI / 2);
    }
    for (const bay of [2, 4, 6]) {
      const z = -HALF_DEPTH + bay * NAVE.bayPitch + NAVE.bayPitch / 2;
      memorial(kit, side * (AISLE_WALL_X - 0.35), z, 0);
    }
  }

  // ---- the two real lights -----------------------------------------------------------
  //
  // Both exist for the same reason: screen-space GI can only gather light off surfaces
  // that are *in the frame and lit*, and in both these places the surface that has to
  // receive the warm light is either facing away from the camera or is the reflective
  // floor directly beneath the source, where the gather radius of 8 m has nothing to
  // sample from. A point light is the only thing that puts light there.
  //
  // 1. The foreground candle stand. It sits on the polished marble that fills the bottom
  //    third of the frame, and that floor is the largest surface in the picture with no
  //    other warm source anywhere near it.
  const standLight = new PointLight(0xffb066, 6.5, 12, 2);
  standLight.position.set(-1.3, 3.3, 17.6);
  furnishings.add(standLight);
  // 2. The sanctuary. The altar is 55 m down the axis and stands *in front of* the lit
  //    lancets, so every surface of it that the camera can see faces away from the only
  //    light in the building. Without this it is a black block against bright glass.
  const altarLight = new PointLight(0xffc184, 18, 16, 2);
  altarLight.position.set(0, CHANCEL_Y + 2.6, ALTAR_Z + 2.6);
  furnishings.add(altarLight);

  // ---- fire on the authored stands ----------------------------------------------------
  // Last, so these flames sit at the end of the instance buffers and the procedural
  // candles keep the indices — and therefore the seeded phases — they had before the
  // imported models arrived. A capture of an unchanged stage stays byte-comparable.
  for (const wick of authoredWicks) {
    lightWick(kit, wick.x, wick.y, wick.z, wick.size ?? 1);
  }

  // ---- resolve every batch into its single draw ---------------------------------------
  // The names are not only for debugging. `collision.ts` decides what gets a static trimesh
  // collider by matching object names against
  // /glass|flame|candle|chain|banner|pane|rose|lancet|chandelier/. Today `Play` hands that
  // builder the cathedral group and not this one, so nothing here is collided either way —
  // but a batch named for its *material* rather than for what it is would fall straight
  // through that filter the moment it is, and every taper below the 4.5 m reach ceiling
  // would become something the player can stand on. Hence "candle-wax", not "wax".
  batches.bronzeRod.build(furnishings, "furnishings-bronze-rods", true);
  batches.bronzeTaper.build(furnishings, "furnishings-bronze-tapers", true);
  batches.chainLink.build(furnishings, "furnishings-chain", false);
  const flameMesh = batches.flame.build(furnishings, "furnishings-flames", false);
  batches.gold.build(furnishings, "furnishings-gold", false);
  const haloMesh = batches.halo.build(furnishings, "furnishings-candle-halos", false);
  batches.ironBox.build(furnishings, "furnishings-iron-rails", true);
  batches.ironRod.build(furnishings, "furnishings-iron-rods", true);
  batches.ironSpike.build(furnishings, "furnishings-finials", true);
  batches.knop.build(furnishings, "furnishings-knops", false);
  batches.ring.build(furnishings, "furnishings-rings", true);
  batches.robe.build(furnishings, "furnishings-statues", true);
  batches.stoneBox.build(furnishings, "furnishings-stone", true);
  batches.stoneHead.build(furnishings, "furnishings-heads", false);
  batches.stoneSpike.build(furnishings, "furnishings-gables", true);
  batches.wax.build(furnishings, "furnishings-candle-wax", false);

  // ---- fire animation -----------------------------------------------------------------
  // Every flame and both real lights breathe on a seeded phase: deterministic in the
  // build, so two captures of the same frame time still differ by the stage under test
  // and nothing else, while no two neighbouring flames move together. The halo rides its
  // own wobbled matrix rather than the flame's, because the two draw from different base
  // scales. Cost is two instance-matrix uploads of a few hundred entries per frame —
  // orders of magnitude under the post chain.
  if (flameMesh !== undefined && haloMesh !== undefined) {
    furnishings.userData.animateFires = (time: number, camera?: Object3D): void => {
      // The halo quad faces the lens. Read once per frame, not once per flame: every halo
      // in the building shares one orientation, and there are several hundred of them.
      if (camera !== undefined) camera.getWorldQuaternion(haloFacing);
      for (let index = 0; index < fires.length; index += 1) {
        const fire = fires[index] as IFire;
        // Two offset sines: one slow breath, one quicker gutter. Flatlined they would
        // read as a scale tween; the pair is what reads as combustion.
        const wobble =
          Math.sin(time * fire.speed + fire.phase) * 0.6 +
          Math.sin(time * fire.speed * 1.73 + fire.phase * 2.1) * 0.4;
        dummy.position.set(fire.x + wobble * 0.004, fire.y + wobble * 0.006, fire.z);
        dummy.rotation.set(0, 0, wobble * 0.06);
        dummy.scale.set(
          fire.sx * (1 - Math.abs(wobble) * 0.07),
          fire.sy * (1 + wobble * 0.16),
          fire.sz * (1 - Math.abs(wobble) * 0.07),
        );
        dummy.updateMatrix();
        flameMesh.setMatrixAt(index, dummy.matrix);
        // The halo rides its own wobbled matrix rather than the flame's, because the two
        // draw from different base scales — and now from different orientations too: the
        // flame is a lathe standing on the wick, the halo is a quad turned to the camera.
        dummy.quaternion.copy(haloFacing);
        dummy.scale.set(
          fire.hx * (1 - Math.abs(wobble) * 0.05),
          fire.hy * (1 + wobble * 0.1),
          fire.hz * (1 - Math.abs(wobble) * 0.05),
        );
        dummy.updateMatrix();
        haloMesh.setMatrixAt(index, dummy.matrix);
        // Put the shared dummy back the way the flame branch expects to find it next pass.
        dummy.quaternion.identity();
      }
      flameMesh.instanceMatrix.needsUpdate = true;
      haloMesh.instanceMatrix.needsUpdate = true;
      standLight.intensity =
        6.5 * (1 + Math.sin(time * 9.3) * 0.05 + Math.sin(time * 15.7) * 0.03);
      altarLight.intensity =
        18 * (1 + Math.sin(time * 7.9 + 1.3) * 0.05 + Math.sin(time * 13.1) * 0.03);
    };
  }

  // ---- cloth ---------------------------------------------------------------------------
  // Its own hook rather than a line inside `animateFires`, because the two want different
  // clocks: the flames are a closed form in elapsed time and the cloth is an integrator
  // that needs the step. Reported, not silent — a sim that throws on a grid mismatch is
  // loud, but a sim nobody calls is not, and four dead banners look exactly like four
  // simulated banners in still air.
  furnishings.userData.stepCloth = (dt: number): number => {
    let excursion = 0;
    for (const cloth of cloths) {
      cloth.step(dt);
      excursion = Math.max(excursion, cloth.excursion);
    }
    return excursion;
  };
  console.info(
    `TN_BANNER_CLOTH:${JSON.stringify({
      sheets: cloths.length,
      particles: cloths.reduce((total, cloth) => total + cloth.particles, 0),
      constraints: cloths.reduce((total, cloth) => total + cloth.constraintCount, 0),
    })}`,
  );

  return furnishings;
}
