// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// Everything inside the building that is not the building: chandeliers, candle stands,
// pews, statues, banners, the chancel fittings. Owned by the interior-details lane.
//
// Contract with `cathedral.ts`: this file adds objects *inside* the nave volume described
// by `NAVE` and never edits the shell. Anything emissive placed here is a light source the
// screen-space GI pass will gather from, so keep the count of genuinely bright objects
// low and deliberate.
//
// The lighting budget is the design constraint, not a detail of it. Every flame in the
// reference is a candle, and there are roughly two hundred of them; two hundred
// `PointLight`s is two hundred forward-shading iterations per fragment and a scene that
// no longer runs. Instead each flame is an *emissive material above the tonemap ceiling*:
// bloom spreads it and the SSGI pass gathers it off the beauty buffer, so the flames pay
// for themselves as light without ever entering the light loop. Exactly two real point
// lights survive, and each says below why it could not be an emissive quad.
//
// The second constraint is draw calls. Every repeated part — chain link, candle, wax,
// flame, railing bar, spoke, finial — goes into one shared `InstancedMesh` per
// material+geometry pair rather than one per object, so the entire furnishing set costs
// roughly twenty draws no matter how many candles are lit. The batches are declared once
// at the bottom of `createFurnishings` and every builder below writes into them.
import {
  AdditiveBlending,
  BoxGeometry,
  type BufferGeometry,
  Color,
  ConeGeometry,
  CylinderGeometry,
  DoubleSide,
  Group,
  InstancedMesh,
  LatheGeometry,
  type Material,
  Matrix4,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  Object3D,
  PointLight,
  Quaternion,
  Shape,
  ExtrudeGeometry,
  SphereGeometry,
  TorusGeometry,
  Vector2,
  Vector3,
} from "three";
import { NAVE } from "./lighting.js";

// ---------------------------------------------------------------------------------------
// materials
// ---------------------------------------------------------------------------------------
//
// There is no environment map in this scene — one sun and the GI pass, nothing else. A
// `metalness` near 1 with no environment to reflect renders as black, which is why the
// cathedral's chancel screen is deliberately 0.7 and reads as pure silhouette. Anything
// here that must stay *visible* against the dark vault therefore stays low-metalness and
// leans on a small `emissive` term to keep it off the floor of the histogram.
const materials = {
  /** The screens, the chandelier wheels, the candle stands. Silhouette first. */
  iron: new MeshStandardMaterial({ color: 0x16130f, roughness: 0.5, metalness: 0.6 }),
  /**
   * The chandelier corona and the candle cups. Dark bronze rather than bright brass: the
   * reference's chandeliers read as warm because of the flames sitting on them, not
   * because the metal is bright, and a bright ring at that size becomes a hoop of bloom.
   * The faint emissive is what stops the wheel disappearing into an unlit vault.
   */
  bronze: new MeshStandardMaterial({
    color: 0x6b5228,
    roughness: 0.42,
    metalness: 0.3,
    emissive: 0x2b1d09,
  }),
  /** Heraldic gold on the banners and the altar. Same reasoning as bronze, one stop up. */
  gold: new MeshStandardMaterial({
    color: 0x8a6a2c,
    roughness: 0.38,
    metalness: 0.35,
    emissive: 0x241a08,
  }),
  /** Candle wax. Warm-lit from its own flame, so it carries a little emissive of its own. */
  wax: new MeshStandardMaterial({ color: 0xd9cdb2, roughness: 0.75, emissive: 0x3a2610 }),
  /** Statues, plinths, memorial panels, the reredos. One shade off the building's stone. */
  carvedStone: new MeshStandardMaterial({ color: 0x6d6558, roughness: 0.9, metalness: 0 }),
  /** The altar linen: the only near-white cloth in the building, and it reads as the focus. */
  linen: new MeshStandardMaterial({ color: 0xbdb49c, roughness: 0.85, metalness: 0 }),
  /**
   * Banner cloth. Deep and unsaturated — the glass owns the colour in this room.
   *
   * The `emissive` is not a glow, it is a floor. The sun travels +X/-Z, so a cloth hung
   * flat against a pier receives no direct light at any angle, and the gathered indirect
   * on a navy albedo rounds to black: the first capture showed the gold device floating
   * with nothing behind it. The emissive term is what keeps the cloth a dark blue shape
   * instead of a hole.
   */
  banner: new MeshStandardMaterial({
    color: 0x232d54,
    roughness: 0.88,
    metalness: 0,
    emissive: 0x0a0f22,
    side: DoubleSide,
  }),
  /** The sanctuary runner. Muted, so it warms the steps without competing with the rose. */
  carpet: new MeshStandardMaterial({ color: 0x51201d, roughness: 0.9, metalness: 0 }),
  /**
   * A flame.
   *
   * `toneMapped: false` and a colour authored far *past* 1.0. The bloom stage thresholds
   * at 0.2 but its strength is only 0.18, so the halo a flame throws is proportional to how
   * far over the threshold it sits, not to how big the mesh is. The first capture used 2.6
   * and the candles rendered as white sticks with no light on them at all.
   */
  flame: new MeshBasicMaterial({ color: new Color().setRGB(5.5, 2.7, 0.95), toneMapped: false }),
  /**
   * The halo around a flame.
   *
   * Additive, depth-writing off, and much larger than the flame itself. Bloom alone cannot
   * do this job here: `bloomStrength` is 0.18 because the stained glass is already past the
   * tonemap ceiling and a stronger bloom lifts the whole frame. The halo is a local,
   * per-candle version of the same effect that costs one draw call for every candle in the
   * building and nothing in the post chain.
   */
  halo: new MeshBasicMaterial({
    color: new Color().setRGB(0.32, 0.14, 0.045),
    blending: AdditiveBlending,
    depthWrite: false,
    toneMapped: false,
    transparent: true,
  }),
};

// ---------------------------------------------------------------------------------------
// instancing
// ---------------------------------------------------------------------------------------

/** Accumulates transforms for one geometry+material pair, then becomes one draw call. */
interface IBatch {
  readonly add: (matrix: Matrix4) => void;
}

interface IBuiltBatch extends IBatch {
  readonly build: (parent: Group, name: string, castShadow: boolean) => void;
}

function batch(geometry: BufferGeometry, material: Material): IBuiltBatch {
  const matrices: Matrix4[] = [];
  return {
    add: (matrix: Matrix4): void => {
      matrices.push(matrix.clone());
    },
    build: (parent: Group, name: string, castShadow: boolean): void => {
      if (matrices.length === 0) return;
      const mesh = new InstancedMesh(geometry, material, matrices.length);
      mesh.name = name;
      for (let index = 0; index < matrices.length; index += 1) {
        mesh.setMatrixAt(index, matrices[index] as Matrix4);
      }
      mesh.instanceMatrix.needsUpdate = true;
      // Candles and chain links are sub-texel in a 4096 map spanning 92 metres; asking the
      // shadow pass to rasterise them buys nothing and costs a second full instanced draw.
      mesh.castShadow = castShadow;
      mesh.receiveShadow = castShadow;
      mesh.computeBoundingSphere();
      parent.add(mesh);
    },
  };
}

const dummy = new Object3D();
const UP = new Vector3(0, 1, 0);
const rodDirection = new Vector3();
const rodMidpoint = new Vector3();
const rodRotation = new Quaternion();

/** Place one instance by position, scale and Euler rotation. */
function place(
  target: IBatch,
  position: [number, number, number],
  scale: [number, number, number],
  rotation: [number, number, number] = [0, 0, 0],
): void {
  dummy.position.set(position[0], position[1], position[2]);
  dummy.rotation.set(rotation[0], rotation[1], rotation[2]);
  dummy.scale.set(scale[0], scale[1], scale[2]);
  dummy.updateMatrix();
  target.add(dummy.matrix);
}

/**
 * Place a unit cylinder as a rod spanning two points.
 *
 * Chains, tie rods and railing bars are all "from A to B" rather than "at P with rotation
 * R"; deriving the quaternion here keeps every caller from hand-computing an Euler angle
 * that is wrong the moment a position moves by a metre.
 */
function rod(
  target: IBatch,
  from: [number, number, number],
  to: [number, number, number],
  radius: number,
): void {
  rodDirection.set(to[0] - from[0], to[1] - from[1], to[2] - from[2]);
  const length = rodDirection.length();
  if (length < 1e-5) return;
  rodDirection.divideScalar(length);
  rodRotation.setFromUnitVectors(UP, rodDirection);
  rodMidpoint.set((from[0] + to[0]) / 2, (from[1] + to[1]) / 2, (from[2] + to[2]) / 2);
  dummy.position.copy(rodMidpoint);
  dummy.quaternion.copy(rodRotation);
  dummy.scale.set(radius, length, radius);
  dummy.updateMatrix();
  dummy.rotation.set(0, 0, 0);
  target.add(dummy.matrix);
}

// ---------------------------------------------------------------------------------------
// layout, derived from the bay so nothing drifts when the nave is resized
// ---------------------------------------------------------------------------------------
const BAYS = Math.floor(NAVE.depth / NAVE.bayPitch);
const HALF_DEPTH = (BAYS * NAVE.bayPitch) / 2;
/** Centre of the pier standing proud of the arcade, matching `createCathedral`. */
const PIER_X = NAVE.width / 2 - NAVE.pierRadius * 0.7;
/** Face of the outer aisle wall. */
const AISLE_WALL_X = NAVE.width / 2 + NAVE.aisleWidth;
/** The chancel screen line `createCathedral` already builds bars on. */
/**
 * The east end, mirrored from `createCathedral`.
 *
 * These five numbers are the shell's, not this file's: the chancel arch springs two bays
 * short of the east wall, the sanctuary floor is a raised platform, and the screen stands
 * on it. They are duplicated here rather than imported because `cathedral.ts` exports one
 * function and nothing else — which makes them the one thing in this file that can go
 * silently stale. When the altar moves over there, these move here, and the symptom is an
 * altar set floating a metre below a platform it should be standing on.
 */
const CHANCEL_Z = -HALF_DEPTH + NAVE.bayPitch * 2;
/** Top of the raised sanctuary platform: everything in the chancel stands on this. */
const CHANCEL_Y = 1.08;
const SCREEN_Z = CHANCEL_Z - 0.8;
const ALTAR_Z = CHANCEL_Z - 6.5;
/** Half-width of the platform. Outside this the chancel fittings stand on the nave floor. */
const CHANCEL_HALF_WIDTH = 5.8;

// ---------------------------------------------------------------------------------------
// the pieces
// ---------------------------------------------------------------------------------------

interface IKit {
  readonly bronzeRod: IBatch;
  readonly chainLink: IBatch;
  readonly flame: IBatch;
  readonly gold: IBatch;
  readonly halo: IBatch;
  readonly ironBox: IBatch;
  readonly ironRod: IBatch;
  readonly ironSpike: IBatch;
  readonly knop: IBatch;
  readonly ring: IBatch;
  readonly stoneBox: IBatch;
  readonly stoneHead: IBatch;
  readonly stoneSpike: IBatch;
  readonly robe: IBatch;
  readonly wax: IBatch;
}

/**
 * One lit candle: wax plus flame, with the flame sitting *on* the wick rather than
 * floating above it. Height varies per call because a rack of candles all burnt to the
 * same length reads as a comb, which is the single most artificial thing a candle rack
 * can do.
 */
function candle(kit: IKit, x: number, baseY: number, z: number, height: number, radius: number) {
  place(kit.wax, [x, baseY + height / 2, z], [radius, height, radius]);
  // Deliberately larger than a real flame. A 15 mm flame 20 m down the nave is a third of a
  // pixel; at that size the tonemap averages it away with its neighbours and the candle
  // reads as an unlit white stick, which is exactly what the first capture showed.
  const tip = baseY + height + 0.09;
  place(kit.flame, [x, tip, z], [0.05, 0.11, 0.05]);
  // Kept barely wider than the flame. The halo is a sphere, not a soft sprite, so two of
  // them closer together than their own radius merge into one lozenge with no candles
  // inside it — which is what a 0.2 m halo did to every seven-branch stand in the frame.
  place(kit.halo, [x, tip, z], [0.115, 0.14, 0.115]);
}

/**
 * A hanging wheel chandelier: rim, spokes, corona tie-rods, a ring of candles, and a chain
 * running all the way to the vault springing.
 *
 * The chain is not decoration. In the reference the chandeliers read as *hanging* — the
 * eye follows a line up into darkness — and a wheel with no visible suspension reads as a
 * ring of candles parked in mid-air.
 */
function chandelier(
  kit: IKit,
  x: number,
  z: number,
  ringY: number,
  radius: number,
  arms: number,
): void {
  const hubTop = ringY + radius * 1.15;
  const chainTop = NAVE.clerestoryTop - 1;

  // Links every 0.34 m, each rotated 90° from the last. Two coplanar links read as a
  // dashed line; alternating them is what makes a chain read as a chain at 12 m.
  for (let y = hubTop + 0.35; y < chainTop; y += 0.34) {
    const upright = Math.round((y - hubTop) / 0.34) % 2 === 0;
    place(kit.chainLink, [x, y, z], [0.11, 0.11, 0.11], [0, upright ? 0 : Math.PI / 2, 0]);
  }

  // The rim, and a lighter inner ring. One ring alone reads as a hoop; the pair reads as a
  // wheel, which is the shape the reference's chandeliers are built on.
  place(kit.ring, [x, ringY, z], [radius, radius, radius], [-Math.PI / 2, 0, 0]);
  place(kit.ring, [x, ringY + 0.02, z], [radius * 0.5, radius * 0.5, radius * 0.5], [
    -Math.PI / 2,
    0,
    0,
  ]);
  rod(kit.bronzeRod, [x, ringY - 0.1, z], [x, hubTop + 0.35, z], 0.045);
  place(kit.knop, [x, ringY - 0.28, z], [0.14, 0.22, 0.14]);

  const spokes = 8;
  for (let index = 0; index < spokes; index += 1) {
    const angle = (index / spokes) * Math.PI * 2;
    const rim: [number, number, number] = [
      x + Math.cos(angle) * radius,
      ringY,
      z + Math.sin(angle) * radius,
    ];
    rod(kit.bronzeRod, [x, ringY, z], rim, 0.028);
    // Tie rods from the hub down to the rim: the diagonal is what gives a corona its
    // cone-shaped silhouette instead of a flat disc seen edge-on from below.
    rod(kit.bronzeRod, [x, hubTop, z], rim, 0.022);
  }

  for (let index = 0; index < arms; index += 1) {
    const angle = (index / arms) * Math.PI * 2 + 0.2;
    const cx = x + Math.cos(angle) * radius;
    const cz = z + Math.sin(angle) * radius;
    place(kit.bronzeRod, [cx, ringY + 0.06, cz], [0.085, 0.1, 0.085]);
    candle(kit, cx, ringY + 0.11, cz, 0.3 + ((index * 7) % 5) * 0.02, 0.05);
  }
}

/**
 * A branched floor candelabrum: foot, knopped shaft, crossbar, a row of tapers.
 *
 * `yaw` exists because a bar seen end-on collapses to a single candle. These stand beside
 * the piers where the view direction is oblique, so each is turned a little off the nave
 * axis to keep the row spread across the frame.
 */
function candelabrum(
  kit: IKit,
  x: number,
  z: number,
  height: number,
  count: number,
  yaw: number,
  baseY = 0,
): void {
  const top = baseY + height;
  // A stepped foot, not a ball. A squashed sphere on the floor reads as a boulder at the
  // base of the stand, which is what the fourth capture put under every one of them.
  place(kit.ironRod, [x, baseY + 0.04, z], [0.44, 0.08, 0.44]);
  place(kit.ironRod, [x, baseY + 0.14, z], [0.3, 0.12, 0.3]);
  place(kit.ironRod, [x, baseY + 0.24, z], [0.17, 0.1, 0.17]);
  rod(kit.ironRod, [x, baseY + 0.12, z], [x, top, z], 0.048);
  place(kit.knop, [x, baseY + height * 0.42, z], [0.12, 0.14, 0.12]);
  place(kit.knop, [x, baseY + height * 0.74, z], [0.1, 0.12, 0.1]);

  const spacing = 0.27;
  const span = (count - 1) * spacing;
  const dx = Math.cos(yaw);
  const dz = Math.sin(yaw);
  rod(
    kit.ironRod,
    [x - (dx * span) / 2, top, z - (dz * span) / 2],
    [x + (dx * span) / 2, top, z + (dz * span) / 2],
    0.035,
  );
  for (let index = 0; index < count; index += 1) {
    const offset = -span / 2 + index * spacing;
    const cx = x + dx * offset;
    const cz = z + dz * offset;
    place(kit.bronzeRod, [cx, top + 0.05, cz], [0.075, 0.09, 0.075]);
    // The middle taper is the tallest and they fall away to the ends. A flat row of equal
    // candles reads as a barcode; the arc is what makes the group read as a candelabrum.
    const fall = Math.abs(index - (count - 1) / 2) / Math.max(1, (count - 1) / 2);
    // Plus a deterministic burn-down per position. Thin, because at three metres from the
    // lens a 43 mm taper is a white post: the near stand is the one place in the frame
    // where a candle is read as an object rather than as a point of light.
    const burn = ((index * 5) % 4) * 0.05;
    candle(kit, cx, top + 0.1, cz, 0.78 - fall * 0.24 - burn, 0.033);
  }
}

/**
 * A votive rack in an aisle: a low iron tray carrying rows of stubs burnt to different
 * lengths.
 *
 * This is the only warm thing in the aisles, and the aisles are the part of the frame the
 * GI pass is being judged on — a rack seen through an arcade opening puts a warm pool on a
 * surface that receives no direct sun at all.
 */
function votiveRack(kit: IKit, x: number, z: number, facing: number): void {
  const trayY = 0.78;
  const width = 1.5;
  const depth = 0.62;
  for (const sx of [-1, 1]) {
    for (const sz of [-1, 1]) {
      rod(
        kit.ironRod,
        [x + sx * (width / 2 - 0.1), 0, z + sz * (depth / 2 - 0.08)],
        [x + sx * (width / 2 - 0.1), trayY, z + sz * (depth / 2 - 0.08)],
        0.03,
      );
    }
  }
  place(kit.ironBox, [x, trayY, z], [width, 0.06, depth], [0, facing, 0]);
  place(kit.ironBox, [x, trayY + 0.11, z - depth / 2], [width, 0.16, 0.05], [0, facing, 0]);

  const rows = 3;
  const columns = 7;
  for (let row = 0; row < rows; row += 1) {
    for (let column = 0; column < columns; column += 1) {
      const cx = x + (column / (columns - 1) - 0.5) * (width - 0.2);
      const cz = z + (row / (rows - 1) - 0.5) * (depth - 0.18);
      // Burnt to unequal stubs. The variation is deterministic so two captures of the same
      // build differ by the stage under test and nothing else.
      const burn = ((row * 7 + column * 3) % 5) / 5;
      candle(kit, cx, trayY + 0.03, cz, 0.09 + burn * 0.17, 0.036);
    }
  }
}

/**
 * A run of iron railing between two points: balusters, two rails, a crest and finials.
 *
 * The reference's ironwork is read entirely as a black lattice against a lit apse, so the
 * bar pitch matters more than any other number here — too coarse and it reads as a fence,
 * too fine and it fills in solid and reads as a wall.
 */
function railing(
  kit: IKit,
  from: [number, number],
  to: [number, number],
  height: number,
  options: { readonly pitch?: number; readonly finials?: boolean; readonly baseY?: number } = {},
): void {
  const pitch = options.pitch ?? 0.42;
  const baseY = options.baseY ?? 0;
  const dx = to[0] - from[0];
  const dz = to[1] - from[1];
  const length = Math.hypot(dx, dz);
  if (length < 1e-4) return;
  const count = Math.max(2, Math.round(length / pitch));
  const yaw = Math.atan2(dx, dz);

  for (let index = 0; index <= count; index += 1) {
    const t = index / count;
    const bx = from[0] + dx * t;
    const bz = from[1] + dz * t;
    rod(kit.ironRod, [bx, baseY, bz], [bx, baseY + height, bz], 0.038);
    // A boss on every other bar, on the middle rail. Screen ironwork in the reference is
    // never a plain grid; one repeated ornament at the mid-rail is the cheapest thing that
    // reads as wrought rather than welded, and it costs no extra draw call.
    if (index % 2 === 0) {
      place(kit.knop, [bx, baseY + height * 0.62, bz], [0.09, 0.09, 0.09]);
    }
    if (options.finials === true && index % 3 === 0) {
      place(kit.ironSpike, [bx, baseY + height + 0.24, bz], [0.075, 0.34, 0.075]);
    }
  }
  for (const railY of [baseY + 0.14, baseY + height * 0.62, baseY + height - 0.06]) {
    place(kit.ironBox, [from[0] + dx / 2, railY, from[1] + dz / 2], [0.06, 0.09, length], [
      0,
      yaw,
      0,
    ]);
  }
}

/**
 * A heraldic banner hanging from the west face of a pier.
 *
 * The bottom is a swallowtail rather than a straight hem: the notch is what separates a
 * banner from a rectangle of cloth, and at this distance the notch is most of the read.
 *
 * West face, not the nave face, and that is a lighting decision rather than a liturgical
 * one. The sun in this building travels +X and -Z, so it lights whatever faces -X or +Z;
 * a banner hung flat against the *side* of a pier faces +X and receives no direct light on
 * any part of it. Hung on the west face it faces the camera and the sun at once, which is
 * also how the reference's banners are seen — broadside, not edge-on.
 */
function banner(
  kit: IKit,
  parent: Group,
  geometry: BufferGeometry,
  x: number,
  z: number,
  topY: number,
): void {
  const cloth = new Mesh(geometry, materials.banner);
  cloth.position.set(x, topY, z);
  cloth.castShadow = true;
  parent.add(cloth);

  // The pole and its two suspension rings. Cloth that starts at a bare edge looks pasted
  // to the pier; the pole gives it something to hang from.
  rod(kit.bronzeRod, [x - 1.25, topY + 0.12, z + 0.1], [x + 1.25, topY + 0.12, z + 0.1], 0.05);
  for (const side of [-0.85, 0.85]) {
    place(kit.chainLink, [x + side, topY + 0.26, z + 0.1], [0.14, 0.14, 0.14]);
  }

  // The device: a cross patty in gold. Five boxes rather than a texture, because there are
  // no textures in this file and a flat quad would show as a smear at this size.
  const deviceY = topY - 2.1;
  const face = z + 0.16;
  place(kit.gold, [x, deviceY, face], [0.2, 1.5, 0.06]);
  place(kit.gold, [x, deviceY + 0.28, face], [0.95, 0.2, 0.06]);
  for (const side of [-0.62, 0.62]) {
    place(kit.gold, [x + side, deviceY - 0.75, face], [0.24, 0.24, 0.06]);
  }
  // A hem band across the bottom, which is what stops the swallowtail reading as a tear.
  place(kit.gold, [x, topY - 4.55, face], [1.9, 0.11, 0.05]);
}

/** A robed figure on a plinth, standing in an aisle bay. */
function statue(kit: IKit, x: number, z: number, facing: number): void {
  place(kit.stoneBox, [x, 0.75, z], [0.9, 1.5, 0.9]);
  place(kit.stoneBox, [x, 1.56, z], [1.05, 0.12, 1.05]);
  place(kit.robe, [x, 1.62, z], [1, 1, 1], [0, facing, 0]);
  place(kit.stoneHead, [x, 3.62, z], [0.15, 0.19, 0.15]);
}

/** A wall memorial: gabled stone panel with a gold inscription plate. */
function memorial(kit: IKit, x: number, z: number, facing: number): void {
  place(kit.stoneBox, [x, 3.4, z], [0.22, 1.9, 1.25], [0, facing, 0]);
  place(kit.stoneSpike, [x, 4.55, z], [0.7, 0.8, 0.7], [0, facing, 0]);
  place(kit.stoneBox, [x + Math.sign(x) * -0.13, 3.5, z], [0.05, 1.1, 0.8], [0, facing, 0]);
  place(kit.gold, [x + Math.sign(x) * -0.17, 3.5, z], [0.04, 0.9, 0.62], [0, facing, 0]);
}

// ---------------------------------------------------------------------------------------

/** Everything that furnishes the nave. Origin and axes match `createCathedral`. */
export function createFurnishings(): Group {
  const furnishings = new Group();
  furnishings.name = "furnishings";

  // Unit geometries. Every one of these is instanced, so the segment counts below are paid
  // exactly once no matter how many hundreds of copies end up in the frame.
  const unitRod = new CylinderGeometry(1, 1, 1, 8);
  const batches = {
    bronzeRod: batch(unitRod, materials.bronze),
    chainLink: batch(new TorusGeometry(1, 0.26, 4, 8), materials.bronze),
    flame: batch(new SphereGeometry(1, 6, 5), materials.flame),
    gold: batch(new BoxGeometry(1, 1, 1), materials.gold),
    halo: batch(new SphereGeometry(1, 8, 6), materials.halo),
    ironBox: batch(new BoxGeometry(1, 1, 1), materials.iron),
    ironRod: batch(unitRod, materials.iron),
    ironSpike: batch(new ConeGeometry(1, 1, 6), materials.iron),
    knop: batch(new SphereGeometry(1, 8, 6), materials.bronze),
    ring: batch(new TorusGeometry(1, 0.05, 6, 28), materials.bronze),
    stoneBox: batch(new BoxGeometry(1, 1, 1), materials.carvedStone),
    stoneHead: batch(new SphereGeometry(1, 8, 6), materials.carvedStone),
    stoneSpike: batch(new ConeGeometry(1, 1, 4), materials.carvedStone),
    // A lathed robe: one profile, many figures. Modelling a body would cost geometry the
    // frame never resolves — at 20 m in an unlit aisle a statue is a tapering silhouette.
    robe: batch(
      new LatheGeometry(
        [
          new Vector2(0.42, 0),
          new Vector2(0.4, 0.25),
          new Vector2(0.34, 0.8),
          new Vector2(0.29, 1.25),
          new Vector2(0.27, 1.6),
          new Vector2(0.22, 1.82),
          new Vector2(0.13, 1.95),
          new Vector2(0.06, 2.0),
        ],
        10,
      ),
      materials.carvedStone,
    ),
    wax: batch(unitRod, materials.wax),
  };
  const kit: IKit = batches;

  // ---- chandeliers -------------------------------------------------------------------
  // Two staggered rows rather than one down the axis. A centred row stacks in perspective
  // and hangs directly over the rose window, which is the one thing in the frame that must
  // stay unobstructed; flanking them opens the axis and puts a lit wheel in each half of
  // the picture, which is how the reference is composed.
  chandelier(kit, 6.2, 11.0, 9.9, 1.55, 12);
  chandelier(kit, -4.9, 2.5, 10.4, 1.75, 14);
  chandelier(kit, 5.0, -8.0, 10.8, 1.6, 12);
  // Stops short of the chancel arch at z -19.5; a wheel hung inside the arch loses its
  // chain against the arch order and reads as a ring stuck to the masonry.
  chandelier(kit, -4.7, -13.5, 11.0, 1.5, 12);

  // ---- candle stands -----------------------------------------------------------------
  // Against the piers, where the reference puts them: a lit object in the near field is
  // what gives the nave its scale, because the eye reads a candle as a known size.
  // The foreground pair, and they are placed against the *camera*, not against the
  // architecture. The view sits at x 2.6 — a metre and a half off the axis — with a 63°
  // lens, which leaves the near frustum only about ten metres wide at the first pier row:
  // a stand out at the pier line four metres away is entirely off the left edge, which is
  // where the previous near stand went when the framing moved. These two stand in from the
  // colonnade so their flames land in the lower-left of the frame, three and eight metres
  // from the lens. That is the whole job: a candle is a known size, so a lit cluster this
  // close is what tells the eye the piers behind it are fifteen metres tall, and the pool
  // it throws is the only warm thing on the near pavement.
  candelabrum(kit, -1.3, 17.6, 3.1, 7, 0.55);
  candelabrum(kit, -4.4, 13.4, 2.6, 7, 0.4);
  candelabrum(kit, -6.3, 8.2, 2.35, 7, 0.3);
  candelabrum(kit, -6.2, -0.6, 2.3, 7, 0.3);
  // The right of the nave, held in toward the axis. The nearest pier on that side fills the
  // right quarter of the frame from top to bottom, and anything placed behind it at
  // x > 6 disappears whole — including, in the third capture, an entire seven-branch stand.
  candelabrum(kit, 6.4, 14.5, 2.7, 7, -0.5);
  candelabrum(kit, 5.4, 6.0, 2.5, 7, -0.45);
  candelabrum(kit, 5.9, -6.4, 2.25, 7, -0.3);
  // Flanking the chancel steps, on the nave floor rather than the raised platform.
  candelabrum(kit, -4.1, CHANCEL_Z + 4.4, 2.4, 5, 0.15);
  candelabrum(kit, 4.1, CHANCEL_Z + 4.4, 2.4, 5, -0.15);

  // ---- aisle votives -----------------------------------------------------------------
  // Placed so the sight line from the camera through an arcade opening actually lands on
  // them; a rack behind a pier is a rack nobody ever sees.
  // One of these is on the nave side of the arcade rather than in the aisle behind it.
  // A rack correctly placed in an aisle bay is invisible from the nave floor here — the
  // colonnade is deep enough that almost no sightline clears it — and the warm pool it
  // throws on the pavement is the whole reason it exists.
  votiveRack(kit, -5.4, 10.5, Math.PI / 2);
  votiveRack(kit, -9.8, -1.0, Math.PI / 2);
  votiveRack(kit, 9.8, 10.0, -Math.PI / 2);

  // ---- the chancel enclosure ---------------------------------------------------------
  // `createCathedral` builds twenty-seven bars across x ±6.5, standing on the raised
  // platform and topping out at 4.78. This continues that line out past the edge of the
  // platform — where the floor drops back to 0 and the bars have to be a whole metre
  // taller to reach the same crest — and adds the finialled top the reference silhouettes
  // against the lit apse.
  const screenTop = CHANCEL_Y + 3.4;
  for (const side of [-1, 1]) {
    railing(kit, [side * 6.7, SCREEN_Z], [side * (AISLE_WALL_X - 1.2), SCREEN_Z], screenTop, {
      finials: true,
      pitch: 0.34,
    });
    // Gate posts on the platform, taller than the screen, marking the opening on the axis.
    rod(kit.ironRod, [side * 2.0, CHANCEL_Y, SCREEN_Z], [side * 2.0, screenTop + 0.5, SCREEN_Z], 0.1);
    place(kit.ironSpike, [side * 2.0, screenTop + 0.85, SCREEN_Z], [0.16, 0.6, 0.16]);
  }
  // The crest, spanning the shell's bars and this file's, so the whole screen reads as one
  // horizontal rather than as three pieces of fence that happen to line up.
  place(kit.ironBox, [0, screenTop + 0.06, SCREEN_Z], [2 * (AISLE_WALL_X - 1.2), 0.11, 0.11]);
  // The choir enclosure, running east from the screen along the edge of the platform. It
  // is the only thing in the frame that draws a receding line at eye level, and a lattice
  // in perspective is worth more to the read of depth than the same lattice seen flat on.
  for (const side of [-1, 1]) {
    railing(
      kit,
      [side * (CHANCEL_HALF_WIDTH - 0.35), SCREEN_Z - 0.6],
      [side * (CHANCEL_HALF_WIDTH - 0.35), SCREEN_Z - 6.0],
      2.6,
      { pitch: 0.38, baseY: CHANCEL_Y },
    );
  }
  // A low communion rail on the nave floor, west of the chancel steps.
  railing(kit, [-3.4, CHANCEL_Z + 3.6], [3.4, CHANCEL_Z + 3.6], 0.95, { pitch: 0.36 });

  // ---- the altar group ---------------------------------------------------------------
  // Everything here stands on the sanctuary platform, so every y is measured from
  // `CHANCEL_Y`. The shell's altar block is 1.35 tall centred at 1.76, which puts its top
  // at 2.435 — the height every fitting below sits on.
  const mensaY = 2.435;

  const runner = new Mesh(new BoxGeometry(4.6, 0.03, 7.5), materials.carpet);
  runner.position.set(0, CHANCEL_Y + 0.015, ALTAR_Z + 3.4);
  runner.receiveShadow = true;
  furnishings.add(runner);

  // The mensa and its frontal. The linen is the brightest non-emissive surface in the
  // building and it sits dead on the axis, which is what pulls the eye to the east end.
  place(kit.stoneBox, [0, mensaY + 0.07, ALTAR_Z], [4.7, 0.14, 2.15]);
  const frontal = new Mesh(new BoxGeometry(4.2, 1.3, 0.04), materials.linen);
  frontal.position.set(0, 1.76, ALTAR_Z + 0.97);
  furnishings.add(frontal);
  place(kit.gold, [0, 2.36, ALTAR_Z + 0.98], [4.2, 0.08, 0.03]);
  place(kit.gold, [0, 1.8, ALTAR_Z + 0.99], [0.1, 0.7, 0.03]);
  place(kit.gold, [0, 1.96, ALTAR_Z + 0.99], [0.44, 0.1, 0.03]);

  // Six candlesticks and a cross: the standard altar set, and six small flames at the far
  // end of a 55 m axis is exactly the cue that says something is happening down there.
  const setZ = ALTAR_Z - 0.4;
  for (let index = 0; index < 6; index += 1) {
    const cx = -1.65 + index * 0.66;
    rod(kit.bronzeRod, [cx, mensaY + 0.14, setZ], [cx, mensaY + 0.72, setZ], 0.035);
    place(kit.knop, [cx, mensaY + 0.42, setZ], [0.075, 0.06, 0.075]);
    place(kit.bronzeRod, [cx, mensaY + 0.75, setZ], [0.07, 0.07, 0.07]);
    candle(kit, cx, mensaY + 0.79, setZ, 0.42, 0.04);
  }
  place(kit.gold, [0, mensaY + 1.35, setZ - 0.25], [0.08, 1.25, 0.08]);
  place(kit.gold, [0, mensaY + 1.67, setZ - 0.25], [0.62, 0.08, 0.08]);

  // The reredos behind the altar: five gabled panels, the centre one tallest.
  for (let index = -2; index <= 2; index += 1) {
    const panelHeight = 3.4 - Math.abs(index) * 0.45;
    const panelZ = ALTAR_Z - 1.7;
    place(kit.stoneBox, [index * 1.22, CHANCEL_Y + panelHeight / 2, panelZ], [1.14, panelHeight, 0.3]);
    place(
      kit.stoneSpike,
      [index * 1.22, CHANCEL_Y + panelHeight + 0.42, panelZ],
      [0.86, 0.85, 0.42],
      [0, Math.PI / 4, 0],
    );
    if (index !== 0) continue;
    place(kit.gold, [index * 1.22, CHANCEL_Y + panelHeight * 0.62, panelZ + 0.17], [0.6, 0.9, 0.04]);
  }

  // The tabernacle canopy: a slender spire over the altar, rising past the top of the
  // screen. Everything else in the sanctuary sits below the screen's crest and is read
  // through a lattice of iron bars; the spire is the one part of the group that clears
  // them, and it is the reason the east end reads as a *place* rather than as a bright
  // window with some candles in front of it.
  const canopyFoot = CHANCEL_Y + 0.1;
  const canopyTop = CHANCEL_Y + 5.6;
  for (const cx of [-0.62, 0.62]) {
    for (const cz of [-0.62, 0.62]) {
      rod(kit.stoneBox, [cx, canopyFoot, ALTAR_Z + cz], [cx, canopyTop, ALTAR_Z + cz], 0.09);
    }
  }
  place(kit.stoneBox, [0, canopyTop, ALTAR_Z], [1.7, 0.22, 1.7]);
  for (const [gx, gz, yaw] of [
    [0, 0.85, 0],
    [0, -0.85, 0],
    [0.85, 0, Math.PI / 2],
    [-0.85, 0, Math.PI / 2],
  ] as ReadonlyArray<readonly [number, number, number]>) {
    place(kit.stoneSpike, [gx, canopyTop + 0.5, ALTAR_Z + gz], [0.75, 0.9, 0.2], [0, yaw, 0]);
  }
  place(kit.stoneSpike, [0, canopyTop + 1.3, ALTAR_Z], [0.82, 1.9, 0.82], [0, Math.PI / 4, 0]);
  // Crockets. Four knops up the spire are what stop a cone reading as a traffic bollard.
  for (let step = 0; step < 4; step += 1) {
    const t = 0.18 + step * 0.2;
    place(kit.knop, [0, canopyTop + 0.35 + t * 1.9, ALTAR_Z], [0.1, 0.1, 0.1]);
  }
  place(kit.gold, [0, canopyTop + 2.5, ALTAR_Z], [0.09, 0.62, 0.09]);
  place(kit.gold, [0, canopyTop + 2.6, ALTAR_Z], [0.34, 0.09, 0.09]);

  // Two sanctuary lamps on long chains, one either side of the altar. They hang where a
  // chandelier cannot — inside the chancel arch, below the apse vault — and they are the
  // only warm light *behind* the screen, which is what stops the sanctuary reading as a
  // flat lit backdrop with a silhouette in front of it.
  for (const side of [-1, 1]) {
    const lampX = side * 2.7;
    const lampZ = ALTAR_Z + 1.9;
    const bowlY = CHANCEL_Y + 3.3;
    for (let y = bowlY + 0.5; y < 15; y += 0.34) {
      const upright = Math.round((y - bowlY) / 0.34) % 2 === 0;
      place(kit.chainLink, [lampX, y, lampZ], [0.1, 0.1, 0.1], [0, upright ? 0 : Math.PI / 2, 0]);
    }
    for (const hang of [-0.22, 0.22]) {
      rod(
        kit.bronzeRod,
        [lampX + hang, bowlY + 0.52, lampZ],
        [lampX, bowlY + 0.14, lampZ],
        0.016,
      );
    }
    place(kit.knop, [lampX, bowlY, lampZ], [0.24, 0.15, 0.24]);
    candle(kit, lampX, bowlY + 0.06, lampZ, 0.1, 0.05);
  }

  // ---- banners -----------------------------------------------------------------------
  // Hung from alternating piers so the two colonnades do not mirror each other exactly —
  // a perfectly symmetric pair of banners reads as wallpaper.
  const bannerShape = new Shape();
  bannerShape.moveTo(-1.0, 0);
  bannerShape.lineTo(1.0, 0);
  bannerShape.lineTo(1.0, -4.85);
  bannerShape.lineTo(0, -5.4);
  bannerShape.lineTo(-1.0, -4.85);
  bannerShape.closePath();
  // Extruded rather than flat. A zero-thickness cloth has one normal; the extrusion gives
  // it edges facing -X and +Y that catch the sun and draw a lit rim down each side, which
  // is what stops it reading as a decal stuck on the pier.
  const bannerGeometry = new ExtrudeGeometry(bannerShape, { depth: 0.09, bevelEnabled: false });
  for (const [x, z] of [
    [-PIER_X, -3.5],
    [-PIER_X, 10.5],
    [PIER_X, 3.5],
    [PIER_X, -10.5],
  ] as ReadonlyArray<readonly [number, number]>) {
    banner(kit, furnishings, bannerGeometry, x, z + NAVE.pierRadius + 0.25, 13.0);
  }

  // ---- aisle statuary and memorials --------------------------------------------------
  // Everything here lives in light the sun never reaches. If the GI stage is off these are
  // black cut-outs; if it is on they are modelled by bounce off the arcade — which makes
  // them the cheapest read on whether the stage did anything.
  for (const side of [-1, 1]) {
    for (const bay of [3, 5, 7]) {
      // Bay centres, on the nave side of the arcade rather than out in the aisle. The
      // colonnade in this building is dense enough that a sightline from the nave floor
      // into an aisle bay is almost never clear: statues placed properly in the aisle were
      // invisible in three consecutive captures. Standing them against the arcade puts
      // them where the reference's are read from — in front of an opening, not behind one.
      const z = -HALF_DEPTH + bay * NAVE.bayPitch + NAVE.bayPitch / 2;
      statue(kit, side * 6.95, z, side > 0 ? -Math.PI / 2 : Math.PI / 2);
    }
    for (const bay of [2, 4, 6]) {
      const z = -HALF_DEPTH + bay * NAVE.bayPitch + NAVE.bayPitch / 2;
      memorial(kit, side * (AISLE_WALL_X - 0.35), z, 0);
    }
  }

  // ---- the two real lights -----------------------------------------------------------
  //
  // Both exist for the same reason: screen-space GI can only gather light off surfaces
  // that are *in the frame and lit*, and in both these places the surface that has to
  // receive the warm light is either facing away from the camera or is the reflective
  // floor directly beneath the source, where the gather radius of 8 m has nothing to
  // sample from. A point light is the only thing that puts light there.
  //
  // 1. The foreground candle stand. It sits on the polished marble that fills the bottom
  //    third of the frame, and that floor is the largest surface in the picture with no
  //    other warm source anywhere near it.
  const standLight = new PointLight(0xffb066, 6.5, 12, 2);
  standLight.position.set(-1.3, 3.3, 17.6);
  furnishings.add(standLight);
  // 2. The sanctuary. The altar is 55 m down the axis and stands *in front of* the lit
  //    lancets, so every surface of it that the camera can see faces away from the only
  //    light in the building. Without this it is a black block against bright glass.
  const altarLight = new PointLight(0xffc184, 18, 16, 2);
  altarLight.position.set(0, CHANCEL_Y + 2.6, ALTAR_Z + 2.6);
  furnishings.add(altarLight);

  // ---- resolve every batch into its single draw ---------------------------------------
  batches.bronzeRod.build(furnishings, "furnishings-bronze-rods", true);
  batches.chainLink.build(furnishings, "furnishings-chain", false);
  batches.flame.build(furnishings, "furnishings-flames", false);
  batches.gold.build(furnishings, "furnishings-gold", false);
  batches.halo.build(furnishings, "furnishings-halos", false);
  batches.ironBox.build(furnishings, "furnishings-iron-rails", true);
  batches.ironRod.build(furnishings, "furnishings-iron-rods", true);
  batches.ironSpike.build(furnishings, "furnishings-finials", true);
  batches.knop.build(furnishings, "furnishings-knops", false);
  batches.ring.build(furnishings, "furnishings-rings", true);
  batches.robe.build(furnishings, "furnishings-statues", true);
  batches.stoneBox.build(furnishings, "furnishings-stone", true);
  batches.stoneHead.build(furnishings, "furnishings-heads", false);
  batches.stoneSpike.build(furnishings, "furnishings-gables", true);
  batches.wax.build(furnishings, "furnishings-wax", false);

  return furnishings;
}
