// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// The surface library. Owned by the textures lane.
//
// Contract: this file resolves textures through `ctx.assets` (so they go through the
// project's asset pipeline and ship compressed) and dresses the materials `cathedral.ts`
// already built. It creates no geometry, positions nothing, and never edits that file.
//
// A hard constraint learned the expensive way: the pipeline compresses to block formats
// whose block is 4x4, so **every source texture's width and height must be divisible by
// four**. A 1254x1254 source compiles without complaint and then fails at draw time with
// `GPUValidationError: size is not a multiple of the block width`.
//
// Three things this file will not do, and why:
//
//   It does not change how bright any surface is. Every map is authored to a measured
//   mean (`ALBEDO_MEAN`, `GLASS_LUMINANCE`) and the material's existing colour is divided
//   by that mean before it multiplies the map, so a lit pier and a lit window average
//   exactly the value they averaged when they were flat colour. Exposure, SSGI intensity,
//   godray density and the deliberate half-value on the aisle glass were all tuned
//   against those values; a texture pass that quietly doubles them invalidates the lot.
//
//   It does not decide hue on the stone. The maps are desaturated to neutral on the way
//   in, so the palette (and, on the carved shell, the vertex colours) still say what
//   colour the building is. The map only says how it varies.
//
//   It does not touch UVs on the stone. The shell is merged geometry drawn as instanced
//   meshes — cylinders, extruded panels, welded tracery, tori and rings all in one draw —
//   and there is no single `repeat` that is right for all of it. The stone is mapped
//   triplanar from world position instead, so one metre of stone is one metre of texture
//   everywhere and the courses run continuously across the joins.
import {
  type BufferGeometry,
  ClampToEdgeWrapping,
  Color,
  Float32BufferAttribute,
  type Group,
  LinearSRGBColorSpace,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  NoColorSpace,
  RepeatWrapping,
  type RingGeometry,
  SRGBColorSpace,
  type Texture,
} from "three";
import {
  bumpMap,
  float,
  mix,
  normalWorld,
  positionWorld,
  smoothstep,
  texture as textureNode,
  triplanarTexture,
  vec3,
  vertexColor,
} from "three/tsl";
import { palette } from "./palette.js";

/** Every texture this file needs, by the name the asset pipeline knows it as. */
export const SURFACE_SOURCES = {
  glassCool: "cathedral-glass-clerestory-cool.png",
  glassLancet: "cathedral-glass-lancet.png",
  glassRose: "cathedral-glass-rose.png",
  glassWarm: "cathedral-glass-clerestory-warm.png",
  limestone: "cathedral-limestone.png",
  limestoneRelief: "cathedral-limestone-relief.png",
  vaultstone: "cathedral-vaultstone.png",
  vaultstoneRelief: "cathedral-vaultstone-relief.png",
} as const;

type SurfaceName = keyof typeof SURFACE_SOURCES;
export type ISurfaceTextures = Record<SurfaceName, Texture>;

/** The subset of `ctx.assets` this file uses. */
export interface IAssetSource {
  texture(name: string): Promise<Texture>;
}

/**
 * The linear mean each stone albedo map was authored to, per channel.
 *
 * The maps are colour-neutral on average by construction, so dividing the material's
 * colour by this number and multiplying it back through the map leaves the average
 * surface exactly as bright as it was before the map existed. Change it here only when
 * the generator that wrote the PNGs changes its target.
 */
const ALBEDO_MEAN = 0.25;

/** Measured mean linear luminance of each glass map, over its opaque pixels. */
const GLASS_LUMINANCE: Record<"glassCool" | "glassLancet" | "glassRose" | "glassWarm", number> = {
  glassCool: 0.4797,
  glassLancet: 0.2502,
  glassRose: 0.3496,
  glassWarm: 0.6065,
};

/**
 * One stone, as this file needs it: two maps, the size the source was photographed at,
 * and how hard to push its relief into the surface normal.
 */
interface IStone {
  albedo: Texture;
  bump: number;
  relief: Texture;
  tileMetres: number;
}

/** Roughness, read off the relief: the recessed mortar in a wall is also the rough part. */
const ROUGH_PROUD = 0.74;
const ROUGH_RECESSED = 0.97;

/** How dark the base of a wall gets, and how far up the staining reaches. */
const GRIME_FLOOR = 0.55;
const GRIME_TOP = 4.5;

/**
 * Linear luminance below which a stone material is the dark stone rather than the pale one.
 *
 * Matching on exact palette hexes broke the moment the shell was rebuilt around vertex
 * colours and the main material turned white; how *light* a stone material is survives
 * that kind of change, which is the whole reason the split is written this way.
 */
const SHADOW_STONE_MAX_LUMINANCE = 0.1;

/**
 * `colorNode` and `roughnessNode` exist on every node material the WebGPU renderer builds,
 * but the shell is made of plain `three` materials whose types know nothing about nodes.
 * The renderer copies own properties across when it converts one, so setting the nodes
 * before the first frame works; the compiler just cannot see it.
 */
type INodeMaterial = {
  colorNode?: unknown;
  normalNode?: unknown;
  roughnessNode?: unknown;
};

/** Rec. 709 luminance of a colour already in linear working space. */
function luminance(colour: Color): number {
  return 0.2126 * colour.r + 0.7152 * colour.g + 0.0722 * colour.b;
}

let loaded: ISurfaceTextures | undefined;

/**
 * Resolves every surface texture. Call from `Scene.load`, not from `enter`.
 *
 * The stone has to be on the materials before the first frame is drawn: the screen-space
 * passes gather from what is on screen, so a texture that arrives three frames late is a
 * texture the first three frames of GI were computed without.
 */
export async function loadSurfaces(assets: IAssetSource): Promise<ISurfaceTextures> {
  const names = Object.keys(SURFACE_SOURCES) as SurfaceName[];
  const textures = await Promise.all(names.map((name) => assets.texture(SURFACE_SOURCES[name])));
  const resolved = {} as ISurfaceTextures;
  names.forEach((name, index) => {
    const texture = textures[index];
    if (texture === undefined) throw new Error(`TN_SURFACES_MISSING: ${SURFACE_SOURCES[name]}`);
    resolved[name] = texture;
  });
  loaded = resolved;
  return resolved;
}

/**
 * Dresses the cathedral shell in stone and glass, and returns it so the call site stays
 * one expression.
 *
 * Materials are found by traversing rather than handed in, because `createCathedral` owns
 * them and this lane does not edit that file. Structure is everything unmetallic; the
 * marble floor, the marble bands and the ironwork all carry metalness and are left alone.
 */
export function applySurfaces(cathedral: Group, textures?: ISurfaceTextures): Group {
  const maps = textures ?? loaded;
  if (maps === undefined) {
    throw new Error("TN_SURFACES_NOT_LOADED: call loadSurfaces() from Scene.load() first.");
  }

  const pale = new Set<MeshStandardMaterial>();
  const dark = new Set<MeshStandardMaterial>();
  const glass: Mesh[] = [];
  cathedral.traverse((object) => {
    if (!(object instanceof Mesh)) return;
    const material = object.material;
    if (material instanceof MeshStandardMaterial) {
      if (material.metalness !== 0) return;
      if (luminance(material.color) < SHADOW_STONE_MAX_LUMINANCE) dark.add(material);
      else pale.add(material);
      return;
    }
    // `toneMapped: false` is only ever set on the glass.
    if (material instanceof MeshBasicMaterial && !material.toneMapped) glass.push(object);
  });

  const limestone: IStone = {
    albedo: maps.limestone,
    bump: 0.45,
    relief: maps.limestoneRelief,
    tileMetres: 3,
  };
  const vaultstone: IStone = {
    albedo: maps.vaultstone,
    bump: 0.32,
    relief: maps.vaultstoneRelief,
    tileMetres: 2,
  };
  for (const material of pale) dressStone(material, limestone);
  for (const material of dark) dressStone(material, vaultstone);
  for (const mesh of glass) dressGlass(mesh, maps);
  return cathedral;
}

/** Triplanar albedo and relief, plus the dirt that collects where a wall meets a floor. */
function dressStone(material: MeshStandardMaterial, stone: IStone): void {
  prepare(stone.albedo, SRGBColorSpace, 8);
  // Relief is data, not colour. Read through an sRGB transfer the joints come back far
  // too shallow and every pier in the building turns into polished granite.
  prepare(stone.relief, NoColorSpace, 4);

  const scale = float(1 / stone.tileMetres);
  const project = (map: Texture) =>
    triplanarTexture(textureNode(map), null, null, scale, positionWorld, normalWorld);

  const albedoNode = project(stone.albedo);
  const reliefNode = project(stone.relief).r;
  // The material's own colour still decides how light this stone is; the map only says
  // how it varies. Dividing by the map's measured mean is what keeps those jobs apart.
  const tint = material.color.clone().multiplyScalar(1 / ALBEDO_MEAN);
  // Weathering, not a gradient: the darkening at the foot of a wall is modulated by the
  // stone's own pattern, so it follows the courses instead of drawing a clean horizon.
  const staining = mix(
    float(GRIME_FLOOR).add(albedoNode.r.mul(0.3)),
    float(1),
    smoothstep(float(0.2), float(GRIME_TOP), positionWorld.y),
  );

  let colour = albedoNode.rgb.mul(vec3(tint.r, tint.g, tint.b)).mul(staining);
  // The carved shell is one merged material tinted per vertex — plinth dark, capital
  // bright. Replacing `colorNode` drops that attribute unless it is multiplied back in,
  // and the building flattens into one value the moment it is forgotten.
  if (material.vertexColors) colour = colour.mul(vertexColor().rgb);

  const nodes = material as unknown as INodeMaterial;
  nodes.colorNode = colour;
  nodes.roughnessNode = mix(float(ROUGH_RECESSED), float(ROUGH_PROUD), reliefNode);
  // The joints have to catch the light, not just be a darker colour. `bumpMap` takes the
  // screen-space derivative of the relief, so it works off the triplanar sample without a
  // tangent frame — which the merged shell does not have a usable one of anyway.
  nodes.normalNode = bumpMap(reliefNode, float(stone.bump));
}

function prepare(map: Texture, colorSpace: string, anisotropy: number): void {
  map.wrapS = RepeatWrapping;
  map.wrapT = RepeatWrapping;
  map.colorSpace = colorSpace;
  map.anisotropy = anisotropy;
}

/**
 * Leaded glass on one window.
 *
 * Which panel it gets comes from the flat colour it is replacing: the arcade already
 * alternates warm and cool lights down the nave, so reading that back keeps the rhythm
 * the building was designed with instead of inventing a second one.
 */
function dressGlass(mesh: Mesh, maps: ISurfaceTextures): void {
  const material = mesh.material;
  if (!(material instanceof MeshBasicMaterial)) return;
  const geometry = mesh.geometry;
  const ring = ringRadius(geometry);
  // The eye at the centre of the wheel is a disc barely a metre across, and the rose map
  // already draws one. Texturing it a second time only fights the tracery in front of it.
  if (ring !== undefined && ring < ROSE_MIN_RADIUS) return;

  const hex = material.color.getHex();
  const key: keyof typeof GLASS_LUMINANCE =
    ring !== undefined
      ? "glassRose"
      : hex === palette.glassWarm
        ? "glassWarm"
        : hex === palette.glassCool
          ? "glassCool"
          : "glassLancet";
  const map = maps[key];

  // Planes and rings already carry the 0..1 UVs one panel wants. The east lancets are
  // three extruded shapes welded into one mesh and carry UVs in metres, mixed with the
  // side walls' own; those get one panel projected across the group, which at fifty
  // metres down the nave is the difference between glass and a blue slab, and nothing
  // finer than that is resolvable anyway.
  if (geometry.type !== "PlaneGeometry" && ring === undefined) projectPanelUV(geometry);

  map.colorSpace = SRGBColorSpace;
  map.anisotropy = 4;
  map.wrapS = ClampToEdgeWrapping;
  map.wrapT = ClampToEdgeWrapping;
  material.map = map;
  // Keep the window exactly as bright as the flat colour it replaces and let the map
  // supply the hue. Leaving the tint on multiplies colour in twice — the aisle lights
  // were deliberately set to half value, and a white base colour throws that away.
  const gain = luminance(material.color) / GLASS_LUMINANCE[key];
  material.color.setRGB(gain, gain, gain, LinearSRGBColorSpace);
  // The rose map is transparent outside its wheel, so the panel is a wheel even when the
  // geometry under it is not.
  material.alphaTest = key === "glassRose" ? 0.5 : 0;
  material.needsUpdate = true;
}

/** Anything smaller than this and a disc of glass is the rose's eye, not the rose. */
const ROSE_MIN_RADIUS = 3;

/** Outer radius if this geometry is a disc or ring, otherwise undefined. */
function ringRadius(geometry: BufferGeometry): number | undefined {
  if (geometry.type !== "RingGeometry") return undefined;
  return (geometry as RingGeometry).parameters.outerRadius;
}

/** Rewrites `uv` so one copy of the panel covers the geometry's local XY extent. */
function projectPanelUV(geometry: BufferGeometry): void {
  const position = geometry.getAttribute("position");
  let minX = Number.POSITIVE_INFINITY;
  let minY = Number.POSITIVE_INFINITY;
  let maxX = Number.NEGATIVE_INFINITY;
  let maxY = Number.NEGATIVE_INFINITY;
  for (let index = 0; index < position.count; index += 1) {
    minX = Math.min(minX, position.getX(index));
    maxX = Math.max(maxX, position.getX(index));
    minY = Math.min(minY, position.getY(index));
    maxY = Math.max(maxY, position.getY(index));
  }
  const spanX = Math.max(maxX - minX, Number.EPSILON);
  const spanY = Math.max(maxY - minY, Number.EPSILON);
  const uv = new Float32Array(position.count * 2);
  for (let index = 0; index < position.count; index += 1) {
    uv[index * 2] = (position.getX(index) - minX) / spanX;
    uv[index * 2 + 1] = (position.getY(index) - minY) / spanY;
  }
  geometry.setAttribute("uv", new Float32BufferAttribute(uv, 2));
}
