// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// The surface library. Owned by the textures lane.
//
// Contract: this file resolves textures through `ctx.assets` (so they go through the
// project's asset pipeline and ship compressed) and dresses the materials `cathedral.ts`
// already built. It creates no geometry, positions nothing, and never edits that file.
//
// A hard constraint learned the expensive way: the pipeline compresses to block formats
// whose block is 4x4, so **every source texture's width and height must be divisible by
// four**. A 1254x1254 source compiles without complaint and then fails at draw time with
// `GPUValidationError: size is not a multiple of the block width`.
//
// Three things this file will not do, and why:
//
//   It does not change how bright any surface is. Every map is authored to a measured
//   mean (`ALBEDO_MEAN`, `GLASS_LUMINANCE`) and the material's existing colour is divided
//   by that mean before it multiplies the map, so a lit pier and a lit window average
//   exactly the value they averaged when they were flat colour. Exposure, SSGI intensity,
//   godray density and the deliberate half-value on the aisle glass were all tuned
//   against those values; a texture pass that quietly doubles them invalidates the lot.
//
//   It does not decide hue on the stone. The maps are desaturated to neutral on the way
//   in, so the palette (and, on the carved shell, the vertex colours) still say what
//   colour the building is. The map only says how it varies.
//
//   It does not touch UVs on the stone. The shell is merged geometry drawn as instanced
//   meshes — cylinders, extruded panels, welded tracery, tori and rings all in one draw —
//   and there is no single `repeat` that is right for all of it. The stone is mapped
//   triplanar from world position instead, so one metre of stone is one metre of texture
//   everywhere and the courses run continuously across the joins.
import {
  type BufferGeometry,
  ClampToEdgeWrapping,
  Color,
  DoubleSide,
  Float32BufferAttribute,
  type Group,
  LinearSRGBColorSpace,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  NoColorSpace,
  RepeatWrapping,
  type RingGeometry,
  SRGBColorSpace,
  type Texture,
} from "three";
import {
  bumpMap,
  cameraViewMatrix,
  clamp,
  float,
  frontFacing,
  mix,
  mx_fractal_noise_float,
  normalWorld,
  positionWorld,
  smoothstep,
  texture as textureNode,
  transformDirection,
  triplanarTexture,
  uv,
  vec2,
  vec3,
  vec4,
  vertexColor,
} from "three/tsl";
import { palette } from "./palette.js";

/** Every texture this file needs, by the name the asset pipeline knows it as. */
export const SURFACE_SOURCES = {
  banner: "cathedral-banner.png",
  floorRough: "cathedral-floor-rough.png",
  glassCool: "cathedral-glass-clerestory-cool.png",
  glassLancet: "cathedral-glass-lancet.png",
  glassRose: "cathedral-glass-rose.png",
  glassWarm: "cathedral-glass-clerestory-warm.png",
  limestone: "cathedral-limestone.png",
  limestoneRelief: "cathedral-limestone-normal.png",
  vaultstone: "cathedral-vaultstone.png",
  vaultstoneRelief: "cathedral-vaultstone-normal.png",
} as const;

// Each `*-normal.png` is four channels of one map: `rg` is a tangent-space normal with z
// reconstructed rather than stored, `b` is cavity — 1 on an open face, dark in a mortar bed
// — and `a` is the greyscale relief that has always driven roughness, carried across
// unchanged. One map, three triplanar samples: exactly what the greyscale relief map on its
// own used to cost, so a real normal and a cavity arrive for no extra fetch.
//
// The `-normal` suffix is load bearing rather than descriptive. The asset pipeline matches
// it and switches that file from ETC1S to UASTC, which is the only codec in this project
// that keeps four channels independent of each other; ETC1S is a luma-plus-palette codec
// and would hand back a normal map that is an approximation of its own average colour.

type SurfaceName = keyof typeof SURFACE_SOURCES;
export type ISurfaceTextures = Record<SurfaceName, Texture>;

/** The subset of `ctx.assets` this file uses. */
export interface IAssetSource {
  texture(name: string): Promise<Texture>;
}

/**
 * The linear mean each stone albedo map was authored to, per channel.
 *
 * The maps are colour-neutral on average by construction, so dividing the material's
 * colour by this number and multiplying it back through the map leaves the average
 * surface exactly as bright as it was before the map existed. Change it here only when
 * the generator that wrote the PNGs changes its target.
 */
const ALBEDO_MEAN = 0.25;

/** Measured mean linear luminance of each glass map, over its opaque pixels. */
type GlassName = "glassCool" | "glassLancet" | "glassRose" | "glassWarm";

const GLASS_LUMINANCE: Record<GlassName, number> = {
  glassCool: 0.4291,
  // 0.1260, not the 0.2655 of the panel this replaced. The new lancet is a hand-authored
  // three-saint light on a deep blue ground, and it is genuinely about half as bright. The
  // gain divides by this number, so recording it is what keeps the window as bright on
  // screen as the flat colour it stands in for — leaving the old value here would have
  // halved every lancet in the building and quietly invalidated the exposure, SSGI and
  // godray values that were tuned against it.
  glassLancet: 0.126,
  glassRose: 0.1856,
  glassWarm: 0.5209,
};

/**
 * Width over height of each panel as authored.
 *
 * A lancet panel is drawn four times taller than it is wide because that is the shape of
 * the opening it covers. Stretched to fit whatever rectangle it lands on, the saints go
 * dumpy; `fitPanel` uses these to keep the panel square-on and tile it instead.
 */
const GLASS_ASPECT: Record<GlassName, number> = {
  glassCool: 512 / 1024,
  glassLancet: 432 / 2172,
  glassRose: 1,
  glassWarm: 512 / 1024,
};

/**
 * A material this rough is the floor: `cathedral.ts` keeps it the only low-roughness
 * surface in the building, because otherwise screen-space reflection has nothing to
 * return. Whatever number it uses stays the *polished* roughness — the mask only says
 * where the polish is not.
 */
const FLOOR_MAX_ROUGHNESS = 0.3;
/** Unpolished joints between inlay pieces. High enough that the reflection stops there. */
const FLOOR_GROUT_ROUGHNESS = 0.55;

/**
 * Metalness at or below which a material is polished stone rather than metal.
 *
 * `cathedral.ts` gives its two marbles a token 0.1 for the sheen; its ironwork carries 0.7.
 * Anything between is not a case this building has, so the threshold only has to separate
 * those two and leave room for a marble that gains a little more sheen later.
 */
const POLISHED_MAX_METALNESS = 0.15;

/**
 * One stone, as this file needs it: two maps, the size the source was photographed at,
 * how hard to push its relief into the surface normal, and the mean its cavity channel
 * was measured at.
 */
interface IStone {
  albedo: Texture;
  /**
   * Albedo-weighted mean of the packed map's cavity channel, straight off the generator.
   *
   * Cavity multiplies the colour, so without dividing by this the pass is a dimmer switch
   * on the whole building — nine per cent of it, which is more than the difference between
   * two of the exposure values this project has argued about. Weighted by the albedo and
   * not a plain mean, because the shader multiplies the two together and it is the product
   * whose average has to come out unchanged.
   */
  cavityMean: number;
  /** Multiplier on the map's tangent-space x and y before z is rebuilt from them. */
  normalScale: number;
  /** `rg` normal, `b` cavity, `a` recess. See the note on `SURFACE_SOURCES`. */
  packed: Texture;
  tileMetres: number;
}

/**
 * Mean linear luminance of the banner map, over the whole panel.
 *
 * Measured over *every* texel, not over the cloth alone. Cloth-only is the intuitive
 * reference — the gold device replaces boxes that were separate meshes, so it feels like it
 * should not count — and it is wrong, because it is a mean the material never samples. A
 * banner four metres up covers about sixty pixels of a 1600-wide frame, so it reads three or
 * four mip levels down, where every texel is already an average of an 8x8 block and the
 * braid and the device have bled into the cloth. Calibrating on cloth-only measured 0.02206
 * and the banner came back 27% hot against the flat colour it was standing in for.
 *
 * The remaining trade is that at arm's length the cloth is a little darker than the flat
 * navy, since up close the gold is resolved rather than averaged in. That is the right way
 * round: every complaint about this banner has been that it is too bright.
 *
 * The material's `emissive` floor is untouched: it is added after lighting and `colorNode`
 * does not reach it, which is what keeps a navy cloth on an unlit pier from rounding to
 * black whether or not it has a map.
 */
const BANNER_LUMINANCE = 0.03677;

/** Roughness, read off the relief: the recessed mortar in a wall is also the rough part. */
const ROUGH_PROUD = 0.74;
const ROUGH_RECESSED = 0.97;

/** How dark the base of a wall gets, and how far up the staining reaches. */
const GRIME_FLOOR = 0.55;
const GRIME_TOP = 4.5;

/**
 * The wavelength and depth of the low-frequency variation laid over every stone surface.
 *
 * A 3 m tile repeated across a 92 m building repeats thirty times, and the eye finds that
 * long before it finds any individual block. This is the standard answer: a second signal
 * an order of magnitude larger than the tile, multiplied over the albedo, so no two bays
 * average the same value even though they sample the same texels.
 *
 * It is procedural rather than a macro texture on purpose — a texture would be a fourth
 * map and a fourth triplanar sample for a signal that is three octaves of noise. The
 * noise is mean-zero, so `1 + amount * noise` averages exactly one and the calibration
 * every other constant in this file was tuned against survives untouched.
 *
 * 22 m, not 13: at 13 m the variation landed inside a single bay and read as dirt on one
 * pier rather than as one bay being a different quarry batch from the next.
 */
const MACRO_METRES = 22;
const MACRO_AMOUNT = 0.22;
/** How much of that same variation reaches roughness. Damp patches are duller patches. */
const MACRO_ROUGHNESS = 0.05;

/**
 * Linear luminance below which a stone material is the dark stone rather than the pale one.
 *
 * Matching on exact palette hexes broke the moment the shell was rebuilt around vertex
 * colours and the main material turned white; how *light* a stone material is survives
 * that kind of change, which is the whole reason the split is written this way.
 */
const SHADOW_STONE_MAX_LUMINANCE = 0.1;

/**
 * `colorNode` and `roughnessNode` exist on every node material the WebGPU renderer builds,
 * but the shell is made of plain `three` materials whose types know nothing about nodes.
 * The renderer copies own properties across when it converts one, so setting the nodes
 * before the first frame works; the compiler just cannot see it.
 */
type INodeMaterial = {
  colorNode?: unknown;
  normalNode?: unknown;
  roughnessNode?: unknown;
};

/** Rec. 709 luminance of a colour already in linear working space. */
function luminance(colour: Color): number {
  return 0.2126 * colour.r + 0.7152 * colour.g + 0.0722 * colour.b;
}

/**
 * `?off=banner` leaves a surface in its flat material colour.
 *
 * The same trick `postprocessing.ts` uses on the render stages, and for the same reason: an
 * A/B of a calibrated map against the colour it is calibrated to has to differ by the map
 * and nothing else. Comparing two captures taken minutes apart is not that — this file, the
 * geometry and the material all moved between them, and the first attempt at diagnosing a
 * blown-out banner blamed the exposure on the strength of exactly that comparison.
 */
function surfaceOff(name: string): boolean {
  if (typeof globalThis.location === "undefined") return false;
  const off = new URLSearchParams(globalThis.location.search).get("off");
  return off !== null && off.split(",").some((entry) => entry.trim() === name);
}

let loaded: ISurfaceTextures | undefined;

/**
 * Resolves every surface texture. Call from `Scene.load`, not from `enter`.
 *
 * The stone has to be on the materials before the first frame is drawn: the screen-space
 * passes gather from what is on screen, so a texture that arrives three frames late is a
 * texture the first three frames of GI were computed without.
 */
export async function loadSurfaces(assets: IAssetSource): Promise<ISurfaceTextures> {
  const names = Object.keys(SURFACE_SOURCES) as SurfaceName[];
  const textures = await Promise.all(names.map((name) => assets.texture(SURFACE_SOURCES[name])));
  const resolved = {} as ISurfaceTextures;
  names.forEach((name, index) => {
    const texture = textures[index];
    if (texture === undefined) throw new Error(`TN_SURFACES_MISSING: ${SURFACE_SOURCES[name]}`);
    resolved[name] = texture;
  });
  loaded = resolved;
  return resolved;
}

/**
 * Dresses the cathedral shell in stone and glass, and returns it so the call site stays
 * one expression.
 *
 * Materials are found by traversing rather than handed in, because `createCathedral` owns
 * them and this lane does not edit that file. Structure is everything unmetallic; the
 * marble floor, the marble bands and the ironwork all carry metalness and are left alone.
 */
export function applySurfaces(cathedral: Group, textures?: ISurfaceTextures): Group {
  const maps = textures ?? loaded;
  if (maps === undefined) {
    throw new Error("TN_SURFACES_NOT_LOADED: call loadSurfaces() from Scene.load() first.");
  }

  const pale = new Set<MeshStandardMaterial>();
  const dark = new Set<MeshStandardMaterial>();
  const floor = new Set<MeshStandardMaterial>();
  const glass: Mesh[] = [];
  cathedral.traverse((object) => {
    if (!(object instanceof Mesh)) return;
    const material = object.material;
    if (material instanceof MeshStandardMaterial) {
      if (material.roughness <= FLOOR_MAX_ROUGHNESS && material.map !== null) {
        floor.add(material);
        return;
      }
      // Polished stone that never received a map: the chancel steps and platform, which
      // `cathedral.ts` builds out of `marbleBand` at roughness 0.2 and metalness 0.1. The
      // guard below reads that 0.1 as "this is ironwork, leave it alone" and skips it, so
      // it stayed a smooth, unmapped slab. That was invisible while the sanctuary was dark
      // and became the loudest thing in the altar vantage the moment `lighting.ts` put a
      // room environment behind it: a surface at roughness 0.2 with an environment to
      // reflect returns the clerestory band whatever its albedo says, so a near-black step
      // rendered as a flat white plane.
      //
      // Dressed as stone rather than as floor, because it *is* stone — steps in a chancel,
      // not a mirror — and `dressStone`'s roughness runs 0.74 to 0.97 off the relief, which
      // is what stops the reflection.
      if (material.metalness > 0 && material.metalness <= POLISHED_MAX_METALNESS) {
        if (material.roughness <= FLOOR_MAX_ROUGHNESS && material.map === null) {
          dark.add(material);
          return;
        }
      }
      if (material.metalness !== 0) return;
      if (luminance(material.color) < SHADOW_STONE_MAX_LUMINANCE) dark.add(material);
      else pale.add(material);
      return;
    }
    // `toneMapped: false` is only ever set on the glass.
    if (material instanceof MeshBasicMaterial && !material.toneMapped) glass.push(object);
  });

  // The two `cavityMean` numbers are the generator's own measurements of the maps in
  // `assets/`, not estimates. Rebake a stone and this number moves with it.
  const limestone: IStone = {
    albedo: maps.limestone,
    cavityMean: 0.9085,
    normalScale: 1,
    packed: maps.limestoneRelief,
    tileMetres: 3,
  };
  const vaultstone: IStone = {
    albedo: maps.vaultstone,
    cavityMean: 0.9161,
    // 0.8 rather than 1: the vault stone's albedo is the contrastier of the two
    // photographs, so the same bake gave it a mean slope of 13.1 degrees against the
    // limestone's 11.7 for relief that is physically shallower, not deeper.
    normalScale: 0.8,
    packed: maps.vaultstoneRelief,
    tileMetres: 2,
  };
  for (const material of pale) dressStone(material, limestone);
  for (const material of dark) dressStone(material, vaultstone);
  for (const material of floor) dressFloor(material, maps.floorRough);
  for (const mesh of glass) dressGlass(mesh, maps);
  return cathedral;
}

/** Triplanar albedo and relief, plus the dirt that collects where a wall meets a floor. */
function dressStone(material: MeshStandardMaterial, stone: IStone): void {
  prepare(stone.albedo, SRGBColorSpace, 8);
  // The packed map is data, not colour. Read through an sRGB transfer the joints come back
  // far too shallow and every pier in the building turns into polished granite; a normal
  // read that way is worse still, because the transfer is applied to x and y and not to the
  // z they are reconstructed against, so the vectors stop being unit length.
  prepare(stone.packed, NoColorSpace, 4);

  const scale = float(1 / stone.tileMetres);
  const project = (map: Texture) =>
    triplanarTexture(textureNode(map), null, null, scale, positionWorld, normalWorld);

  const albedoNode = project(stone.albedo);
  const packed = projectPacked(stone);
  const reliefNode = packed.recess;
  // The material's own colour still decides how light this stone is; the map only says
  // how it varies. Dividing by the map's measured mean is what keeps those jobs apart.
  const tint = material.color.clone().multiplyScalar(1 / ALBEDO_MEAN);
  // Three octaves from 22 m down to 5.5 m, mean zero. Sampled in world space like
  // everything else here, so it crosses the joins between merged pieces without a seam.
  const macro = mx_fractal_noise_float(positionWorld.mul(float(1 / MACRO_METRES)), 3, 2, 0.5);
  // Weathering, not a gradient: the darkening at the foot of a wall is modulated by the
  // stone's own pattern, so it follows the courses instead of drawing a clean horizon.
  const staining = mix(
    float(GRIME_FLOOR).add(albedoNode.r.mul(0.3)),
    float(1),
    smoothstep(float(0.2), float(GRIME_TOP), positionWorld.y),
  );

  let colour = albedoNode.rgb
    .mul(vec3(tint.r, tint.g, tint.b))
    .mul(staining)
    .mul(surfaceOff("macro") ? float(1) : float(1).add(macro.mul(float(MACRO_AMOUNT))))
    // Cavity. Divided by the mean it was measured at, so the mortar beds go down and
    // nothing else moves — the same bargain every other map in this file strikes.
    .mul(surfaceOff("cavity") ? float(1) : packed.cavity.div(float(stone.cavityMean)));
  // The carved shell is one merged material tinted per vertex — plinth dark, capital
  // bright. Replacing `colorNode` drops that attribute unless it is multiplied back in,
  // and the building flattens into one value the moment it is forgotten.
  if (material.vertexColors) colour = colour.mul(vertexColor().rgb);

  const nodes = material as unknown as INodeMaterial;
  nodes.colorNode = colour;
  const roughness = mix(float(ROUGH_RECESSED), float(ROUGH_PROUD), reliefNode);
  nodes.roughnessNode = surfaceOff("macro")
    ? roughness
    : clamp(roughness.add(macro.mul(float(MACRO_ROUGHNESS))), float(0), float(1));
  // A real normal, blended across the same three projections the albedo uses.
  //
  // What this replaces was `bumpMap(relief, 0.25)`, and the value was 0.25 rather than the
  // 0.45 it wanted because `bumpMap` differences the height in *screen* space: the strength
  // of the effect therefore depended on how far away the wall was, and at any usable value
  // the regular course pattern turned into a honeycomb weave across every mid-distance
  // wall — texture noise reading as knitted fabric. A sampled normal has no such
  // dependence. It is mip-filtered like any other texture, so it flattens toward the
  // geometric normal with distance instead of aliasing into a pattern, which is why the
  // relief can now be authored at its real depth and still be quiet at the far end of the
  // nave.
  nodes.normalNode = surfaceOff("stonenormal")
    ? bumpMap(reliefNode, float(0.25))
    : transformDirection(packed.normal, cameraViewMatrix);
}

/**
 * Samples one packed map on all three world planes and returns what each channel meant.
 *
 * Three samples, hand-written rather than three calls to `triplanarTexture`, because a
 * normal cannot be blended the way a colour can: the three projections disagree about
 * which way is up, and averaging their raw vectors flattens the relief toward nothing on
 * every surface that is not axis-aligned. The plane assignments and the blend weights are
 * copied from `triplanarTexture` itself so the normal lands on the same texels as the
 * albedo — a groove sitting one plane away from its own dark line is worse than no groove.
 */
function projectPacked(stone: IStone) {
  const position = positionWorld.mul(float(1 / stone.tileMetres));
  const map = stone.packed;
  const sx = textureNode(map, position.yz);
  const sy = textureNode(map, position.zx);
  const sz = textureNode(map, position.xy);

  const axis = normalWorld.abs().normalize();
  const weight = axis.div(axis.dot(vec3(1, 1, 1)));

  const blend = (a: typeof sx.b, b: typeof sx.b, c: typeof sx.b) =>
    a.mul(weight.x).add(b.mul(weight.y)).add(c.mul(weight.z));

  // z is rebuilt rather than stored: two channels describe a unit vector completely, and
  // the third is worth more as the cavity.
  const decode = (sample: typeof sx) => {
    const xy = sample.rg.mul(2).sub(1).mul(float(stone.normalScale));
    return vec3(xy.x, xy.y, xy.dot(xy).oneMinus().max(float(0)).sqrt());
  };

  // The whiteout blend: each projection's tangent normal is added onto the geometric
  // normal's other two components, and the component along the projection axis keeps the
  // geometric normal's sign. That sign is the whole reason for the form — without it every
  // surface facing -x reads its relief mirrored, and a wall and the wall opposite it are
  // lit as if the sun were on different sides of the building.
  const surface = normalWorld;
  const tx = decode(sx);
  const ty = decode(sy);
  const tz = decode(sz);
  const wx = vec3(tx.z.abs().mul(surface.x), tx.x.add(surface.y), tx.y.add(surface.z));
  const wy = vec3(ty.y.add(surface.x), ty.z.abs().mul(surface.y), ty.x.add(surface.z));
  const wz = vec3(tz.x.add(surface.x), tz.y.add(surface.y), tz.z.abs().mul(surface.z));

  return {
    cavity: blend(sx.b, sy.b, sz.b),
    normal: wx.mul(weight.x).add(wy.mul(weight.y)).add(wz.mul(weight.z)).normalize(),
    recess: blend(sx.a, sy.a, sz.a),
  };
}

/**
 * Breaks the floor's mirror where a real floor is not a mirror.
 *
 * One uniform roughness across the whole nave floor reads as water. The mask says where
 * the polish is missing — the joints between inlay pieces, the duller dark stone, and
 * broad patches of wear — and the roughness runs from whatever `cathedral.ts` set as the
 * polished value up to `FLOOR_GROUT_ROUGHNESS` across it.
 */
function dressFloor(material: MeshStandardMaterial, mask: Texture): void {
  const albedo = material.map;
  if (albedo === null) return;
  // The mask is drawn on the albedo's own image, so it has to be sampled with the albedo's
  // own transform. Copying it is what keeps a joint in the roughness over the joint in the
  // pattern instead of a tile and a half away from it.
  mask.wrapS = albedo.wrapS;
  mask.wrapT = albedo.wrapT;
  mask.repeat.copy(albedo.repeat);
  mask.offset.copy(albedo.offset);
  mask.center.copy(albedo.center);
  mask.rotation = albedo.rotation;
  mask.anisotropy = albedo.anisotropy;
  // Linear. Read through an sRGB transfer the joints come back at roughly a third of the
  // weight they were drawn at, and the floor goes back to being a mirror.
  mask.colorSpace = NoColorSpace;
  mask.needsUpdate = true;

  const nodes = material as unknown as INodeMaterial;
  nodes.roughnessNode = mix(
    float(material.roughness),
    float(FLOOR_GROUT_ROUGHNESS),
    textureNode(mask).r,
  );
}

function prepare(map: Texture, colorSpace: string, anisotropy: number): void {
  map.wrapS = RepeatWrapping;
  map.wrapT = RepeatWrapping;
  map.colorSpace = colorSpace;
  map.anisotropy = anisotropy;
}

/**
 * Leaded glass on one window.
 *
 * Which panel it gets comes from the flat colour it is replacing: the arcade already
 * alternates warm and cool lights down the nave, so reading that back keeps the rhythm the
 * building was designed with instead of inventing a second one.
 */
function dressGlass(mesh: Mesh, maps: ISurfaceTextures): void {
  const material = mesh.material;
  if (!(material instanceof MeshBasicMaterial)) return;
  const geometry = mesh.geometry;
  const ring = ringRadius(geometry);
  // The eye at the centre of the wheel is a disc barely a metre across, and the rose map
  // already draws one. Texturing it a second time only fights the tracery in front of it.
  if (ring !== undefined && ring < ROSE_MIN_RADIUS) return;

  const hex = material.color.getHex();
  const key: GlassName =
    ring !== undefined
      ? "glassRose"
      : hex === palette.glassWarm
        ? "glassWarm"
        : hex === palette.glassCool
          ? "glassCool"
          : "glassLancet";

  // Planes and rings already carry the 0..1 UVs one panel wants. The east lancets are three
  // extruded shapes welded into one mesh and carry UVs in metres, mixed with the side walls'
  // own, so those get rewritten from the local XY extent.
  if (geometry.type !== "PlaneGeometry" && ring === undefined) projectPanelUV(geometry);

  // One clone per window. The clone shares the image — so it is still a single upload — but
  // carries its own repeat and offset, which is what lets one lancet panel serve a 5.4 m
  // triple light and a 3.4 m aisle window without either of them being stretched.
  const map = maps[key].clone();
  map.colorSpace = SRGBColorSpace;
  map.anisotropy = 8;
  map.wrapS = RepeatWrapping;
  map.wrapT = ClampToEdgeWrapping;
  if (ring === undefined) fitPanel(map, geometry, GLASS_ASPECT[key]);
  map.needsUpdate = true;

  // Keep the window exactly as bright as the flat colour it replaces and let the map supply
  // the hue. The aisle lights and the east lancets were deliberately set to half value, and
  // a white base colour throws that away.
  const gain = luminance(material.color) / GLASS_LUMINANCE[key];

  // Every pane is `DoubleSide`, and all of them are seen from whichever side the geometry
  // happens to face. A back face shows the same UVs from behind, which is a left-to-right
  // mirror — fine for tracery, fatal for a saint holding a book. Flipping u on back faces
  // makes both sides read the same way round, and does it without needing to know which way
  // any particular window was built to face.
  // Keep V exactly as authored. Both the raw PNG desktop-native path and Three's KTX2
  // loader expose the panel upright to shader UVs; applying another V inversion turns the
  // standing saints upside down. Only U changes on a back face, to undo the mirror.
  const panel = uv();
  const facing = frontFacing.select(panel, vec2(panel.x.oneMinus(), panel.y));
  const sample = textureNode(map, facing);

  const nodes = material as unknown as INodeMaterial;
  nodes.colorNode = vec4(sample.rgb.mul(gain), sample.a);
  // The rose map is transparent outside its wheel, so the panel is a wheel even when the
  // geometry under it is not.
  material.alphaTest = key === "glassRose" ? 0.5 : 0;
  material.needsUpdate = true;
}

/**
 * Sets `repeat` and `offset` so the panel keeps its authored proportions on this opening.
 *
 * A wide opening gets whole panels side by side — three lights of a triple lancet get three
 * copies, and the seams land in the stone between them. A tall one shows as much of the
 * panel as fits, anchored at the head, since that is the end with the canopy on it.
 */
function fitPanel(map: Texture, geometry: BufferGeometry, panelAspect: number): void {
  geometry.computeBoundingBox();
  const box = geometry.boundingBox;
  if (box === null) return;
  const width = box.max.x - box.min.x;
  const height = box.max.y - box.min.y;
  if (width <= 0 || height <= 0) return;
  const columns = Math.max(1, Math.round(width / (height * panelAspect)));
  const panelHeight = width / columns / panelAspect;
  const rows = Math.min(1, height / panelHeight);
  map.repeat.set(columns, rows);
  map.offset.set(0, 1 - rows);
}

/**
 * Dresses the furnishings that carry a texture, and returns the group so the call site
 * stays one expression. Today that is the banners and nothing else.
 *
 * Deliberately *not* part of `applySurfaces`: the stone rules there classify by metalness
 * and colour luminance, and half the furnishings — the carpet, the pews, the plinths — are
 * unmetallic and dark enough that they would be dressed as vault stone.
 */
export function applyFurnishings(furnishings: Group, textures?: ISurfaceTextures): Group {
  const maps = textures ?? loaded;
  if (maps === undefined) {
    throw new Error("TN_SURFACES_NOT_LOADED: call loadSurfaces() from Scene.load() first.");
  }
  const cloths = new Set<MeshStandardMaterial>();
  const panels = new Set<BufferGeometry>();
  furnishings.traverse((object) => {
    if (!(object instanceof Mesh)) return;
    const material = object.material;
    // Matched on *structure*, not on a colour value. The banner cloth is the one furnishing
    // that is two-sided, and `furnishings.ts` says why: it bows, so at grazing angles the
    // far half of the curve turns its back to the camera. Matching the exact navy hex cost
    // a capture the moment that lane re-tinted the cloth to stop it clipping — and a tint
    // is exactly the kind of thing they should be free to move without breaking this file.
    if (!(material instanceof MeshStandardMaterial)) return;
    if (material.side !== DoubleSide || material.metalness !== 0) return;
    cloths.add(material);
    panels.add(object.geometry);
  });
  // Extruded from a swallowtail shape, so the UVs arrive in metres and mixed with the side
  // walls' own. One rewrite covers every banner: they share the geometry.
  for (const geometry of panels) projectPanelUV(geometry);
  if (!surfaceOff("banner")) for (const material of cloths) dressBanner(material, maps.banner);
  console.info(`TN_SURFACES_BANNERS:${JSON.stringify({ cloths: cloths.size })}`);
  return furnishings;
}

/** Navy damask, a gold cross patty, and a braid that follows the swallowtail hem. */
function dressBanner(material: MeshStandardMaterial, map: Texture): void {
  map.colorSpace = SRGBColorSpace;
  map.anisotropy = 8;
  map.wrapS = ClampToEdgeWrapping;
  map.wrapT = ClampToEdgeWrapping;
  map.needsUpdate = true;

  // The material's own colour is still what decides how dark the cloth is; the map only
  // says how it varies and where the gold goes. Read at apply time, so re-tinting the
  // banner in `furnishings.ts` still moves it.
  const gain = luminance(material.color) / BANNER_LUMINANCE;
  // Same two corrections the glass needs, and for the same reasons: V because these arrive
  // as KTX2 and a compressed texture cannot be flipped at upload, U on back faces because
  // the cloth is `DoubleSide` and a heraldic device is not left-right symmetric.
  const panel = vec2(uv().x, uv().y.oneMinus());
  const facing = frontFacing.select(panel, vec2(panel.x.oneMinus(), panel.y));

  const nodes = material as unknown as INodeMaterial;
  nodes.colorNode = textureNode(map, facing).rgb.mul(gain);
  material.needsUpdate = true;
}

/** Anything smaller than this and a disc of glass is the rose's eye, not the rose. */
const ROSE_MIN_RADIUS = 3;

/** Outer radius if this geometry is a disc or ring, otherwise undefined. */
function ringRadius(geometry: BufferGeometry): number | undefined {
  if (geometry.type !== "RingGeometry") return undefined;
  return (geometry as RingGeometry).parameters.outerRadius;
}

/** Rewrites `uv` so one copy of the panel covers the geometry's local XY extent. */
function projectPanelUV(geometry: BufferGeometry): void {
  const position = geometry.getAttribute("position");
  let minX = Number.POSITIVE_INFINITY;
  let minY = Number.POSITIVE_INFINITY;
  let maxX = Number.NEGATIVE_INFINITY;
  let maxY = Number.NEGATIVE_INFINITY;
  for (let index = 0; index < position.count; index += 1) {
    minX = Math.min(minX, position.getX(index));
    maxX = Math.max(maxX, position.getX(index));
    minY = Math.min(minY, position.getY(index));
    maxY = Math.max(maxY, position.getY(index));
  }
  const spanX = Math.max(maxX - minX, Number.EPSILON);
  const spanY = Math.max(maxY - minY, Number.EPSILON);
  const uv = new Float32Array(position.count * 2);
  for (let index = 0; index < position.count; index += 1) {
    uv[index * 2] = (position.getX(index) - minX) / spanX;
    uv[index * 2 + 1] = (position.getY(index) - minY) / spanY;
  }
  geometry.setAttribute("uv", new Float32BufferAttribute(uv, 2));
}
