// Generated by nobody: this is ordinary Three.js and ThreeNative does not read it.
//
// Finding the wicks on an authored candle stand.
//
// An authored glTF candelabrum arrives with its candles modelled as carved wax and no fire
// on them — every one of the Meshy pieces in `assets/` does. The flames have to be put
// there by this game, and the only hard part is *where*: a stand has eight or twelve
// tapers burnt to unequal lengths, and hand-listing their coordinates ties the scene to one
// version of one file. Replace the model and every flame hangs in the air beside a candle.
//
// So the tips are measured off the geometry instead. The observation the whole module rests
// on is that a wick is a local maximum of the mesh: cut the top slice of the model's height,
// and what survives is one small blob of vertices per taper, separated in plan. Cluster
// those blobs in XZ and each cluster's highest point is a wick.
//
// Measured in world space, after the model is placed. A model's own origin is not at its
// feet, its scale is whatever its author used, and compiled models are quantized — positions
// then arrive as normalized integers with the real units carried on the node transform.
// `Vector3.fromBufferAttribute` denormalizes and `applyMatrix4(matrixWorld)` restores the
// units, so reading the placed object is the one reading that is right for every input.

import { Box3, type Object3D, Mesh, Vector3 } from "three";

export interface IWickTip {
  readonly x: number;
  readonly y: number;
  readonly z: number;
  /** Vertices in the cluster. A caller can drop the thin ones as noise. */
  readonly weight: number;
}

export interface IWickOptions {
  /**
   * Slice of the model's total height to search, measured down from its highest point.
   *
   * Too small and only the tallest tapers are found — at 0.06 this model returned eight of
   * its twelve candles, because the other four are burnt down. Too large and the search
   * reaches the crossbar the tapers stand on, which is one continuous ring of vertices and
   * clusters into a single meaningless blob.
   */
  readonly topFraction?: number;
  /**
   * Cluster radius in plan, as a fraction of the model's larger horizontal extent.
   *
   * This is the taper *pitch*, not the taper width: two candles closer together than this
   * merge into one flame. 0.06 of the footprint separates candles at a 30° ring pitch.
   */
  readonly radiusFraction?: number;
  /** Clusters thinner than this are shading noise, not a candle. */
  readonly minWeight?: number;
}

interface IMutableCluster {
  sumX: number;
  sumZ: number;
  top: number;
  weight: number;
}

/**
 * Every wick on a placed model, in world coordinates.
 *
 * Returns tips in descending order of weight. The caller decides what a wick becomes —
 * this function knows nothing about flames, and deliberately: it reports where the candles
 * are and `furnishings.ts` owns what fire looks like.
 */
export function findWickTips(root: Object3D, options: IWickOptions = {}): IWickTip[] {
  const topFraction = options.topFraction ?? 0.12;
  const radiusFraction = options.radiusFraction ?? 0.06;
  const minWeight = options.minWeight ?? 24;

  root.updateMatrixWorld(true);
  const bounds = new Box3().setFromObject(root);
  const height = bounds.max.y - bounds.min.y;
  if (height <= 0) return [];
  const footprint = Math.max(bounds.max.x - bounds.min.x, bounds.max.z - bounds.min.z);
  const cut = bounds.max.y - height * topFraction;
  const radius = footprint * radiusFraction;

  const clusters: IMutableCluster[] = [];
  const point = new Vector3();
  root.traverse((object) => {
    if (!(object instanceof Mesh)) return;
    const position = object.geometry.getAttribute("position");
    if (position === undefined) return;
    for (let index = 0; index < position.count; index += 1) {
      point.fromBufferAttribute(position, index).applyMatrix4(object.matrixWorld);
      if (point.y < cut) continue;
      let joined = false;
      for (const cluster of clusters) {
        const dx = cluster.sumX / cluster.weight - point.x;
        const dz = cluster.sumZ / cluster.weight - point.z;
        if (dx * dx + dz * dz < radius * radius) {
          cluster.sumX += point.x;
          cluster.sumZ += point.z;
          cluster.weight += 1;
          cluster.top = Math.max(cluster.top, point.y);
          joined = true;
          break;
        }
      }
      if (!joined) clusters.push({ sumX: point.x, sumZ: point.z, top: point.y, weight: 1 });
    }
  });

  return clusters
    .filter((cluster) => cluster.weight >= minWeight)
    .sort((left, right) => right.weight - left.weight)
    .map((cluster) => ({
      x: cluster.sumX / cluster.weight,
      y: cluster.top,
      z: cluster.sumZ / cluster.weight,
      weight: cluster.weight,
    }));
}
