// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// `WorldEnvironment` is Godot's name for the node that says which lighting effects a scene
// runs and how strong they are, and the property names below are Godot's `Environment`
// properties where Godot has one (`ssr_enabled`, `glow_enabled`, `tonemap_mode`) and
// Three.js's node names where it does not (`ssgi`, `gtao`) — because Three.js is the
// rendering vocabulary and Godot is the node vocabulary. Nothing here is a new word.
//
// What it owns: which stages run, in what order, and an honest report of what actually
// happened. What it does not own: any colour, and any strength that is not a quality tier.
// Those are arguments, supplied below by the game.
import {
  ACESFilmicToneMapping,
  AgXToneMapping,
  type Camera,
  NeutralToneMapping,
  type DirectionalLight,
  type PerspectiveCamera,
  type Scene,
} from "three";
import { bloom } from "three/addons/tsl/display/BloomNode.js";
import { denoise } from "three/addons/tsl/display/DenoiseNode.js";
import { ssgi } from "three/addons/tsl/display/SSGINode.js";
import { bilateralBlur } from "three/addons/tsl/display/BilateralBlurNode.js";
import { godrays } from "three/addons/tsl/display/GodraysNode.js";
import { ao } from "three/addons/tsl/display/GTAONode.js";
import { sharpen } from "three/addons/tsl/display/SharpenNode.js";
import { ssr } from "three/addons/tsl/display/SSRNode.js";
import {
  color,
  convertToTexture,
  float,
  metalness,
  mrt,
  normalView,
  output,
  pass,
  roughness,
  screenUV,
  smoothstep,
  vec2,
} from "three/tsl";

// The TSL factories below (`ssgi`, `denoise`, `ssr`, `bloom`) all run their colour input
// through `convertToTexture`, which accepts any node at runtime. `@types/three` types the
// parameter as `TextureNode` regardless, so a composed `.mul().add()` result — a plain
// `Node<"vec4">` — is rejected by the compiler and accepted by the renderer. One narrow
// cast here, named and explained, beats scattering `as never` down the chain.
type ChainNode = Parameters<typeof bloom>[0];
const chain = (node: unknown): ChainNode => node as ChainNode;

type OutputRenderer = {
  kind: string;
  raw: unknown;
  setOutputNode(node: unknown): void;
};

/** Godot's `Environment.tonemap_mode`, with the modes Three.js actually ships. */
export type TonemapMode = "aces" | "agx" | "neutral";

/**
 * SSGI sample budget. The three tiers are the presets SSGINode's own documentation
 * recommends for the temporally-filtered case, not numbers invented here.
 */
export type SsgiQuality = "low" | "medium" | "high";

const SSGI_QUALITY: Record<SsgiQuality, { sliceCount: number; stepCount: number }> = {
  low: { sliceCount: 1, stepCount: 12 },
  medium: { sliceCount: 2, stepCount: 8 },
  high: { sliceCount: 3, stepCount: 16 },
};

export interface IWorldEnvironmentOptions {
  /** Screen-space indirect diffuse light. Godot calls this `ssil_enabled`. */
  readonly ssgiEnabled?: boolean;
  /** Why ssgi is off, reported verbatim in the stage report when `ssgiEnabled` is false. */
  readonly ssgiDisabledReason?: string;
  readonly ssgiQuality?: SsgiQuality;
  /** How much of the gathered indirect light reaches the frame. Godot's `ssil_intensity`. */
  readonly ssgiIntensity?: number;
  /** How far, in world units, indirect light is gathered from. */
  readonly ssgiRadius?: number;
  /** Screen-space reflections. Godot's `ssr_enabled`. */
  readonly ssrEnabled?: boolean;
  /**
   * How far, in world units, a reflection ray is traced.
   *
   * `SSRNode` defaults this to **1**, which is one metre. On any scene larger than a
   * tabletop that reads as "screen-space reflections are on and do nothing" — the ray
   * terminates before it reaches the thing that should be standing in the floor.
   */
  readonly ssrMaxDistance?: number;
  /**
   * Fraction of the display resolution the reflection is traced at.
   *
   * A reflection in a rough surface carries almost no high-frequency detail, so tracing it
   * at half resolution costs a quarter of the rays and is very hard to see in the result.
   */
  readonly ssrResolutionScale?: number;
  /** Spatial denoise over the SSGI result. Off is noisier and cheaper. */
  readonly denoiseEnabled?: boolean;
  /** Raymarched shafts. Needs `godraysLight`, and that light must cast shadows. */
  readonly godraysEnabled?: boolean;
  /** How dense the participating medium is. Higher is foggier. */
  readonly godraysDensity?: number;
  /**
   * Haze below this value is discarded instead of added to the frame.
   *
   * Without it the pass is a uniform brightener rather than a shaft renderer. It returns a
   * non-zero value for nearly every pixel, because in a building lit through a clerestory
   * most of the upper volume genuinely is lit — so every view ray accumulates something.
   * That "something" is tiny in linear space and enormous after the tone curve, which
   * lifts shadows hardest: measured on the cathedral, the darkest 5% of the frame sat at
   * luminance 71 of 255 with godrays on and 4 with them off, against 7 in the reference.
   *
   * Subtracting a floor keeps the air inside a real beam and discards the ambient lift.
   */
  readonly godraysFloor?: number;
  /** Multiplier applied after the floor, so beams can be bright without the haze returning. */
  readonly godraysIntensity?: number;
  /**
   * Radius, in pixels, of the separable bilateral blur applied to the shaft mask.
   *
   * `GodraysNode`'s own documentation asks for this: *"After the godrays have been computed,
   * it's recommened to apply a Bilateral Blur to the result to mitigate raymarching and noise
   * artifacts."* Skipping it leaves the raymarch's step boundaries visible as slabs across
   * every surface a shaft crosses, which reads as low-resolution rather than as light.
   *
   * Bilateral rather than gaussian because it is edge-preserving: the point of a shaft is
   * its hard edge where a mullion cuts it, and an ordinary blur would soften exactly that.
   * Zero disables the blur.
   */
  readonly godraysBlur?: number;
  /**
   * Raymarch steps per pixel. `GodraysNode` defaults to 60.
   *
   * Every step is a shadow-map sample, so this multiplies directly into the cost of the
   * whole pass. The pass jitters its sample positions with interleaved noise, so a lower
   * count trades a hard shaft edge for a slightly noisier one rather than for banding —
   * which the denoise and temporal stages then largely absorb.
   */
  readonly godraysSteps?: number;
  /**
   * Ceiling on shaft brightness.
   *
   * This is also the single strongest control over how bright the *whole* scene looks. The
   * pass adds its accumulated illumination to every pixel, not only to the pixels inside a
   * visible beam, so raising it raises the shadow floor of the entire frame. Measured on
   * the cathedral: with godrays on, the darkest tenth of the frame sat at luminance 55.8
   * of 255; with them off it sat at 1.4, and the frame mean halved from 97 to 46.
   */
  readonly godraysMaxDensity?: number;
  /**
   * Ground-truth ambient occlusion, at contact scale. Godot's `ssao_enabled`.
   *
   * Deliberately a *second* occlusion term next to the one SSGI already produces, not a
   * replacement for it. SSGI's AO is gathered over `ssgiRadius` — metres, in this scene —
   * which is the right scale for "this aisle is enclosed" and the wrong one for "this
   * candelabra foot is standing on this floor". A gather that wide returns almost the same
   * value for the pixel under the foot and the pixel beside it, so the contact never
   * darkens and the prop reads as pasted onto the floor rather than resting on it. This
   * pass runs at a radius of centimetres and multiplies on top.
   */
  readonly gtaoEnabled?: boolean;
  /** Occlusion gather radius in world units. Contact scale, not room scale. */
  readonly gtaoRadius?: number;
  /** Exponent on the occlusion term: higher is a darker, tighter contact. */
  readonly gtaoScale?: number;
  /** Directions sampled per pixel. Cost is linear in this. */
  readonly gtaoSamples?: number;
  /** Fraction of display resolution the occlusion is traced at. */
  readonly gtaoResolutionScale?: number;
  /**
   * Contrast-adaptive sharpening (RCAS) over the finished frame.
   *
   * Everything upstream of it blurs: the GI gather is denoised, the reflection is traced at
   * half resolution and roughness-blurred, and the godray mask is bilateral-blurred. Each
   * of those is worth its softness on its own and the sum of them is a frame with no
   * micro-detail left in the stone. RCAS is contrast-adaptive, so it puts the edges back
   * without ringing the shafts.
   */
  readonly sharpenEnabled?: boolean;
  /** RCAS sharpness. **0 is maximum sharpening and 2 is none** — it is a radius, not a gain. */
  readonly sharpenStrength?: number;
  /** Corner darkening, as a fraction removed at the extreme corner. Zero disables it. */
  readonly vignetteAmount?: number;
  /** Godot's `glow_enabled`. */
  readonly bloomEnabled?: boolean;
  readonly bloomStrength?: number;
  readonly tonemapMode?: TonemapMode;
  readonly exposure?: number;
}

/** One stage of the chain, and whether it ran. */
export interface IStageReport {
  readonly stage: string;
  readonly applied: boolean;
  /** Present only when `applied` is false. Never blank — a dropped stage always says why. */
  readonly reason?: string;
}

export interface IWorldEnvironmentReport {
  readonly rendererKind: string;
  readonly stages: readonly IStageReport[];
}

const TONEMAP: Record<TonemapMode, number> = {
  aces: ACESFilmicToneMapping,
  agx: AgXToneMapping,
  neutral: NeutralToneMapping,
};

/**
 * Installs a lighting chain and reports what of it actually ran.
 *
 * The reason this is a class and not four lines at the call site is ordering and honesty.
 * AO and GI must be gathered before they are denoised, denoised before they are added to
 * the beauty pass, and everything must precede tonemapping; get that wrong and the frame is
 * dim or noisy with nothing saying which. And a stage that could not run — no WebGPU, no
 * `rg11b10ufloat-renderable` — has to be *named*, or a game with GI silently switched off
 * looks exactly like a game that chose not to use it.
 */
export class WorldEnvironment {
  readonly #options: Required<IWorldEnvironmentOptions>;
  #report: IWorldEnvironmentReport | undefined;

  constructor(options: IWorldEnvironmentOptions = {}) {
    const quality = options.ssgiQuality ?? "medium";
    if (SSGI_QUALITY[quality] === undefined) {
      // Fail closed. A typo'd tier that silently became "medium" is a quality setting
      // nobody can trust afterwards.
      throw new Error(
        `Unknown ssgiQuality '${quality}'. Use one of: ${Object.keys(SSGI_QUALITY).join(", ")}.`,
      );
    }
    const tonemapMode = options.tonemapMode ?? "aces";
    if (TONEMAP[tonemapMode] === undefined) {
      throw new Error(
        `Unknown tonemapMode '${tonemapMode}'. Use one of: ${Object.keys(TONEMAP).join(", ")}.`,
      );
    }
    this.#options = {
      ssgiEnabled: options.ssgiEnabled ?? true,
      ssgiDisabledReason: options.ssgiDisabledReason ?? "ssgiEnabled is false",
      ssgiQuality: quality,
      ssgiIntensity: options.ssgiIntensity ?? 1,
      ssgiRadius: options.ssgiRadius ?? 12,
      ssrEnabled: options.ssrEnabled ?? false,
      ssrMaxDistance: options.ssrMaxDistance ?? 1,
      ssrResolutionScale: options.ssrResolutionScale ?? 1,
      denoiseEnabled: options.denoiseEnabled ?? true,
      godraysEnabled: options.godraysEnabled ?? false,
      godraysDensity: options.godraysDensity ?? 0.7,
      godraysFloor: options.godraysFloor ?? 0,
      godraysIntensity: options.godraysIntensity ?? 1,
      godraysSteps: options.godraysSteps ?? 60,
      godraysBlur: options.godraysBlur ?? 0,
      godraysMaxDensity: options.godraysMaxDensity ?? 0.5,
      gtaoEnabled: options.gtaoEnabled ?? false,
      gtaoRadius: options.gtaoRadius ?? 0.25,
      gtaoScale: options.gtaoScale ?? 1,
      gtaoSamples: options.gtaoSamples ?? 16,
      gtaoResolutionScale: options.gtaoResolutionScale ?? 1,
      sharpenEnabled: options.sharpenEnabled ?? false,
      sharpenStrength: options.sharpenStrength ?? 0.2,
      vignetteAmount: options.vignetteAmount ?? 0,
      bloomEnabled: options.bloomEnabled ?? true,
      bloomStrength: options.bloomStrength ?? 0.7,
      tonemapMode,
      exposure: options.exposure ?? 1,
    };
  }

  /** What ran, after `apply`. Undefined before it, never a guess. */
  get applied(): IWorldEnvironmentReport | undefined {
    return this.#report;
  }

  apply(
    renderer: OutputRenderer,
    scene: Scene,
    camera: Camera,
    /** The light godrays are raymarched against. Required only when `godraysEnabled`. */
    godraysLight?: DirectionalLight,
  ): IWorldEnvironmentReport {
    const options = this.#options;
    const raw = renderer.raw as { toneMapping?: number; toneMappingExposure?: number };
    raw.toneMapping = TONEMAP[options.tonemapMode];
    // `toneMappingExposure` is set for the non-WebGPU path below, and it is *not* what
    // exposes the node chain: once `setOutputNode` installs a `RenderPipeline`, the
    // renderer's exposure scalar no longer reaches the frame. Measured — moving it from
    // 0.85 to 1.45 changed nothing at all on screen. Exposure is applied as a multiply on
    // the scene pass instead, which is also the physically right place for it: it is the
    // shutter, so it belongs before the tone curve rather than after.
    raw.toneMappingExposure = options.exposure;

    const stages: IStageReport[] = [];
    const off = (stage: string, reason: string): void => {
      stages.push({ stage, applied: false, reason });
    };

    if (renderer.kind !== "webgpu") {
      // Everything below is a TSL node graph, and `setOutputNode` throws on any other
      // renderer. Say so once, per stage, instead of returning in silence.
      const reason = `renderer kind is '${renderer.kind}', not 'webgpu'`;
      const all = ["ssgi", "denoise", "gtao", "godrays", "ssr", "bloom", "sharpen", "vignette"];
      for (const stage of all) off(stage, reason);
      this.#report = { rendererKind: renderer.kind, stages };
      return this.#report;
    }

    // Normals come from a second render target on the scene pass. SSGI can derive them
    // from depth alone, but the derived normal is flat across a triangle, which shows up
    // as faceted bounce on exactly the smooth surfaces GI is bought for.
    const scenePass = pass(scene, camera);
    // Metalness and roughness ride along in the same multi-render-target as the normals.
    // Without them SSR has no way to know which pixels are supposed to reflect, and with
    // `reflectNonMetals` it would mirror every matte wall in the building.
    scenePass.setMRT(mrt({ output, normal: normalView, metalness, roughness }));
    const colour = scenePass.getTextureNode("output");
    const depth = scenePass.getTextureNode("depth");
    const normal = scenePass.getTextureNode("normal");
    const metal = scenePass.getTextureNode("metalness");
    const rough = scenePass.getTextureNode("roughness");
    // Every stage here is perspective-camera maths — view-space reconstruction from depth,
    // and a projection matrix inverse. The scene's camera is the one the pass rendered with.
    const view = camera as PerspectiveCamera;

    // Scene-referred exposure. Everything downstream — GI gather, reflections, bloom
    // threshold — sees the exposed image, which is what makes the bloom threshold mean the
    // same thing at any exposure.
    const exposed = chain(colour.mul(options.exposure));
    let lit: ChainNode = exposed;

    if (options.ssgiEnabled) {
      const gi = ssgi(exposed, depth, normal, view);
      const tier = SSGI_QUALITY[options.ssgiQuality];
      gi.sliceCount.value = tier.sliceCount;
      gi.stepCount.value = tier.stepCount;
      gi.radius.value = options.ssgiRadius;

      // SSGI writes two targets: AO in a single-channel `RedFormat` texture, and the GI
      // term in an RGB one. Multiplying the beauty pass by the whole AO vec4 therefore
      // zeroes green and blue and the entire room renders monochrome red — take `.r` for
      // the scalar and `.rgb` for the colour.
      //
      // No albedo buffer here, so the beauty pass stands in for it: occlusion darkens what
      // is already lit, and the gathered indirect light is tinted by the surface it lands
      // on. That is the standard approximation, and it is why a red wall tints a white
      // floor at all.
      let ao: ChainNode = chain(gi.getAONode());
      let indirect: ChainNode = chain(gi.getGINode());
      if (options.denoiseEnabled) {
        ao = chain(denoise(ao, depth, normal, view));
        indirect = chain(denoise(indirect, depth, normal, view));
        stages.push({ stage: "denoise", applied: true });
      } else {
        off("denoise", "denoiseEnabled is false");
      }
      // Occlusion darkens the direct term; the gathered indirect adds on top of it, tinted
      // by the surface it lands on. `ssgiIntensity` is the game's dial on that second term —
      // gathered light is unbounded, and a Cornell box at 1.0 blows out.
      lit = chain(exposed.mul(ao.r).add(exposed.mul(indirect.rgb).mul(options.ssgiIntensity)));
      stages.push({ stage: "ssgi", applied: true });
    } else {
      off("ssgi", options.ssgiDisabledReason ?? "ssgiEnabled is false");
      off("denoise", "nothing to denoise with ssgi off");
    }

    // Contact occlusion, before the air. Order matters and this is the only place it can
    // go: the godray pass adds *scattered light in the air between the camera and the
    // surface*, and no amount of geometry at the surface occludes that. Multiplying the
    // contact term over a frame that already has haze in it darkens the haze instead of the
    // contact, which reads as a dirty lens rather than as a foot on a floor.
    if (options.gtaoEnabled) {
      const contact = ao(depth, normal, view);
      contact.radius.value = options.gtaoRadius;
      contact.scale.value = options.gtaoScale;
      contact.samples.value = options.gtaoSamples;
      contact.resolutionScale = options.gtaoResolutionScale;
      // `RedFormat`, like SSGI's AO target: `.r` is the whole occlusion term, and
      // multiplying by the vec4 would zero green and blue and render the nave in red.
      lit = chain(lit.mul(chain(contact).r));
      stages.push({ stage: "gtao", applied: true });
    } else {
      off("gtao", "gtaoEnabled is false");
    }

    if (options.godraysEnabled) {
      // Godrays are raymarched against the light's shadow map: the shaft is the volume the
      // shadow map reports as lit. A light that casts no shadow yields a black pass, which
      // would read as "godrays are on and do nothing" — so refuse it by name instead.
      if (godraysLight === undefined) {
        off("godrays", "godraysEnabled is true but no light was passed to apply()");
      } else if (godraysLight.castShadow !== true) {
        off("godrays", `light '${godraysLight.name || "sun"}' does not cast shadows`);
      } else {
        const shafts = godrays(depth, view, godraysLight);
        shafts.density.value = options.godraysDensity;
        shafts.maxDensity.value = options.godraysMaxDensity;
        shafts.raymarchSteps.value = options.godraysSteps;
        // The pass jitters its samples with interleaved noise, and at 24 steps the noise
        // renders as a regular honeycomb lattice over every hazy pixel — visible even on
        // the dark stone the scatter barely touches. The bilateral denoiser built for the
        // GI gather smooths exactly that: high-frequency, depth-coherent, and the shaft
        // edges survive because they sit on geometry silhouettes the depth term owns.
        // Denoise before the floor: the floor's subtraction amplifies relative noise on
        // near-floor values, so cleaning the raw accumulation is worth more per pass.
        let shaft: ChainNode = chain(shafts);
        if (options.denoiseEnabled) {
          shaft = chain(denoise(shaft, depth, normal, view));
        }
        // Floor, then scale, then tint. The floor is what turns this from a whole-frame
        // brightener into a shaft renderer; the tint by the light's own colour is what
        // stops a warm sun throwing a white beam.
        const cleaned = chain(
          shaft.rgb.sub(options.godraysFloor).max(0).mul(options.godraysIntensity),
        );
        lit = chain(lit.add(cleaned.mul(color(godraysLight.color))));
        stages.push({ stage: "godrays", applied: true });
      }
    } else {
      off("godrays", "godraysEnabled is false");
    }

    if (options.ssrEnabled) {
      // SSR wants the normal as vec3; the MRT target hands it over as vec4 with an
      // unused alpha. `.xyz` is the whole conversion.
      // Three defaults that together make SSR silently do nothing on a real scene, all
      // fixed here and each worth stating:
      //   maxDistance   defaults to 1 world unit — a ray that dies after a metre
      //   reflectNonMetals  defaults to false, so a polished *stone* floor never reflects
      //   roughnessNode     null means every surface is treated as a perfect mirror
      // `normal`, not `normal.xyz`. SSR calls `.sample()` on this node, so it needs the
      // whole TextureNode; a swizzle produces a plain vec3 and the pass dies at shader
      // build with `this.normalNode.sample is not a function`. `@types/three` declares the
      // parameter as `Node<"vec3">`, which is what makes the swizzle look correct — the
      // types are wrong here and the runtime is right.
      // Both `colorNode` and `normalNode` are `.sample()`d inside the pass, so both must be
      // real texture nodes. `lit` at this point is a composed `.mul().add()` expression —
      // `convertToTexture` resolves it into a render target the pass can sample. `ssgi()`
      // does this conversion for you in its factory; `ssr()` does not.
      // Materialise the chain ONCE and reuse that texture on both sides of the add.
      //
      // Passing `convertToTexture(lit)` to the pass while adding the reflections back onto
      // the unconverted `lit` builds two parallel copies of the same graph — one rendered
      // into a target, one not. With bloom on, bloom's own conversion re-materialised the
      // second copy and it happened to work. With bloom off the second copy never got
      // scheduled and the frame came out as the bare background colour. Measured: bloom
      // off alone rendered blank, bloom off plus SSR off rendered, bloom off plus godrays
      // off rendered — the blank needed all three conditions, which is what a dangling
      // graph branch looks like from the outside.
      const base = convertToTexture(lit);
      const reflections = ssr(base, depth, normal as unknown as Parameters<typeof ssr>[2], {
        camera: view,
        metalnessNode: metal.r,
        roughnessNode: rough.g,
        reflectNonMetals: true,
      });
      reflections.maxDistance.value = options.ssrMaxDistance;
      reflections.resolutionScale = options.ssrResolutionScale;
      lit = chain(chain(base).add(reflections));
      stages.push({ stage: "ssr", applied: true });
    } else {
      off("ssr", "ssrEnabled is false");
    }

    if (options.bloomEnabled) {
      lit = chain(lit.add(bloom(lit, options.bloomStrength, 0.5, 0.2)));
      stages.push({ stage: "bloom", applied: true });
    } else {
      off("bloom", "bloomEnabled is false");
    }

    // Last of the image stages, because RCAS is defined on the finished picture: it looks
    // at the contrast around a pixel and sharpens in proportion to it, so running it before
    // bloom would sharpen edges that bloom then spreads back out.
    if (options.sharpenEnabled) {
      lit = chain(sharpen(convertToTexture(lit), options.sharpenStrength));
      stages.push({ stage: "sharpen", applied: true });
    } else {
      off("sharpen", "sharpenEnabled is false");
    }

    // Folded into the last expression rather than given a pass of its own: it is one
    // multiply by a function of the screen coordinate, and a full-screen pass to do a
    // multiply would cost a render target's bandwidth to save nothing.
    if (options.vignetteAmount > 0) {
      // Radius measured from the centre in screen-diagonal units, so the corner is 1 and
      // the falloff does not change shape when the window does. It starts at 0.55 — well
      // outside the subject in a 16:9 frame — so the vignette is a corner, not a spotlight.
      const radius = screenUV.sub(vec2(0.5, 0.5)).mul(vec2(1.78, 1)).length().mul(1.04);
      const fall = smoothstep(float(0.55), float(1.02), radius).mul(options.vignetteAmount);
      lit = chain(lit.mul(fall.oneMinus()));
      stages.push({ stage: "vignette", applied: true });
    } else {
      off("vignette", "vignetteAmount is 0");
    }

    renderer.setOutputNode(lit);
    this.#report = { rendererKind: renderer.kind, stages };
    // One line a playtest, a console reader and `doctor` can all grep. A convention turned
    // off must not turn its measurement off.
    console.info(`TN_WORLD_ENVIRONMENT:${JSON.stringify(this.#report)}`);
    return this.#report;
  }
}
