// Generated by hand for this game: ordinary Three.js. ThreeNative does not read this file.
//
// `WorldEnvironment` is Godot's name for the node that says which lighting effects a scene
// runs and how strong they are, and the property names below are Godot's `Environment`
// properties where Godot has one (`ssr_enabled`, `glow_enabled`, `tonemap_mode`) and
// Three.js's node names where it does not (`ssgi`, `gtao`) — because Three.js is the
// rendering vocabulary and Godot is the node vocabulary. Nothing here is a new word.
//
// What it owns: which stages run, in what order, and an honest report of what actually
// happened. What it does not own: any colour, and any strength that is not a quality tier.
// Those are arguments, supplied below by the game.
import {
  ACESFilmicToneMapping,
  AgXToneMapping,
  type Camera,
  NeutralToneMapping,
  type DirectionalLight,
  type PerspectiveCamera,
  type Scene,
} from "three";
import { bloom } from "three/addons/tsl/display/BloomNode.js";
import { denoise } from "three/addons/tsl/display/DenoiseNode.js";
import { ssgi } from "three/addons/tsl/display/SSGINode.js";
import { godrays } from "three/addons/tsl/display/GodraysNode.js";
import { ssr } from "three/addons/tsl/display/SSRNode.js";
import { color, convertToTexture, metalness, mrt, normalView, output, pass, roughness } from "three/tsl";

// The TSL factories below (`ssgi`, `denoise`, `ssr`, `bloom`) all run their colour input
// through `convertToTexture`, which accepts any node at runtime. `@types/three` types the
// parameter as `TextureNode` regardless, so a composed `.mul().add()` result — a plain
// `Node<"vec4">` — is rejected by the compiler and accepted by the renderer. One narrow
// cast here, named and explained, beats scattering `as never` down the chain.
type ChainNode = Parameters<typeof bloom>[0];
const chain = (node: unknown): ChainNode => node as ChainNode;

type OutputRenderer = {
  kind: string;
  raw: unknown;
  setOutputNode(node: unknown): void;
};

/** Godot's `Environment.tonemap_mode`, with the modes Three.js actually ships. */
export type TonemapMode = "aces" | "agx" | "neutral";

/**
 * SSGI sample budget. The three tiers are the presets SSGINode's own documentation
 * recommends for the temporally-filtered case, not numbers invented here.
 */
export type SsgiQuality = "low" | "medium" | "high";

const SSGI_QUALITY: Record<SsgiQuality, { sliceCount: number; stepCount: number }> = {
  low: { sliceCount: 1, stepCount: 12 },
  medium: { sliceCount: 2, stepCount: 8 },
  high: { sliceCount: 3, stepCount: 16 },
};

export interface IWorldEnvironmentOptions {
  /** Screen-space indirect diffuse light. Godot calls this `ssil_enabled`. */
  readonly ssgiEnabled?: boolean;
  readonly ssgiQuality?: SsgiQuality;
  /** How much of the gathered indirect light reaches the frame. Godot's `ssil_intensity`. */
  readonly ssgiIntensity?: number;
  /** How far, in world units, indirect light is gathered from. */
  readonly ssgiRadius?: number;
  /** Screen-space reflections. Godot's `ssr_enabled`. */
  readonly ssrEnabled?: boolean;
  /**
   * How far, in world units, a reflection ray is traced.
   *
   * `SSRNode` defaults this to **1**, which is one metre. On any scene larger than a
   * tabletop that reads as "screen-space reflections are on and do nothing" — the ray
   * terminates before it reaches the thing that should be standing in the floor.
   */
  readonly ssrMaxDistance?: number;
  /**
   * Fraction of the display resolution the reflection is traced at.
   *
   * A reflection in a rough surface carries almost no high-frequency detail, so tracing it
   * at half resolution costs a quarter of the rays and is very hard to see in the result.
   */
  readonly ssrResolutionScale?: number;
  /** Spatial denoise over the SSGI result. Off is noisier and cheaper. */
  readonly denoiseEnabled?: boolean;
  /** Raymarched shafts. Needs `godraysLight`, and that light must cast shadows. */
  readonly godraysEnabled?: boolean;
  /** How dense the participating medium is. Higher is foggier. */
  readonly godraysDensity?: number;
  /** Ceiling on shaft brightness, so a shaft never turns into a white wall. */
  readonly godraysMaxDensity?: number;
  /** Godot's `glow_enabled`. */
  readonly bloomEnabled?: boolean;
  readonly bloomStrength?: number;
  readonly tonemapMode?: TonemapMode;
  readonly exposure?: number;
}

/** One stage of the chain, and whether it ran. */
export interface IStageReport {
  readonly stage: string;
  readonly applied: boolean;
  /** Present only when `applied` is false. Never blank — a dropped stage always says why. */
  readonly reason?: string;
}

export interface IWorldEnvironmentReport {
  readonly rendererKind: string;
  readonly stages: readonly IStageReport[];
}

const TONEMAP: Record<TonemapMode, number> = {
  aces: ACESFilmicToneMapping,
  agx: AgXToneMapping,
  neutral: NeutralToneMapping,
};

/**
 * Installs a lighting chain and reports what of it actually ran.
 *
 * The reason this is a class and not four lines at the call site is ordering and honesty.
 * AO and GI must be gathered before they are denoised, denoised before they are added to
 * the beauty pass, and everything must precede tonemapping; get that wrong and the frame is
 * dim or noisy with nothing saying which. And a stage that could not run — no WebGPU, no
 * `rg11b10ufloat-renderable` — has to be *named*, or a game with GI silently switched off
 * looks exactly like a game that chose not to use it.
 */
export class WorldEnvironment {
  readonly #options: Required<IWorldEnvironmentOptions>;
  #report: IWorldEnvironmentReport | undefined;

  constructor(options: IWorldEnvironmentOptions = {}) {
    const quality = options.ssgiQuality ?? "medium";
    if (SSGI_QUALITY[quality] === undefined) {
      // Fail closed. A typo'd tier that silently became "medium" is a quality setting
      // nobody can trust afterwards.
      throw new Error(
        `Unknown ssgiQuality '${quality}'. Use one of: ${Object.keys(SSGI_QUALITY).join(", ")}.`,
      );
    }
    const tonemapMode = options.tonemapMode ?? "aces";
    if (TONEMAP[tonemapMode] === undefined) {
      throw new Error(
        `Unknown tonemapMode '${tonemapMode}'. Use one of: ${Object.keys(TONEMAP).join(", ")}.`,
      );
    }
    this.#options = {
      ssgiEnabled: options.ssgiEnabled ?? true,
      ssgiQuality: quality,
      ssgiIntensity: options.ssgiIntensity ?? 1,
      ssgiRadius: options.ssgiRadius ?? 12,
      ssrEnabled: options.ssrEnabled ?? false,
      ssrMaxDistance: options.ssrMaxDistance ?? 1,
      ssrResolutionScale: options.ssrResolutionScale ?? 1,
      denoiseEnabled: options.denoiseEnabled ?? true,
      godraysEnabled: options.godraysEnabled ?? false,
      godraysDensity: options.godraysDensity ?? 0.7,
      godraysMaxDensity: options.godraysMaxDensity ?? 0.5,
      bloomEnabled: options.bloomEnabled ?? true,
      bloomStrength: options.bloomStrength ?? 0.7,
      tonemapMode,
      exposure: options.exposure ?? 1,
    };
  }

  /** What ran, after `apply`. Undefined before it, never a guess. */
  get applied(): IWorldEnvironmentReport | undefined {
    return this.#report;
  }

  apply(
    renderer: OutputRenderer,
    scene: Scene,
    camera: Camera,
    /** The light godrays are raymarched against. Required only when `godraysEnabled`. */
    godraysLight?: DirectionalLight,
  ): IWorldEnvironmentReport {
    const options = this.#options;
    const raw = renderer.raw as { toneMapping?: number; toneMappingExposure?: number };
    raw.toneMapping = TONEMAP[options.tonemapMode];
    raw.toneMappingExposure = options.exposure;

    const stages: IStageReport[] = [];
    const off = (stage: string, reason: string): void => {
      stages.push({ stage, applied: false, reason });
    };

    if (renderer.kind !== "webgpu") {
      // Everything below is a TSL node graph, and `setOutputNode` throws on any other
      // renderer. Say so once, per stage, instead of returning in silence.
      const reason = `renderer kind is '${renderer.kind}', not 'webgpu'`;
      for (const stage of ["ssgi", "denoise", "godrays", "ssr", "bloom"]) off(stage, reason);
      this.#report = { rendererKind: renderer.kind, stages };
      return this.#report;
    }

    // Normals come from a second render target on the scene pass. SSGI can derive them
    // from depth alone, but the derived normal is flat across a triangle, which shows up
    // as faceted bounce on exactly the smooth surfaces GI is bought for.
    const scenePass = pass(scene, camera);
    // Metalness and roughness ride along in the same multi-render-target as the normals.
    // Without them SSR has no way to know which pixels are supposed to reflect, and with
    // `reflectNonMetals` it would mirror every matte wall in the building.
    scenePass.setMRT(mrt({ output, normal: normalView, metalness, roughness }));
    const colour = scenePass.getTextureNode("output");
    const depth = scenePass.getTextureNode("depth");
    const normal = scenePass.getTextureNode("normal");
    const metal = scenePass.getTextureNode("metalness");
    const rough = scenePass.getTextureNode("roughness");
    // Every stage here is perspective-camera maths — view-space reconstruction from depth,
    // and a projection matrix inverse. The scene's camera is the one the pass rendered with.
    const view = camera as PerspectiveCamera;

    let lit: ChainNode = chain(colour);

    if (options.ssgiEnabled) {
      const gi = ssgi(chain(colour), depth, normal, view);
      const tier = SSGI_QUALITY[options.ssgiQuality];
      gi.sliceCount.value = tier.sliceCount;
      gi.stepCount.value = tier.stepCount;
      gi.radius.value = options.ssgiRadius;

      // SSGI writes two targets: AO in a single-channel `RedFormat` texture, and the GI
      // term in an RGB one. Multiplying the beauty pass by the whole AO vec4 therefore
      // zeroes green and blue and the entire room renders monochrome red — take `.r` for
      // the scalar and `.rgb` for the colour.
      //
      // No albedo buffer here, so the beauty pass stands in for it: occlusion darkens what
      // is already lit, and the gathered indirect light is tinted by the surface it lands
      // on. That is the standard approximation, and it is why a red wall tints a white
      // floor at all.
      let ao: ChainNode = chain(gi.getAONode());
      let indirect: ChainNode = chain(gi.getGINode());
      if (options.denoiseEnabled) {
        ao = chain(denoise(ao, depth, normal, view));
        indirect = chain(denoise(indirect, depth, normal, view));
        stages.push({ stage: "denoise", applied: true });
      } else {
        off("denoise", "denoiseEnabled is false");
      }
      // Occlusion darkens the direct term; the gathered indirect adds on top of it, tinted
      // by the surface it lands on. `ssgiIntensity` is the game's dial on that second term —
      // gathered light is unbounded, and a Cornell box at 1.0 blows out.
      lit = chain(colour.mul(ao.r).add(colour.mul(indirect.rgb).mul(options.ssgiIntensity)));
      stages.push({ stage: "ssgi", applied: true });
    } else {
      off("ssgi", "ssgiEnabled is false");
      off("denoise", "nothing to denoise with ssgi off");
    }

    if (options.godraysEnabled) {
      // Godrays are raymarched against the light's shadow map: the shaft is the volume the
      // shadow map reports as lit. A light that casts no shadow yields a black pass, which
      // would read as "godrays are on and do nothing" — so refuse it by name instead.
      if (godraysLight === undefined) {
        off("godrays", "godraysEnabled is true but no light was passed to apply()");
      } else if (godraysLight.castShadow !== true) {
        off("godrays", `light '${godraysLight.name || "sun"}' does not cast shadows`);
      } else {
        const shafts = godrays(depth, view, godraysLight);
        shafts.density.value = options.godraysDensity;
        shafts.maxDensity.value = options.godraysMaxDensity;
        // The pass returns a grey shaft mask. Tinting it by the light's own colour is
        // what stops a warm sun throwing a white shaft.
        lit = chain(lit.add(chain(shafts).rgb.mul(color(godraysLight.color))));
        stages.push({ stage: "godrays", applied: true });
      }
    } else {
      off("godrays", "godraysEnabled is false");
    }

    if (options.ssrEnabled) {
      // SSR wants the normal as vec3; the MRT target hands it over as vec4 with an
      // unused alpha. `.xyz` is the whole conversion.
      // Three defaults that together make SSR silently do nothing on a real scene, all
      // fixed here and each worth stating:
      //   maxDistance   defaults to 1 world unit — a ray that dies after a metre
      //   reflectNonMetals  defaults to false, so a polished *stone* floor never reflects
      //   roughnessNode     null means every surface is treated as a perfect mirror
      // `normal`, not `normal.xyz`. SSR calls `.sample()` on this node, so it needs the
      // whole TextureNode; a swizzle produces a plain vec3 and the pass dies at shader
      // build with `this.normalNode.sample is not a function`. `@types/three` declares the
      // parameter as `Node<"vec3">`, which is what makes the swizzle look correct — the
      // types are wrong here and the runtime is right.
      // Both `colorNode` and `normalNode` are `.sample()`d inside the pass, so both must be
      // real texture nodes. `lit` at this point is a composed `.mul().add()` expression —
      // `convertToTexture` resolves it into a render target the pass can sample. `ssgi()`
      // does this conversion for you in its factory; `ssr()` does not.
      const reflections = ssr(convertToTexture(lit), depth, normal as unknown as Parameters<typeof ssr>[2], {
        camera: view,
        metalnessNode: metal.r,
        roughnessNode: rough.g,
        reflectNonMetals: true,
      });
      reflections.maxDistance.value = options.ssrMaxDistance;
      reflections.resolutionScale = options.ssrResolutionScale;
      lit = chain(lit.add(reflections));
      stages.push({ stage: "ssr", applied: true });
    } else {
      off("ssr", "ssrEnabled is false");
    }

    if (options.bloomEnabled) {
      lit = chain(lit.add(bloom(lit, options.bloomStrength, 0.5, 0.2)));
      stages.push({ stage: "bloom", applied: true });
    } else {
      off("bloom", "bloomEnabled is false");
    }

    renderer.setOutputNode(lit);
    this.#report = { rendererKind: renderer.kind, stages };
    // One line a playtest, a console reader and `doctor` can all grep. A convention turned
    // off must not turn its measurement off.
    console.info(`TN_WORLD_ENVIRONMENT:${JSON.stringify(this.#report)}`);
    return this.#report;
  }
}
